# Mục lục {- #muc-luc}

1. [Đạo Phật](#dao-phat)  
2. [Tam qui](#tam-qui)  
3. [Ngũ giới](#ngu-gioi)  
4. [Đi chùa lễ Phật](#di-chua-le-phat)  
5. [Sám hối](#sam-hoi)  
6. [Cúng dường Tam Bảo](#cung-duong-tam-bao)  
7. [Phật giáo độ sanh](#phat-giao-do-sanh)  
8. [Luân hồi](#luan-hoi)  
9. [Tam độc](#tam-doc)  
10. [Từ bi](#tu-bi)  
11. [Mê tín chánh tín](#me-tin-chanh-tin)  
12. [Tội phước](#toi-phuoc)  
13. [Nghiệp báo](#nghiep-bao)  
14. [Giác ngộ pháp gì ứng dụng tu Ngũ thừa Phật giáo](#giac-ngo-tu-ngu-thua)  
15. [Tinh thần giác ngộ của đạo Phật qua ngày lễ Vu-lan](#le-vu-lan)  
16. [Pháp tu căn bản của Phật tử *(Phật pháp hóa nhân gian)*](#phap-tu-can-ban-cua-phat-tu)  
17. [Tu trong mọi hoàn cảnh](#tu-trong-moi-hoan-canh)  
18. [Hoa sen trong bùn](#hoa-sen-trong-bun)  
19. [Bồ-tát sợ nhân chúng sanh sợ quả](#bo-tat-so-nhan-chung-sanh-so-qua)  
20. [Chấp là gốc đấu tranh là nguồn](#chap-la-goc-dau-tranh-la-nguon)  
21. [Cốt lõi đạo Phật](#cot-loi-dao-phat)  
22. [Chữ "Tức" trong Phật giáo Đại thừa](#chu-tuc-trong-dai-thua)  
23. [Thấy thân giả dối có phải quan niệm chán đời chăng?](#than-gia-doi-co-phai-chan-doi)  
24. [Số mạng nghiệp báo đồng hay khác?](#so-mang-nghiep-bao-dong-hay-khac)  
25. [Phật là gì?](#phat-la-gi)  
26. [Thế nào là Phật pháp?](#the-nao-la-phat-phap)  
27. [Học Phật bằng cách nào?](#hoc-phat-bang-cach-nao)  
28. [Làm sao tu theo Phật?](#lam-sao-tu-the-phat)  
29. [Kết luận](#ket-luan)  
