
# Đạo Phật {- #dao-phat}

## Mở đề #{- #mo-de-dao-phat}

Chúng sanh đang chìm đắm trong biển khổ sanh tử, dong thuyền ra cứu vớt họ
là sự ra đời của đạo Phật. Đêm tối vô minh che phủ tất cả chúng sanh, cầm đuốc sáng
soi đường cho họ là trách nhiệm của đạo Phật. Đạo Phật đến với chúng sanh trong một
niềm khát vọng vô biên, một sự trông chờ tột độ. Nhưng, con thuyền có giá trị cứu
mạng khi nào người sắp chết chìm biết bám lấy nó. Ngọn đuốc là một cứu tinh, khi
nào những kẻ lạc đường trong đêm tối khao khát muốn ra. Con thuyền và ngọn đuốc sẽ
vô bổ, nếu những kẻ sắp chết chìm và người lạc trong đêm tối chấp nhận cái gì mình
đang chịu. Cũng thế, đạo Phật sẽ vô ích với những chúng sanh chấp nhận sanh tử và an
phận trong vô minh. Vì thế, đạo Phật có mặt trên thế giới này đã hơn hai ngàn năm
trăm năm, còn biết bao nhiêu người nhìn nó với cặp mắt xa lạ. Song những kẻ đã nếm
được pháp vị, thấy công đức của đạo Phật đối với mình vô vàn không sao kể hết. Thật
đúng với câu *“Phật hóa hữu duyên nhân”*.

## Định nghĩa #{- #dinh-nghia-dao-phat}

Đứng về hành động, đạo Phật là con đường đưa người trở về cố hương giác
ngộ. Hoặc đạo Phật là phương pháp giúp người tiến tu đến giác ngộ. Đứng về thực thể,
đạo Phật là tánh giác sẵn có của tất cả chúng sanh.

Những kẻ phiêu lưu ở tha phương viễn xứ ước mơ khao khát trở về cố hương,
đạo Phật là tấm bản đồ vẽ rõ con đường trở về cố hương, do bàn tay của người đồng
cảnh ngộ đã trở về đến tận quê nhà, đức Thích-ca Mâu-ni. Nếu ý thức được cảnh khổ
của người xa quê, một lòng quyết chí trở về cố hương được người trao tay cho tấm bản
đồ, biết rõ con đường về quê thì còn sung sướng nào hơn. Không cam chìm sâu trong
đêm tối vô minh, người cương quyết tiến lên con đường giác ngộ, nắm vững những
phương tiện tiến tu, chắc chắn sớm chiều sẽ được mãn nguyện.

Đứng trên bờ biển thấy toàn biển đều là sóng, bởi cơn gió mạnh, người ta ngơ
ngác không biết làm sao tìm ra nước biển. Nếu đây là sóng thì nước biển ở đâu?
Những lượn sóng đuổi nhau lặn hụp hò hét ầm ì, mặt biển là những cái biến động ấy
sao? Người sáng suốt nghe thế, bảo họ rằng: *“Chính sóng ấy tức là nước”, “cái biến
động kia chỉ là hiện tượng của mặt biển tĩnh lặng”*. Hãy ngay nơi sóng, chúng ta nhận
ra nước, trên cái biến động biết được thể tịnh. Hiện tướng vô minh và tánh giác cũng
thế.

Tất cả những vọng tưởng điên đảo là hiện tướng vô minh, vọng tưởng lặng lẽ là
tánh giác thanh tịnh.

Tuy hai tên hai tướng khác nhau, song không thể rời vô minh tìm được tánh
giác, như sóng với nước. Tánh giác là cái thể chẳng sanh chẳng diệt của mỗi con người
chúng ta, hằng tàng ẩn trong con người vô thường sanh diệt này, như thể tĩnh lặng của
mặt biển sẵn có trên tướng biến động ầm ì. Bởi chúng sanh sẵn có tánh giác mà quên,
nên đức Thích-ca thương xót giáo hóa chỉ dạy cho thức tỉnh, đó là đạo Phật.

Chủ yếu của đạo Phật là giác ngộ, nên được biểu trưng bằng phóng quang, ngọc
minh châu, cây đuốc, ngọn đèn. Nói đến đạo Phật là nói đến giác ngộ; mọi hình thức
mê tín hiện có trong đạo Phật, do người sau ứng dụng sai lầm, chớ không phải thực
chất của đạo Phật.

## Lý thuyết {- #ly-thuyet-dao-phat}

Phần lý thuyết của đạo Phật rất phong phú, nói chung là Tam Tạng giáo điển,
gồm Tạng Kinh, Tạng Luật và Tạng Luận. Tam Tạng này hiện ấn hành có hai văn hệ:
Pali Tạng, Hán Tạng. Pali Tạng thuộc Nam truyền Phật giáo, Hán Tạng thuộc Bắc
truyền Phật giáo.  

Ở đây, chúng tôi nói về hệ thống Hán Tạng. Bộ Hán Tạng hiện do
Nhật Bản và Đài Loan ấn hành gồm trên năm ngàn quyển. Thật là một kho tàng văn
hóa dồi dào, chính những người tu sĩ Phật giáo cũng chưa chắc đã đọc hết. Trong ba
Tạng, quan trọng nhất là tạng Kinh, vì tạng Luận là giải thích lại tạng Kinh, còn tạng
Luật nói rõ về nghi thức luật lệ của người tu.  

Trong tạng Kinh tổng quát chia làm ba
phần : hệ thống A-hàm, hệ thống Bát-nhã, hệ thống Pháp Hoa, Niết-bàn, Hoa Nghiêm.
Hệ thống A-hàm giải thích về triết lý vô thường, khổ, không, vô ngã. Hệ thống Bát-
nhã giải thích tự tánh các pháp là Không, chỗ tánh Không ấy là tướng chân thật. Hệ
thống Pháp Hoa, Niết-bàn, Hoa Nghiêm giải thích chúng sanh sẵn có tánh giác gọi là
Trí tuệ Phật, Tri kiến Phật, Niết-bàn.

Tuy nhiên, vì truyền bá lâu xa khó tránh khỏi những tư tưởng tập tục sai lầm
chen lẫn trong chánh pháp. Chúng ta muốn phán định chánh tà, trong kinh có dạy dùng
Tứ pháp ấn, Tam pháp ấn, Đệ nhất pháp ấn để ấn định đúng sai. Tứ pháp ấn là vô
thường, khổ, không, vô ngã. Tất cả những kinh thuộc hệ thống A-hàm nói không ngoài
bốn lý này, nếu nói khác bốn lý này là tà thuyết. Tam pháp ấn là chư hạnh vô thường,
chư pháp vô ngã, Niết-bàn tịch tịnh. Đây là trùm cả Tiểu thừa lẫn Đại thừa đều nằm
gọn trong ấy. Đệ nhất pháp ấn là Nhất tâm chân như. Phần này chỉ riêng hệ thống Pháp
Hoa..., không can hệ đến hai hệ thống kia. Nắm được cái căn bản này, chúng ta tạm
biết cương yếu học Phật.

Phần lý thuyết của đạo Phật khác hẳn với thuyết lý của những triết gia, học giả
khác. Bởi vì họ dùng suy tư nghĩ tưởng biện thuyết, còn đây do đức Phật sau khi giác
ngộ thấy lẽ thật như thế, tùy hoàn cảnh trường hợp đem ra chỉ dạy cho người. Người
khéo ứng dụng lời Phật dạy vào cuộc sống sẽ được kết quả tốt đẹp, hoàn toàn không
họa hại. Cho nên, trong kinh nói *“lời Phật nói trước, giữa, sau đều thiện”*.

## Thực hành {-#thuc-hanh-dao-phat}

Ứng dụng phần lý thuyết trên vào cuộc sống hiện tại, sẽ được kết quả tùy theo
khả năng phương pháp mình thực hành. Sự thực hành có chia nhiều thứ bậc: Ngũ thừa,
Tam thừa, Nhất thừa. Chữ thừa ở đây ví dụ cỗ xe chở người đi. Từ vị trí con người chở
đến con người là Nhân thừa. Từ vị trí con người chở đến quả vị chư thiên gọi là Thiên
thừa. Từ vị trí con người chở đến quả vị Thanh văn gọi là Thanh văn thừa. Từ vị trí
con người chở đến quả vị Duyên giác gọi là Duyên giác thừa. Từ vị trí con người chở
đến quả vị Bồ-tát gọi là Bồ-tát thừa. Đó gọi là Ngũ thừa. Bỏ hai phần Nhân thừa và
Thiên thừa còn lại ba thừa sau gọi là Tam thừa. Từ vị trí con người phàm phu chở
thẳng đến quả vị Phật gọi là Phật thừa hay Nhất thừa.

Từ vị trí con người đến vị trí con người mai hậu là, ứng dụng tu hành Tam qui Ngũ giới và những nề nếp sống hiền lành chân thật của con người. Từ vị trí con người đến quả vị chư Thiên, ứng dụng pháp Thập Thiện vào
đời sống tu hành và Thiền định từ Sơ thiền đến Tứ thiền. Từ vị trí con người đến quả
vị Thanh văn, ứng dụng pháp Tứ đế để tu hành. Từ vị trí con người đến quả vị Duyên
giác ứng dụng pháp Thập nhị nhân duyên tu hành. Từ vị trí con người đến quả vị Bồ-
tát ứng dụng pháp Lục độ tu hành. Từ vị trí con người phàm phu thẳng đến quả vị Phật
ứng dụng phương pháp *“tức tâm là Phật”* tu hành. Ví như chúng ta muốn đi đến vị trí
nào, khi ra bến xe liền tìm xe đi về vị trí ấy leo lên, sẽ đưa chúng ta đi đến đích như
chỗ mong muốn. Đạo Phật cũng thế, tùy theo sở thích của người mà lập nhiều pháp
môn, ưng pháp môn nào ứng dụng tu hành đều kết quả đúng như sở nguyện. Đó là
phương tiện tùy cơ của đức Phật trên phương pháp giáo hóa chúng sanh. Nếu nói thẳng bản hoài của Ngài, chỉ muốn chúng sanh thành Phật là mục tiêu duy nhất.

Đạo Phật truyền sang Trung Quốc lại chia thành nhiều tông phái, mỗi tông phái
y cứ trên những bộ Kinh hay Luận làm chủ yếu cho sự tu hành. Nếu nói rộng có cả
thảy mười tông, nói hẹp theo sự truyền bá hiện tại có bốn tông. Hiện nay còn bốn tông
đang lưu hành là Thiên Thai tông, Thiền tông, Mật tông, Tịnh Độ tông. Phật giáo Việt
Nam chịu ảnh hưởng Phật giáo Trung Quốc, sự lưu hành các tông phái cũng tương tự Trung Quốc.

## Truyền bá {- #truyen-ba-dao-phat}

Ở đây nói truyền bá là đi thẳng vào phương pháp, không căn cứ trên lịch sử.
Những lời dạy của đức Phật được gọi là Kinh, bởi hai lý do: hợp lý và hợp cơ. Một
chân lý dù cao siêu đến đâu, nếu không ứng dụng được vào cuộc đời, chân lý ấy trở
thành không nền tảng, chỉ lơ lửng trên không trung. Chân lý không áp dụng được cho
người sẽ là vô ích. Truyền bá sự vô ích thật là làm một điều vô nghĩa. Lời Phật dạy
đúng chân lý gọi là hợp lý, song lời dạy ấy cũng phải hợp căn cơ trình độ của con
người đương thời thì họ ứng dụng mới được. Hợp lý hợp cơ là hai điều kiện không thể
thiếu trên phương diện truyền bá. Nếu chỉ dạy thích hợp sự ưa thích của người mà
không có chân lý sẽ đưa đến mê tín và tội lỗi. Một trọng trách của người truyền bá,
phải nhận định sáng suốt, để không bị lỗi thời hay sai chân lý. Chính đây là ý nghĩa
*“tùy duyên mà bất biến”* của tinh thần Đại thừa. Bất biến là hợp lý, tùy duyên là hợp
cơ. Thật là một hình ảnh linh động đi vào cuộc đời của chánh pháp. Người truyền bá
chánh pháp lúc nào cũng linh động mà không sai chân lý. Bởi cuộc đời là một dòng
biến thiên, mỗi thời đều mỗi khác, chúng ta không thể mang hình thức cổ lỗ đi vào thời
đại văn minh. Làm thế, chỉ chuốc sự chán chê của thiên hạ, không lợi gì cho mình, cho
chánh pháp cả. Cũng không thể mang hình thức rất hợp thời trang, mà bỏ mất chân lý.
Tùy duyên mà bất biến, quả là chân lý ngàn đời của người đi ra giáo hóa.

Lại nữa, con người sống lúc nào cũng dung hòa giữa tình cảm và lý trí. Tình
cảm là quả tim, lý trí là khối óc. Quả tim và khối óc phải nhịp nhàng hòa điệu thì con
người mới thanh thản an vui. Nghiêng một bên nào cũng làm mất thăng bằng, khiến
con người dễ mất bình thường. Đạo Phật muốn còn mãi trên nhân gian với con người,
sự truyền bá cũng phải làm thỏa mãn hai phần ấy. Để thỏa mãn phần khối óc, người
truyền bá chánh pháp phải thường giảng dạy Kinh Luận cho Phật tử nghe. Thấm nhuần
triết lý cao siêu của Phật giáo, người Phật tử mới khỏi nghi ngờ khi nghe một lý thuyết
khác. Sự tu hành vững chãi, cũng nhờ hiểu thấu giáo lý siêu thoát của Phật dạy. Giáo
lý là ngọn đuốc sáng đưa người ra khỏi rừng vô minh u tối. Có sẵn trong tay ngọn đuốc
sáng, người Phật tử chắc chắn sẽ thoát khỏi rừng mê. Để thỏa mãn con tim, những hình
thức nghi lễ tán tụng ở nhà chùa, giúp người Phật tử niềm tin được sung mãn. Những buổi lễ tại chùa đều có mang tính chất tín ngưỡng, phổ nhạc trong những lời tụng tán
đều là đi thẳng vào tình cảm của con người. Tuy chưa hiểu gì về Phật pháp, chỉ đến
chùa tụng một thời kinh, người ta cũng thấy lòng được nhẹ nhàng lâng lâng. Hoặc
những đêm khuya tĩnh mịch, những lời tụng tán thâm trầm hòa với tiếng khánh tiếng
mõ nhịp nhàng, khiến người nghe tâm hồn dường như bay bổng trên không trung. Tuy
nhiên như thế, hai phần lý trí và tình cảm đều phải quân bình nhau, lệch một bên đều là
khuyết điểm lớn. Nếu chỉ có lý trí mà thiếu tình cảm trở thành khô khan. Nếu chỉ có
tình cảm mà thiếu lý trí trở thành mê tín. Người truyền giáo phải khéo léo quân bình
hai điều này.

## Kết luận {- #ket-luan-dao-phat}

Đạo Phật có mặt ở thế giới này đã trên hai mươi lăm thế kỷ, sự truyền bá này
quả thật lâu dài. Sở dĩ được như thế, do Phật giáo là chân lý không lý thuyết nào bẻ
gãy nổi, người tu hành theo Phật giáo được kết quả lợi ích thiết thực không nghi ngờ,
phương pháp truyền bá của Phật giáo rất linh động. Chúng ta hữu duyên hữu phước
mới được gội nhuần chánh pháp, đừng cô phụ phước duyên của mình, mỗi chúng ta
phải nỗ lực tiến tu. Có thưởng thức được pháp vị rồi, chúng ta mới tùy duyên lợi ích kẻ
sau. Làm thế nào cho ngọn đèn chánh pháp nối tiếp mãi không tắt trên cõi thế gian
này. Đền ơn Phật Tổ không gì hơn cứu độ chúng sanh. Sự cứu độ thực tế nhất, phải
ngay cõi đời này, với những người có mặt hiện nay, khiến họ chuyển mọi khổ đau trở
thành an lạc. Phật giáo không phải cái gì xa vời, không phải sự ước mơ viển vông, mà
hiện tại thực tế. Nhận định như thế, mới có thể đem đạo Phật vào cuộc đời một cách
hữu hiệu.
