
# Đi chùa lễ Phật {- #di-chua-le-phat}

## Mở đề {- #mo-de-di-chua-le-phat}

Người xưa nói: *“làm việc có nghĩa do tâm tỉnh ngộ, làm việc vô nghĩa do tâm
mê mờ”*. Chúng ta thao thức ước mơ có thì giờ rảnh đi chùa để được nghe những lời
chỉ dạy đạo lý của Tăng, Ni. Quả là do tâm tỉnh ngộ làm động cơ thúc đẩy chúng ta.
Nếu chúng ta mong có lúc rảnh để đến hí trường, lại tửu điếm, chính do tâm mê mờ
làm động cơ thúc đẩy chúng ta. Chọn lấy một hành động có nghĩa là để làm theo, đích
thực là người trí. Chạy theo những hành động vô nghĩa hư hèn, quả là kẻ ngu. Đã có
mặt trên cõi đời, chúng ta phải chọn lấy một lối đi để đưa đời mình đến chỗ rạng ngời
tươi đẹp. Vô lý, chúng ta mãi đua đòi theo sự ăn mặc vui đùa, đến một ngày kia thân
này sắp hoại, tự ta nghĩ sao về thân phận mình? Vì thế, sự đi chùa lễ Phật là một việc
làm do động cơ tỉnh ngộ thúc đẩy, với một tinh thần cố gắng vươn lên, gầy dựng cho
mình một ngày mai sáng đẹp.

## Đi chùa {- #di-chua}

Mục đích đi chùa không phải là để cúng lạy, mà vì học hỏi chánh pháp, tập tu
đức hạnh. Người Phật tử mới đến với đạo chưa thấm nhuần Phật pháp, nếu không được
sự chỉ dạy của Tăng Ni thì làm sao hiểu đạo tu hành. Muốn hiểu đạo lý, Phật tử tới lui
Tự viện để thưa hỏi học tập là sự đương nhiên không thể thiếu. Vì sự sống bận rộn
ngoài xã hội, Phật tử đâu đủ thì giờ nghiên cứu giáo lý, chỉ gặp Tăng, Ni trong nửa giờ,
một giờ, Phật tử có thể học được nhiều điều trước kia chưa biết. Vì thế, đến chùa để
gặp Tăng, Ni là điều thiết yếu không thể thiếu, đối với mỗi Phật tử tại gia. Đi chùa có
hai trường hợp, đi chùa ngày thường và đi chùa ngày lễ vía.

**Đi chùa ngày thường**  

Bất cứ ngày nào thấy rảnh việc nhà, người Phật tử có thể
đi chùa. Khi đi chùa, Phật tử phải nhắm thẳng mục đích thưa hỏi đạo lý. Vì hỏi đạo lý,
Phật tử phải ghi lại những điều gì mình chưa hiểu để đem ra hỏi. Mỗi lần đến chùa,
Phật tử phải có ít nhất đôi ba vấn đề thưa hỏi Tăng, Ni. Những vấn đề ấy, hoặc do thấy
nếp sống sanh hoạt nhà chùa chưa hiểu đem ra hỏi, hoặc đọc trong kinh sách chỗ nào
không biết đem ra hỏi. Biết thưa hỏi như vậy, người Phật tử học đạo rất chóng tiến. Đi
chùa hỏi đạo là đúng tinh thần học vấn của người Phật tử.

Nhưng cũng có những khi không vì hỏi đạo mà vẫn đi chùa. Đây là trường hợp
vì đua chen trong cuộc sống, người Phật tử thần kinh bị căng thẳng, vội vàng bỏ việc
đến chùa. Đến đây để ngồi yên trên tảng đá dưới bóng mát tàn cây, nghe tiếng gió thì
thào trên ngọn cây, giọng chim líu lo trong cành râm, khung cảnh tịch mịch của nhà
chùa, khiến tâm hồn lắng xuống thần kinh dịu lại. Không cần gặp ai, chẳng màng thưa
hỏi, chỉ cần mắt ngắm mấy cội tùng xanh, mũi ngửi mùi hương nhẹ của hoa lan, hoa
nguyệt quới, ngồi đặt lưng tựa bên vách chùa, chúng ta cảm nghe lòng nhẹ nhàng
khoan khoái, những giờ phút này gánh nợ đời oằn oại đôi vai bỗng dưng như quẳng
mất. Chính cảnh cô liêu tịch mịch của nhà chùa đã giải tỏa xoa dịu phần nào nỗi bực
dọc não phiền của Phật tử.

**Đến chùa ngày lễ vía**  

Cùng Phật tử với nhau như con một cha, những ngày lễ
vía là ngày huynh đệ sum họp. Ngày thường mỗi Phật tử có hoàn cảnh riêng gia đình
riêng, ít khi gặp được nhau để thăm hỏi sự tu hành, nhắc nhở nhau về đức hạnh. Nhân
ngày lễ vía ở chùa, toàn thể Phật tử tụ hội về cùng thăm hỏi nhau trong tình đạo bạn,
cùng giãi bày nhau về kinh nghiệm tu hành, thật là một cơ hội quí báu. Chúng ta đâu
không nghe ông cha chúng ta đã nói *“ăn cơm có canh, tu hành có bạn”*. Đoàn tụ dưới
mái chùa, huynh đệ ngồi gần nhau đàm đạo mật thiết thân tình, đây là một niềm vui để
dắt dìu nhau trên con đường đạo đức. Mến thương nhau, đoàn kết nhau, khích lệ nhau,
cùng nỗ lực leo lên cho đến tận đỉnh ngọn giác ngộ.

Càng cao cả hơn, khi chúng ta nghe Tăng, Ni kể lại hành trang nhuộm mùi từ bi
đượm màu giác ngộ của chư Phật, Bồ-tát, hoặc nghe giải thích giáo lý cao siêu thoát
tục của Phật dạy, làm sáng tỏ thêm đường lối tu hành. Thật là những cơ hội hiếm có để
Phật tử thấm nhuần chánh pháp. Vắng mặt trong những ngày lễ vía, là một thiệt thòi
đáng kể của người Phật tử. Có nghe giáo lý, có học công hạnh của Phật, Bồ-tát, Phật tử
mới biết phương hướng tu hành, mới thấy những gương sáng ngời để noi theo. Dù đã
qui y mấy mươi năm, không chịu học hỏi giáo lý, không siêng nghe giảng dạy, Phật tử
này vẫn mờ mịt không hiểu gì về đạo Phật. Là Phật tử phải tỏ ra xứng đáng với danh
nghĩa của mình, nghĩa là học và hành đúng với đường lối Phật dạy. Vì thế, đi chùa
nghe giảng là điều tối cần thiết của người Phật tử.

## Lễ Phật {- #le-phat}

Lạy Phật không vì van xin tha tội, không vì cầu mong ban ân, chỉ vì quí kính
một đấng lòng từ bi tràn trề, trí giác ngộ viên mãn. Vì quí kính công đức trí tuệ của
Phật nên chúng ta lạy Ngài. Lạy Phật để thấy mình còn thấp thỏi ti tiện, bỏ hết những
thói ngạo mạn cống cao. Quí kính gương cao cả của Phật để mình noi theo. Phước đức
lạy Phật là tại chỗ đó.

Lễ Phật vì dẹp ngã mạn - Bản chất con người chúng ta lúc nào cũng tự cao tự
đắc, vênh váo nghênh ngang. Đó là tánh xấu khiến mọi người chán ghét, tiêu mòn
công đức. Phật tử biết được cái dở này, kính lạy Phật, Bồ-tát, các bậc tôn túc, để diệt
trừ tâm ngã mạn của mình. Kính lạy các ngài là tự mình thấy không bì kịp các ngài,
biết mình thấp thì tánh ngạo mạn từ từ biến mất. Khi lạy các ngài không mong một ân
sủng nào, chỉ vì một lòng kính trọng đức hạnh của các ngài, tự thấy mình hèn hạ thấp
thỏi, thế là mọi công đức từ đó phát sanh. Bởi đứa ăn trộm thì phục kẻ ăn trộm giỏi,
chàng võ sĩ thì nể tay vô địch, kính trọng Phật, Bồ-tát, các bậc tôn túc tự nhiên chúng
ta có dự phần trong ấy rồi. Quả như câu nói *“kính thầy mới được làm thầy”*. Chúng ta
muốn dẹp bỏ những tánh xấu, tập tành đức hạnh, kính lễ những bậc đức hạnh là điều
cần thiết vậy.

Lễ Phật vì noi gương - Kính lạy Phật, chính vì chúng ta muốn học đòi noi theo
gương của Ngài. Tại sao chúng ta phải học đòi theo gương đức Phật? Bởi vì, Phật đã
đầy đủ mọi công đức, trí tuệ từ bi viên mãn, nên chúng ta phải học theo. Đây chúng tôi
đơn cử một công hạnh nhỏ xíu của Ngài, thử xem chúng ta có theo kịp không?

Một hôm, đức Phật một mình mang bình bát vào thôn xóm khất thực, bỗng có
một người ngoại đạo biết Ngài và biết rõ Phật đi đến đâu ắt đệ tử của chúng đều bỏ đạo
qui kính Phật. Nổi tức, ông đi theo sau lưng Phật mạ lỵ đủ điều, Phật vẫn chậm rãi tiến
bước đều đều không một lời đối đáp. Đến đầu đường, ông ta chạy đón trước mặt Phật,
chặn lại hỏi: Cù-đàm thua ta chưa? Phật ung dung trải tọa cụ xuống đất, ngồi kiết già
đọc bài kệ:

<div class="align-center">
> Kẻ hơn thì thêm oán  
> Người thua ngủ chẳng yên  
> Hơn thua hai đều xả  
> Ấy được an ổn ngủ  
>  
> <div style="text-align: right">*(Kinh Trung A-hàm)*  </div>
</div>
  
Ngoại đạo hối lỗi ăn năn lễ tạ.

Thử hỏi hành động này của đức Phật, chúng ta có ai dám tự hào cho mình làm
được. Nếu đem danh vọng giá trị so sánh, đức Phật là một vị giáo chủ trong tôn giáo,
một vị Thái tử ở thế gian, chúng ta hiện nay là một tín đồ trong tôn giáo, một kẻ tay
trắng ở thế gian, đức Phật bị mạ lỵ mà không tức giận, chúng ta bị mạ lỵ có tức giận
chăng? Nếu chúng ta không tức giận cũng chưa dám bì với đức Phật, vì giá trị danh
vọng của chúng ta có ra quái gì. Huống là, bị mạ lỵ chúng ta liền nổi giận ầm ầm. Nhìn
lại đức Phật thử xem chúng ta cách Ngài bao xa? Thế thì lạy Ngài bao nhiêu mới xứng
đáng trong việc noi gương theo Ngài? Đến như tâm từ bi, trí giác ngộ của Phật, sánh
với chúng ta thật là trời cao vực thẳm. Đời đời kính lễ Ngài, cũng là cái hãnh diện của
chúng ta, biết kính người đáng kính. Thế mà, có một ít người thấy chúng ta lạy Phật,
họ tỏ vẻ ngạo nghễ. Hãy nghe câu chuyện đối đáp này:

Một em gái đi chùa lễ Phật, lễ xong em vừa ra đến sân chùa, gặp một quân nhân
đứng ngắm cảnh. Thấy em, quân nhân liền hỏi: Em đi đâu thế? Bé gái đáp: Em đi chùa
lễ Phật. Quân nhân hỏi: Tượng Phật bằng gỗ bằng xi măng, em lễ cái gì? Bé gái hỏi
lại: Ở doanh trại anh mỗi sáng có chào cờ không? Quân nhân đáp: Sáng nào cũng chào
cờ. Bé gái hỏi: Cờ bằng vải bằng màu, tại sao phải nghiêm trang chào? Quân nhân đáp:
Chào tinh thần Tổ quốc được tượng trưng qua lá cờ, chớ không phải chào vải màu. Bé
gái nói: Cũng thế, em lạy tinh thần từ bi giác ngộ của Phật được tượng trưng qua hình
tượng chớ không phải lạy gỗ lạy xi măng. Quân nhân đành thôi.

## Kết luận {- #ket-luan-di-chua-le-phat}

Chọn một hành động có ý nghĩa là con người tỉnh sáng. Khi đã nhận định kỹ
việc làm của mình, dù có bị chê khen, chúng ta vẫn an ổn thực hành. Chỉ có những kẻ
xu thời, thấy ai khen cái gì chạy theo cái nấy, mới bàng hoàng khi bị ai phê bình hành
động của mình. Đi chùa lạy Phật đã mang sẵn những ý nghĩa của nó, dù có ai chê là
mê tín..., ta vẫn an nhiên. Đạo đức có hay không, do lòng ta biết kính trọng người đạo
đức hay không. Do lòng kính trọng mới thúc đẩy chúng ta học đòi và bắt chước theo
người đức hạnh. Lạy Phật là động cơ đẩy mạnh chúng ta tiến mãi trên đường giác ngộ.
