
# Sám hối {- #sam-hoi}

## Mở đề {- #mo-de-sam-hoi}

Mắc bệnh ung nhọt làm mủ trong thân, người bệnh cần phải gan dạ mời giải
phẫu sư mổ ra và cạo rửa mủ máu cho sạch, có thế thì bệnh chóng lành. Nếu bệnh nhân
hèn nhát không dám cho mổ, để ấp ủ lâu ngày, ung nhọt có thể làm nguy hiểm đến
tánh mạng. Cũng như thế, người tu lỡ phạm những điều tội lỗi, gan dạ đến những bậc
đức hạnh thành tâm phát lồ sám hối thì tội lỗi chóng sạch. Ngược lại, kẻ ấy hèn nhát
cứ một bề che giấu, tội lỗi càng ngày càng trầm trọng, đến mai kia có thể sa đọa không
thể cứu. Chúng ta là phàm phu, là kẻ đang tập tu, không sao tránh khỏi những điều sai
lầm tội lỗi, chỉ quí ở chỗ có lỗi biết thành tâm sám hối, không dám tái phạm, khiến tội
lỗi sạch dần cho đến ngày nào đó hoàn toàn thanh tịnh. Hèn nhát không chịu sám hối
là kẻ chấp nhận sự lui sụt của mình, tự hủy bỏ đời sống tu hành của chính mình. Sám
hối là phương pháp sách tiến mạnh mẽ nhất, đối với người chân thật tu hành, bỏ sám
hối khó ai từ phàm phu tiến lên thánh được.

## Định nghĩa {- #dinh-nghia-sam-hoi}

Sám hối là ăn năn hối cải. Những tội lỗi đã làm, chúng ta hổ thẹn, ăn năn
không dám tái phạm; những tội lỗi đang làm và sẽ làm, chúng ta hứa sửa đổi không
làm. Không phạm tội cũ, không tạo lỗi mới, là chủ yếu của pháp sám hối. Sám hối
cũng nói là phát lồ sám hối. Phát lồ là vạch trần những tội lỗi mình đã làm phơi bày
trước bậc đức hạnh để thành tâm sám hối. Làm thế, do tâm hổ thẹn, cầu tiến mới dám
gan dạ đến trước bậc đức hạnh phơi bày hết tội lỗi của mình cầu xin sám hối. Giá trị
căn bản nhất là, hổ thẹn và cầu tiến, hai tâm này là động cơ chính yếu trong việc sám
hối. Vì hổ thẹn và cầu tiến chúng ta mới sám hối, sau khi sám hối dứt khoát không tái
phạm gây tạo nữa. Trọng tâm của sám hối là ở chỗ này.

## Hình thức sám hối {- #hinh-thuc-sam-hoi}

Sám hối tương tự nghĩa xin lỗi của người thế gian. Người thế gian lỡ phạm lầm
lỗi với ai khiến họ phiền muộn, biết mình có lỗi gan dạ đến xin lỗi, lỗi lầm ấy liền
được tha thứ, nếu người rộng lượng, hoặc giảm bớt buồn phiền, nếu người cố chấp.
Biết nhận lỗi mình và gan dạ đi xin lỗi, quả là người tiến bộ đáng khen. Người tu cũng
thế, nếu vì ba nghiệp không khéo gìn giữ, có ngôn ngữ hành động làm cho người
chung quanh mình phiền não, nhận rõ lỗi mình, gan dạ đến ngay đương sự thành tâm
sám hối. Nếu người thật tu hành, không ai chẳng tha thứ cho người đã biết lỗi sám hối.
Thế là tội lỗi liền đó dứt sạch.

Nếu người tu vì si mê che đậy lỡ phạm những giới của mình đã thọ, cần phải hổ
thẹn gan dạ đến trước những vị đức hạnh phát lồ sám hối. Do lòng thành của mình và
nhờ sự chứng minh của bậc trưởng thượng, chúng ta nỗ lực cố gắng không tái phạm
những lỗi lầm cũ và không tạo tội lỗi mới. Các bậc đức hạnh không thể tha tội lỗi cho
chúng ta, song nhờ các ngài làm đối tượng cao quí khiến những lời hứa nguyện của
chúng ta có thêm sức mạnh, cho đến cả đời không quên. Biết ăn năn lỗi cũ, không tạo
tội mới, đây là lý do hết tội của người sám hối.

Trên đường tu hành, chúng ta thấy chướng nhiều thuận ít, hoặc trong khi phát
nguyện tu hành gặp toàn những trở ngại, hoặc thân thể bệnh hoạn ngăn trở sự tu, hoặc
túc nghiệp ác duyên khiến mờ mịt ngu tối... gặp hoàn cảnh này, chúng ta nên đến trước
hình tượng Phật, Bồ-tát thành tâm sám hối. Bởi những nghiệp duyên đời trước, hiện
nay chúng ta không nhớ không biết, chỉ thấy những hiện tượng bất tường, nhận ra
mình còn nhiều ác chướng, đến trước Phật, Bồ-tát thành tâm sám hối. Với lòng thiết
tha tâm chân thành, chúng ta đảnh lễ Phật, Bồ-tát, quì gối chí thành phát lên những lời
chí thiết sám hối và hứa nguyện, cầu Phật, Bồ-tát chứng minh. Bởi lòng thành khẩn
thiết tha này, nên sám hối tội lỗi chóng sạch. Lời văn sám hối những nghiệp chướng cũ
thu gọn trong bốn câu này:  
  
<div class="align-center">  
> Xưa con đã tạo bao ác nghiệp  
> Đều bởi muôn thuở tham sân si  
>  Từ thân miệng ý mà phát sanh  
> Tất cả, nay con xin sám hối  
</div>

## Tinh thần sám hối {- #tinh-than-sam-hoi}

Sám hối đúng ý nghĩa của nó phải có đủ tâm hổ thẹn và cầu tiến. Vì hổ thẹn,
chúng ta không thể chứa chấp tội lỗi mãi, cần thành tâm sám hối rồi mới an ổn. Với
tinh thần cầu tiến chúng ta phải dứt khoát những lỗi lầm đã qua bằng cách sám hối, để
vui vẻ tiến lên con đường đạo đức. Có thế, sự tu hành tinh tấn không bị chướng ngại.
Bởi hổ thẹn và mong mỏi vươn lên, sau khi sám hối, chúng ta tuyệt đối không để tái
phạm những lỗi cũ. Chính khi sám hối không phải bị ai bắt buộc, chỉ do tâm hổ thẹn
thúc đẩy, chí thành tha thiết sám hối. Lòng chí thành tha thiết sẽ giúp chúng ta sạch hết
mọi tội lỗi.

Tuy nhiên, đã thành tâm sám hối lý đáng không được tái phạm lỗi ấy nữa, song
vì hoàn cảnh bất khả kháng, hoặc vì tâm yếu mềm chống chọi không lại, rồi dẫm lại
vết xưa. Thế đã dở lắm rồi, nhưng chúng ta cũng thành tâm sám hối đừng nản. Còn
biết sám hối, chúng ta còn thấy đó là tội lỗi, nếu buông xuôi luôn, tội lỗi càng ngập
đầu. Vì thế, có khi một lỗi phạm đến đôi ba lần, lần nào chúng ta cũng vẫn mạnh dạn
sám hối, đừng vì tự ái không dám sám hối những lỗi đã tái phạm, tự ái này là gốc
khiến ta buông lung tột độ.

Tinh thần sám hối buộc chúng ta phải thành khẩn thiết tha, hổ thẹn cầu tiến,
vạch trần những lỗi lầm đã làm, cầu xin sám hối. Vì vậy, khi sám hối đương sự phải
cần cầu tha thiết, lời lẽ trình bày chân thành rành rõ thiết yếu, phát nguyện chừa cải
một cách mạnh dạn, mới đúng ý nghĩa sám hối. Nhưng gần đây các chùa cứ theo lệ
xưa, chiều mười bốn và chiều ba mươi tổ chức lạy sám hối Hồng Danh, sau khi lạy quì
xuống tụng nguyên bản văn dịch âm chữ Hán, Phật tử đọc thuộc lòng mà không hiểu
biết gì hết. Như thế, cứ lạy tụng xong gọi là xong thời sám hối. Sám hối như thế mất
hết tinh thần cao cả, ý nghĩa thâm sâu của nó. Hằng ngày Phật tử làm những tội lỗi gì
cũng được, miễn đến ngày mười bốn và ba mươi đi sám hối một thời là sạch. Quả là
một việc làm lấy lệ không đúng tinh thần đạo Phật.

## Lợi ích sám hối {- #loi-ich-sam-hoi}

Nếu người phạm tội một lòng thành khẩn thiết tha sám hối, sau khi sám hối
tuyệt đối không tái phạm, người này chưa phải là thánh, nhưng đã là bậc hiền. Bởi vì
tất cả thế gian này có ai không có tội lỗi, chỉ khác nhau nhiều hay ít, biết chừa cải hay
không biết chừa cải ấy thôi. Đã có tội lỗi mà biết ăn năn hối cải, tội lỗi ấy sẽ giảm
xuống dần dần, cho đến hết, người như thế không phải bậc hiền là gì? Cho nên trong
cuộc sống này, chúng ta đừng đòi hỏi mình hay mọi người không có tội lỗi, chỉ cần khi
lỡ phạm tội lỗi mình cũng như mọi người phải hổ thẹn ăn năn thành tâm sám hối,
nguyện chừa cải hẳn sau này. Được thế, chúng ta đều là con người tiến bộ, là kẻ sẽ
vươn lên bậc Hiền Thánh ở mai kia. Sám hối muốn hết tội phải nhắm thẳng động cơ
chánh yếu của nó. Như bài kệ này:  
  
<div class="align-center">  
> Tánh tội vốn không do tâm tạo  
> Tâm nếu diệt rồi tội sạch trong  
> Tội trong tâm diệt cả hai không  
> Thế ấy mới là chân sám hối  
</div>
  
Hành động ăn cướp ăn trộm, tự nó không thể thành nghiệp phải do lòng tham
thúc đẩy. Lòng tham là động cơ chánh yếu của hành động trộm cướp. Thế nên nói
*“tánh tội vốn không do tâm tạo”*. Lòng tham dứt rồi thì hành động trộm cướp làm gì
còn. Quả là cả tâm cả tội đều sạch, sự sám hối này mới là chân chánh sám hối. Chân
chánh sám hối thì tội lỗi nào mà chẳng sạch.

Hoặc khi sám hối thì thành khẩn tha thiết, song sau đó lại mau quên thỉnh
thoảng lại tái phạm. Tái phạm lại sám hối, năm lần mười lượt như vậy, tuy tội không
sạch được, mà do bền chí sám hối nó cũng mòn dần. Đây có thể là trường hợp của
hạng trung bình chúng ta. Chúng ta chưa được một lần sám hối là dứt khoát không
phạm, mà lâu lâu lại tái phạm tội cũ. Đừng thối chí đừng nản lòng, chúng ta lại dập
đầu sám hối nữa. Biết như thế là dở, song dở phải chịu dở chớ sao; biết dở chịu dở còn
hơn người không biết không chịu.

Có sám hối là có suy giảm tiêu mòn, chúng ta hằng ngày mang tâm hổ thẹn,
lòng thiết tha sám hối mãi. Nhắc đi lập lại đôi ba mươi lần, nó cũng có sức mạnh, đây
là hành động thấp mình khiến tâm ngạo mạn tiêu mất, lâu ngày công đức cũng được
đầy đủ. Dám sám hối cũng là một việc làm can đảm, nó là sức mạnh đẩy chúng ta tiến
lên. Tu mà không gan dạ sám hối, quả là người hèn nhát che dấu không thể nào tiến
lên được.

## Kết luận {- #ket-luan-sam-hoi}

Người đời đa số có tội lỗi tìm mọi cách khéo léo che giấu đắp điếm cho người
khác đừng thấy lỗi mình, chúng ta có lỗi can đảm nhận chịu và can đảm phơi bày cho
người khác biết để sám hối. Thế đã vượt hơn người đời một bậc đáng kể rồi. Huống là,
biết lỗi rồi ăn năn hổ thẹn quyết tâm chừa cải để khỏi phạm lại lần thứ hai, người này
hẳn đã đi theo bước đường của Hiền Thánh. Căn bản của sự tu hành là sửa đổi những
điều dở, nếu chúng ta không còn dở thì ai cần tu. Sửa đổi những điều dở, sám hối là
thượng sách. Người biết sám hối, là biết tu, ngược lại có lỗi mà không biết sám hối, dù
có mang hình thức nhà tu kẻ ấy cũng chưa biết tu. Sám hối với một tâm chí thành, với
một lòng tha thiết, xấu hổ những lỗi đã làm, quả quyết không tái phạm, người này
không còn tội lỗi nào mà chẳng sạch. Dù có tạo tội bao nhiêu, họ vẫn là người tốt ở
mai sau.
