
# Phật giáo độ sanh {- #phat-giao-do-sanh}

## Mở đề {- #mo-de-phat-giao-do-sanh}

Tất cả việc làm của Phật giáo đều tập chú vào lợi ích cho chúng sanh. Chúng
sanh là đối tượng duy nhất của Phật giáo. Thế nên sự truyền bá của Phật giáo vì lợi ích
chúng sanh. Nếu không vì lợi ích chúng sanh, sự truyền bá ấy là vô nghĩa lý. Chúng
sanh ở đây là những người hiện có mặt, nghe hiểu được những lời giáo hoá. Chúng ta
đừng hiểu chúng sanh là những âm hồn, những kẻ chết. Nếu Phật giáo sống với kẻ
chết, thực chất Phật giáo đã chết mất rồi. Thế mà gần đây có một số Tăng, Ni đưa Phật
giáo đi vào cõi chết. Tăng, Ni xuất hiện đông đủ chỉ ở những đám ma chay. Phật sự
quan trọng của Tăng, Ni là đưa ma cúng đám. Đó là nét bi thảm đang xuất hiện trên
hình ảnh Phật giáo Việt Nam. Cần nói một câu chính xác hơn: *“Phật giáo độ sanh,
không phải độ tử.”* Nếu ai cố tình đem Phật giáo vào cõi tử, chính là kẻ làm hoại diệt
Phật giáo.

## Giảng dạy {- #giang-day-phat-giao-do-sanh}

Vì tính cách độ sanh nên những người truyền giáo có bổn phận hằng giảng dạy
cho tín đồ thông hiểu Phật giáo. Mỗi ngôi chùa là một nơi giảng dạy kinh điển, mỗi
buổi lễ là mỗi lần giảng dạy giáo lý. Có thế, người Phật tử mới biết rõ đường lối tu
hành, mới thâm nhập được giáo lý cao siêu. Phật giáo đã tự hào có một kho tàng kinh
điển dồi dào, mà người Phật tử kể cả Tăng, Ni, đa số dốt nát về giáo lý. Lỗi ấy tại ai?
Bởi sự truyền bá còn sơ sót yếu kém, chính Tăng, Ni phải chịu trách nhiệm. Sở dĩ có
sơ sót này, vì Tăng, Ni bận quá nhiều thì giờ lo cho người chết. Một người chết, Tăng,
Ni mất mấy ngày đêm có mặt tại tang gia, sau khi chôn cất xong, phải mất bao nhiêu
ngày trong những lễ trai tuần. Nếu chùa có đôi ba ngàn Phật tử, thử hỏi Tăng, Ni còn
thì giờ đâu lo tu học và truyền bá chánh pháp. Quả là chúng ta làm lệch lạc trọng trách
của mình. Việc đáng làm chúng ta lại không làm, việc không đáng làm chúng ta lại
dồn hết thì giờ vào đó. Ví như người chết đã nằm cứng đờ trong quan tài, mà ba bốn vị
Tăng, Ni có khi nhiều hơn, thường trực tụng kinh cho họ nghe, thử hỏi đã nghe được
những gì? Đúng theo tinh thần Phật giáo, người chết sau khi tắt thở tùy nghiệp thiện ác
theo đó đi thọ sanh, có ai còn lẩn quẩn bên quan tài để chúng ta tụng kinh cho họ nghe.
Việc làm này quả thật không đáng, mà chúng ta tốn nhiều thì giờ. Vì thế, việc tối quan
trọng là giảng kinh dạy đạo, chúng ta phải bê tha đi. Nếu thật người chân chánh xuất
gia, chúng ta phải điều chỉnh lại, đừng để đi mãi trên con đường sai lầm như thế.
Chúng ta hằng nhớ trọng trách của mình là phổ biến chánh pháp lợi ích quần sanh,
không phải vì tụng cúng để được lòng Phật tử.

## Dịch kinh viết sách {- #dich-kinh-viet-sach}

Kinh điển Phật giáo hiện giờ chưa được phiên dịch hết ra chữ Việt. Thế là trọng
trách Tăng, Ni còn nặng nề biết mấy. Những bản kinh chữ Phạn, sang Trung Quốc
người ta đã phiên dịch thành chữ Hán. Tạng kinh chữ Hán có mặt ở Việt Nam khá lâu
rồi, Tăng, Ni Việt Nam chưa phiên dịch được một phần mười (1/10). Cho đến những
nghi lễ tụng niệm hằng ngày cũng vẫn đọc theo phiên âm chữ Hán, quả là một thiếu
sót to tát của Phật giáo Việt Nam. Tại sao Tăng, Ni không dồn hết thì giờ của mình
trong việc học tập để phiên dịch kinh điển? Bởi vì Phật tử đòi hỏi việc đưa ma cúng
đám, Tăng, Ni mới thiếu thì giờ học tập. Tăng, Ni là người hướng dẫn Phật tử, tại sao
chúng ta mãi để những đòi hỏi không đáng, làm mất thì giờ vàng ngọc của người tu?
Chính tại Tăng, Ni không gan chẳng dám nói thẳng, sợ mất cảm tình, khiến tệ đoan
càng ngày càng thêm. Đâu những thế, có một thiểu số Tăng, Ni lại bày biện đủ cách
rối ren, khiến đã mất thì giờ lại thêm mất thì giờ. Những kẻ này bề ngoài xem dường
như thương Phật pháp, kỳ thật họ lợi dụng Phật pháp làm kế sanh nhai. Người Phật tử
dốt nát không biết, thấy bày biện chừng nào lại càng thích chừng ấy, quả thật kẻ mù
dắt đám mù. Kinh điển là những phương thuốc độ đời, Tăng, Ni là người chịu trách
nhiệm truyền bá, mà không dồn hết thì giờ học tập phiên dịch, thật là trái với bổn phận
biết bao. Tổ tiên chúng ta khi xưa học chữ Hán, nên Tạng kinh chữ Hán vốn không có
gì khó khăn. Hiện nay chúng ta học chữ Việt, Tạng kinh chữ Hán là một cổ ngữ không
làm sao đọc được. Tăng, Ni hiện nay không cố gắng dịch ra chữ Việt, vô tình chúng ta
để giáo lý chết khô và chôn sâu trong các tủ kinh nhà chùa.

## Thọ cúng dường {- #tho-cung-duong}

Khi xưa Phật còn tại thế, nếu Phật tử muốn thỉnh Phật và Tăng chúng cúng
dường, Phật đều thọ nhận. Đúng giờ thọ trai, Phật và chúng Tăng mới đến, nghỉ ngơi
giây lát rồi thọ trai. Thọ trai xong, trong gia quyến tụ họp ngồi chung quanh đức Phật,
Ngài vì gia quyến thuyết pháp, thuyết pháp xong, Phật vì gia quyến chúc lành, đứng
dậy ra về. Thế thì người cúng dường vì Phật và Tăng chúng mà cúng, người thọ cúng
dường cũng vì gia chủ hiện tại mà thọ. Phật thuyết pháp chúc lành cũng vì người sống
hiện có mặt, đúng là ý nghĩa độ sanh. Ngày nay chúng ta lại khác, gặp ngày tuần, ngày
giỗ của cha mẹ, Phật tử thỉnh Tăng, Ni cúng dường. Tăng, Ni thọ trai xong, vì người
chết tụng một biến kinh cầu nguyện, cầu nguyện xong ra về. Như vậy, người cúng
dường vì kẻ chết mà cúng, người thọ cúng dường cũng vì kẻ chết mà cầu nguyện. Cả
hai điều vì người chết , quả là Phật giáo độ tử, đâu còn là nghĩa độ sanh. Tăng, Ni đến
nhà không có lợi ích gì cho người hiện tại hết, chỉ cầu lợi ích cho kẻ quá cố, song
người quá cố chắc gì có mặt ở đây, nếu người quá cố đã thác sanh nơi nào rồi, việc làm
này có phải viển vông không thiết thực chăng? Tại sao chúng ta không giữ theo nếp
xưa, thực hành đúng tinh thần cúng dường Phật và Tăng chúng thuở trước, để ý nghĩa
độ sanh được vẹn toàn, sự lợi ích cụ thể thiết thực tròn đủ trăm phần? Trước đã quá
hay, tại sao nay chúng ta lại bỏ? Nay thật dở, tại sao chúng ta lại theo? Ở đây, chúng ta
cần chỉnh lại, đừng để đưa Phật giáo vào cõi chết, gây thêm mê tín cho Phật tử, trái với
đạo lý giác ngộ chân thật của đức Thích-ca.

Hơn nữa, khi xưa đức Phật thuyết pháp cho dân chúng nghe, nhân nghe pháp
dân chúng liền cúng dường cơm, Phật không thọ nhận. Phật cho nhận như thế là nhờ
giảng dạy nên có cơm ăn, không phải do lòng chân thành phát tâm cúng dường của
Phật tử. Ngày nay tại sao chúng ta đi tụng kinh cho Phật tử để được cúng cơm cúng
tiền, hoan hỉ thọ nhận? Làm thế có phải đi tụng kinh thuê chăng? Có trái với tông chỉ
của Phật ngày xưa không? Ngày xưa, đức Phật cao cả thanh bạch đến thế, ngày nay
chúng ta ti tiện thấp hèn lắm vậy. Đây cũng là một điều chúng ta phải lưu tâm chỉnh
đốn lại, đừng để những tệ tục cứ dắt mãi chúng ta trong đường mê tối. Thậm chí hiện
nay có một ít Tăng, Ni đến tận nhà Phật tử dùng đủ lời lẽ để quyên tởi, thật đau lòng
thay! Đạo lý nào dạy những điều ấy?


## Dĩ huyễn độ chân {- #di-huyen-do-chan}

Hoặc có người nói những việc cúng đám ma chay cho các Phật tử chẳng qua *“dĩ
huyễn độ chân”*, nhân cơ hội tang gia bối rối, chúng ta đến với họ để có cảm tình dẫn
dắt họ vào đạo. Nhưng xin đặt câu hỏi, nếu vì cảm tình đến với đạo, mai mốt mất cảm
tình thì sao? Chủ trương đạo Phật là tự giác tự nguyện, nếu không vì lẽ tỉnh giác đến
với đạo, người ấy vẫn chưa xứng đáng là Phật tử. Huống chi, vì chiều theo cảm tình
của họ, Tăng, Ni mất hết giá trị cao thượng, thanh nhã của mình, được đôi ba người
Phật tử, mà người truyền giáo mất hết giá trị, thử hỏi việc ấy có đáng làm không?
Chúng tôi đồng ý, nếu cần Tăng, Ni đến đám ma đám tuần tại nhà Phật tử, song với
điều kiện tang gia thân quyến tụ họp lại, để nghe Tăng, Ni giảng một thời kinh, xong
rồi hồi hướng công đức cho người chết, Tăng, Ni ra về. Như thế, khả dĩ nói *“dĩ huyễn
độ chân”* được. Bởi vì nhân người chết, chúng ta giáo hóa kẻ sống cho hiểu đạo lý.
Đám tuần, ngày kỵ đều nên tổ chức như thế, việc làm này không trái với chánh pháp.

Hoặc có người nói Phật giáo từ bi, khi giáo hoá kẻ dương là nghĩ đến người âm,
muốn làm sao cho âm dương lưỡng lợi, mới đầy đủ lòng từ. Chúng tôi đồng ý lẽ này,
nhưng trong chùa trước khi thọ trai, Phật dạy Tăng, Ni phải cúng chim đại bàng, quỉ
la-sát và các quỉ thần, không phải vì kẻ âm là gì? Mỗi chiều ở chùa hầu hết đều dùng
nghi Mông Sơn để cúng cô hồn, đâu không phải vì kẻ âm. Hằng đêm ở chùa hai thời
công phu, Tịnh độ sau đó đều phục nguyện *“âm siêu dương thới”*, còn gì không đủ
lòng từ bi. Nếu Phật tử có lòng hiếu thảo muốn cầu nguyện cho thân nhân, cứ đến chùa
vào những thời công phu, Tịnh độ, Tăng, Ni sẽ vì thân nhân họ cầu nguyện cho. Có
thế, không mất thì giờ tu hành của Tăng, Ni, Phật tử cũng được mãn nguyện. Biết tôn
trọng những bậc thầy hướng dẫn mình mới gọi người ấy biết đạo đức, vì việc riêng của
mình, để bậc thầy mình mất hết giá trị cao thượng, là đạo đức chỗ nào? Sự hướng dẫn
không khéo cả thầy lẫn trò làm việc vô nghĩa, còn chuốc lấy sự đau khổ là khác. Khi
Phật còn tại thế, chúng ta có nghe Ngài đi đưa đám lần nào đâu. Cho đến chư Tỳ-kheo
môn đồ của Phật, cũng không nghe đi đưa đám lần nào. Tại sao chúng ta hiện nay, cứ
bận rộn đám ma đám tuần mãi. Thế là chúng ta đã đi đúng đường Phật hay đã sai rồi,
cần phải vận dụng công tâm xét lại điều này. Bởi Tăng, Ni xuất hiện trong xóm làng
đều do nhà có ma chay, nên bất thần Tăng, Ni đến nhà người nào họ liền ghét sợ, coi
như một điềm bất tường sắp đến cho gia đình họ. Thật là ngày xưa xem *“một vị Tăng
đến là một ông Phật lại”*, ngày nay thì ngược lại. Thử hỏi còn gì hổ thẹn cho bằng?

## Kết luận {- #ket-luan-phat-giao-do-sanh}

Chủ yếu Phật giáo độ sanh một cách thiết thực, người môn đồ Phật giáo phải
thấy rõ điều này. Tất cả hành động, mọi cuộc tổ chức đều nhằm thẳng giáo hoá chúng
sanh, bằng con đường từ bi giác ngộ. Đem hạt giống từ bi giác ngộ gieo rắc trong lòng
mọi người là truyền bá đạo Phật. Ngược lại, đem tình cảm mê tín gieo rắc trong lòng
tín đồ, thử hỏi đây là truyền đạo gì? Vì giải thoát cho mình cho chúng sanh, nên chúng
ta đi tu, tại sao chúng ta trở thành kẻ chiều chuộng phục vụ tín đồ để được cơm ăn áo
mặc? Quả là điều sai đạo lý không hợp với chánh pháp, chúng ta phải gan dạ đập tan
những tập tục sai lầm ấy, đem lại con đường tu hành cao thượng thanh bai cho chính
mình và huynh đệ mai sau. Trọng trách của chúng ta không phải đóng khung trong một
nhóm bổn đạo, mà phải đem đạo giác ngộ giải thoát lại cho toàn thể chúng sanh. Làm
được như vậy mới đúng tinh thần Phật giáo độ sanh.
