
# Luân hồi {- #luan-hoi}

## Mở đề {- #mo-de-luan-hoi}

Có một số người bảo: *“Nhà Phật nói luân hồi để ru ngủ con người trong giấc
mơ mê tín”*. Chúng ta khảo sát kỹ coi câu ấy có đúng thế không? Đó là nhiệm vụ của
người truyền bá Phật giáo, cần phải làm sáng tỏ vấn đề này. Bởi thuyết luân hồi là một
thuyết quan trọng trong nhà Phật, nếu là mê tín thì đạo Phật là đạo mê tín hay sao? Hẳn
không phải thế, đạo Phật là đạo giác ngộ, truyền bá những lẽ thật của mình giác ngộ
được cho chúng sanh biết là nhiệm vụ của đức Phật. Chúng ta là người nối bước theo
sau đức Phật, cần phải nghiên cứu tường tận giải bày rõ ràng để mọi người được hiểu
khỏi sanh nghi ngờ là một điều cần yếu không thể thiếu được. Lý luân hồi là một cơ
cấu hệ trọng trong Phật pháp, bao gồm cả nhân quả, nghiệp báo là căn bản đạo đức của
người tu Phật. Không thông lý luân hồi, người Phật tử khó bề tu tiến được. Do đó,
chúng ta cần phải tìm hiểu cho thấu đáo.

## Định nghĩa {- #dinh-nghia-luan-hoi}

Luân hồi là xoay vần, cứ mãi đảo lên lộn xuống xoay vần trong khuôn khổ cố
định. Mọi sự đổi thay biến chuyển không đứng yên một vị trí nào. Hằng xê dịch biến
thiên từ trạng thái này sang trạng thái khác, từ hình tướng này sang hình tướng khác.
Tất cả sự biến thiên đều tuỳ duyên thăng trầm không nhất định là luân hồi.

## Luân hồi là sự thật {- #luan-hoi-la-su-that}

Qua định nghĩa trên, chúng ta thấy luân hồi là một triết lý thực tiễn không còn
gì phải nghi ngờ. Bởi vì con người và vũ trụ hiện tại đều nằm chung trong một định
luật *“biến thiên”*.

### Quả đất luân hồi {- #qua-dat-luan-hoi}

Nhờ khoa học phát minh cho biết quả địa cầu chúng ta
đang ở xoay tròn quanh một cái trục trong không gian. Do sự xoay tròn này, phía nào
của quả đất hướng về mặt trời là sáng, phía bị khuất là tối. Từ đó, con người mới đặt ra
thời gian. Sự xoay tròn này không phải luân hồi là gì? Quả đất xoay khiến có ngày
đêm và hai mươi bốn tiếng đồng hồ nhịp nhàng theo chiều quay của trái đất, lại có chia
xuân hạ thu đông, do sự xê dịch gần và xa mặt trời. Từ sự xoay tròn của trái đất, nảy
sanh thời gian, thời gian và trái đất đều là luân hồi. Quả đất là chỗ tựa nương để sống
còn của vạn vật và con người; bản thân nó đã luân hồi thì những vật tựa nương vào nó
làm sao khỏi luân hồi. Thế thì cả vũ trụ lẫn vạn vật cùng toàn thể chúng sanh đều là
luân hồi. Đó là một sự thật căn cứ trên khoa học, chớ không phải là chuyện huyền
thoại mơ hồ. Thể theo sự nhận xét tổng quát này, chúng ta cần đi chi tiết hơn cho dễ
hiểu.

### Vạn vật luân hồi {- #van-vat-luan-hoi}

Muôn vật trên quả địa cầu đều cùng chung luân hồi.

Về sinh vật từ cái cây cọng cỏ bởi do hạt nẩy mầm tăng trưởng thành cây, sanh
hạt, đảo đi lộn lại mãi không cùng. Các loài động vật thì từ trứng nở thành con, con lại
sanh trứng; hoặc từ bào thai thành hình, khi trưởng thành lại có bào thai, lẩn quẩn
loanh quanh không cùng. Đó là chúng ta nói sự luân hồi trong cuộc tiếp nối. Đến ngay
bản thân sự vật cũng bị luân hồi, chúng sanh trưởng thành là do đất nước gió lửa, khi
tan hoại cũng trở về đất, nước, gió, lửa, tụ lại tán ra theo duyên biến chuyển chẳng
cùng. Bản thân đất nước gió lửa vẫn bị luân hồi. Như sáng sớm, chúng ta lấy thau múc
một phần ba thau nước đem để ngoài trời nắng, đến chiều thau nước cạn khô. Thử hỏi
nước đi đâu? Nước mất hết rồi sao? Nước không đi đâu, nước cũng chẳng mất, chẳng
qua nước là thể lỏng do ánh nắng nóng bốc lên thành thể hơi, hơi theo gió bàng bạc
trong hư không nào có định xứ. Thể hơi gặp khí lạnh đọng lại rơi xuống thành nước,
nước lại bốc thành hơi, cứ thế mãi luân hồi không cùng. Gió lửa đất cũng thế, tùy
duyên từ hình thái này đổi sang hình thái khác, đổi đổi thay thay không có ngày cùng.
Tìm chỗ bắt đầu và chung cục của chúng không thể được. Hình tướng trạng thái luôn
luôn đổi thay, sự thật vẫn không bao giờ mất. Từ một hình tướng thô đổi thành một
trạng thái tế, với cái nhìn thô thiển người ta bảo là mất, thật sự nào có mất, chỉ là biến
thái.

### Con người luân hồi {- #con-nguoi-luan-hoi}

Nói đến con người tạm chia làm hai phần, vật chất và
tinh thần, như bóng đèn và điện. Ngọn đèn phát huy được ánh sáng phải có đủ hai điều
kiện hỗ tương nhau. Có bóng đèn mà không có điện trở thành vô ích, có điện mà
không có bóng đèn cũng vô nghĩa. Sự hỗ tương giữa điện và bóng đèn không thể tách
rời, không thể đặt giá trị thiên trọng, không thể xem như chủ khách. Cần phải thấy sự
tương quan bất khả phân ly. Tinh thần và vật chất của con người cũng thế, mọi sự phân
chia, khinh trọng... đều sai ý nghĩa chân thật của nó. Vì muốn thấy sự luân hồi tường
tận, chúng ta tạm nhìn con người ở hai mặt để dễ bề nhận xét:

#### Vật chất luân hồi {- #vat-chat-luan-hoi}

Phần vật chất nơi con người, nhà Phật chia tổng quát
làm 4 phần: đất, nước, gió, lửa. Những loại cứng trong thân người, như da thịt gân
xương tóc lông răng móng... thuộc về đất. Các loại ướt, như máu mủ, mồ hôi đàm dãi
nước mắt nước mũi... thuộc về nước. Hít không khí vào cho phổi hô hấp, quả tim đập,
các mạch máu nhảy... mọi thứ động thuộc về gió. Nhiệt độ trong người làm cho thức
ăn tiêu hóa, máu không đông đặc, ấm áp toàn thân... thuộc về lửa. Bốn thứ này thiếu
một là con người chết ngay. Ở đây chúng ta phân tích sự luân hồi từng thứ:

- Đất luân hồi:  
Thâu nhận tế bào mới, đào thải tế bào cũ, thay mới đổi cũ
không lúc nào dừng, ấy là luân hồi. Cho đến thân này sống nhờ ăn những thức có chất
bột *(đất)*, khi chết nó tan hoại trở thành đất. Khi sống mượn những chất đất bồi dưỡng,
lúc chết trả lại cho đất. Hợp lại tan ra, tan ra hợp lại, không phải luân hồi là gì?

- Nước luân hồi:  
Máu từ quả tim chạy khắp các mạch, rồi trở về quả tim,
chạy ra trở về, trở về chạy ra, sự tuần hoàn như vậy gọi là luân hồi. Cho đến khi sống
mượn nước để bồi bổ chất ướt trong thân, lúc chết chảy ra trở về lòng đất. Sự mượn trả
mà không bao giờ mất ấy là luân hồi.

- Gió luân hồi:  
Hít không khí vô, thở không khí ra, hít vô thở ra cả đời
như vậy là luân hồi. Nhờ cái động của thở hít không khí mà các cơ quan trong toàn
thân hoạt động, các cơ quan hoạt động là thân sống. Đến khi thở không khí ra mà
không hít lại, liền ngừng hoạt động, tức là thân chết. Thế thì sự sống của thân này đích
thực do luân hồi của gió, gió ngưng luân hồi thì thân phải hoại diệt.

- Lửa luân hồi:  
Do những thức ăn có chất nóng nuôi dưỡng phần lửa
trong thân. Lửa dùng sưởi ấm toàn thân, thiêu đốt vật thực, lại do vật thực bồi bổ chất
lửa. Cứ tiêu dùng, bồi bổ, bồi bổ tiêu dùng, đảo đi lộn lại là luân hồi. Khi tiêu dùng mà
không bồi bổ kịp, lửa từ từ tắt, con người chết. Lửa ấy trở về với thiên nhiên, tùy
duyên chuyển biến trong không gian, mà chưa bao giờ mất là luân hồi.

Tóm lại, tứ đại tụ họp quân bình nhau là con người sống khỏe mạnh, nếu thiếu
quân bình là ốm đau, phân tán thì tử vong. Trong khi tứ đại tụ họp trong thân này luôn
luôn biến chuyển tuần hoàn, không được ngăn trệ ứ đọng. Vừa bị ngăn trệ ứ đọng là
thân này nguy ngập. Sự biến chuyển tuần hoàn của tứ đại trong thân con người gọi
chung là vật chất luân hồi. Sở dĩ nói luân hồi vì biến chuyển mà không phải mất hẳn.

#### Tinh thần luân hồi *(tâm sở luân hồi)* {- #tinh-than-luan-hoi}

Phần tinh thần của chúng ta luôn luôn
thay đổi bất thường, không bao giờ đứng yên ở một vị trí. Những thứ buồn vui, yêu
ghét, thương giận, lành dữ, phải quấy... thường thay mặt đổi mày như trên sân khấu.
Có khi chúng ta hiền lành như ông Phật, có lúc giận dữ như con cọp đói. Nhiều lúc vui
vẻ yêu thương, lắm khi bực bội thù địch. Những tâm trạng đổi thay không lường được,
chính tự thân chúng ta cũng không ước đoán nổi tâm trạng của mình sẽ xảy ra những
cái gì. Sự buồn vui thương ghét đổi thay thăng giáng nơi nội tâm chúng ta gọi là luân
hồi.

Nói chung nơi con người chúng ta, hai phần vât chất lẫn tinh thần đều là tướng
trạng luân hồi. Sự luân hồi của chúng là sự hoạt động sống còn của ta. Biết rõ vật chất
tinh thần chỉ đổi thay hình tướng trạng thái, chớ không một vật nào mất. Nếu thấy mất,
chẳng qua do cái nhìn cạn cợt nông nổi mà kết luận như thế. Thực thể của nó là *“biến
thiên mà bất diệt”*, thấy đến chỗ tận cùng ấy, mới khỏi nghi ngờ về lý luân hồi. Sự luân
hồi ngay trong thân hiện tại này là hiện tại luân hồi. Đến sự tụ lại tan ra, tan ra tụ lại
của thân con người là luân hồi đời này sang đời khác.

Mọi sự tụ tán đều tùy duyên khiến hình tướng trạng thái đổi khác. Ví dụ nước
do duyên nóng bốc thành hơi, gặp duyên lạnh cô đọng thành khối. Sự biến thái này đều
do duyên quyết định. Duyên quyết định cho sự luân hồi của con người là gì? Là
nghiệp. Nghiệp là động cơ chánh yếu trong cuộc luân hồi của con người.

## Động cơ luân hồi {- #dong-co-luan-hoi}

Nghiệp là hành động từ thân tâm con người tạo thành. Khi thành nghiệp rồi nó
thúc đẩy dẫn dắt con người đến chỗ thành quả của nó. Chính nó là động cơ quan yếu
đẩy mãi trong vòng luân hồi không dừng của tất cả chúng sanh. Cơ quan tạo nghiệp có
ba thứ, thân miệng và ý. Nói đến nghiệp là nói đến sự toàn quyền quyết định nơi mọi
người chúng ta. Không ai tạo nghiệp thế cho chúng ta, cũng không ai có thể thay thế
nghiệp cho chúng ta. Chính chúng ta là chủ nhân tạo nghiệp, cũng là chủ nhân thọ báo.
Trọng trách của mọi sự khổ vui hiện tại và mai sau đều do chúng ta quyết định. Chủ
trương nghiệp là chủ trương giành lại toàn quyền cho con người. Chúng ta là chủ nhân
của chúng ta hiện tại và vị lai. Không phải một đấng Thượng đế hay một tha nhân nào
khác tạo thành một cuộc sống an vui hay đau khổ cho chúng ta, mà chính do thân
miệng ý của chúng ta trong quá khứ cũng như hiện tại gây nên. Chúng ta thừa nhận
nghiệp do mình tạo ra, đã tước hết mọi quyền năng của các đấng thiêng liêng, của định
mạng, của tướng số và của rủi may. Nghiệp là hành động, là thói quen nên có thể
chuyển đổi, chỉ cần nỗ lực và bền chí. Nghiệp có nghiệp thiện và nghiệp ác.

### Nghiệp ác {- #nghiep-ac-luan-hoi}

Nghiệp ác là hành động làm cho người khổ và mình khổ, hoặc ở
hiện tại hay ở vị lai. Hành động này do ba cơ quan tạo nên: thân, miệng, ý.

- Thân làm ác:  
Để cho thân buông lung thích hành động giết hại sanh mạng
người, hoặc thích trộm cướp tài sản người, hoặc đắm say dâm dật trái phép, là nghiệp
ác của thân. Vì hành động này làm cho người khổ và mình khổ, nếu hiện tại chưa đến
thì vị lai cũng chịu.


- Miệng làm ác:  
Miệng ưa nói lời dối trá, lời ác độc, lời ly gián, lời thêu dệt,
là nghiệp ác của miệng. Vì những lời nói này khiến người nghi ngờ bực tức đau khổ
mang tai họa, nên hiện tại hoặc vị lai mình cũng phải nhận lấy hậu quả đau khổ ấy.

- Ý làm ác:  
Si mê, tham lam, nóng giận là nghiệp ác của ý. Chính nó là động
cơ thúc đẩy thân làm ác, miệng nói ác. Bản thân nó thì chưa làm hại được ai, song do
nó khiến thân sát phạt người, miệng chửi bới nguyền rủa người. Thân miệng mà không
cộng với tham sân si thì tự nó không có lỗi lầm gì. Thế nên, tuy nói ba cơ quan tạo
nghiệp, mà ý là cơ quan hệ trọng hơn cả, nó là chủ động của hai cơ quan kia.

### Nghiệp thiện {- #nghiep-thien-luan-hoi}  

Những hành động đem lại sự an ổn vui vẻ cho người và mình
là nghiệp thiện. Sự an ổn vui vẻ chẳng những có trong hiện tại mà còn đến vị lai. Cũng
do ba cơ quan tạo thành nghiệp thiện: thân, miệng, ý.

- Thân làm lành:  
Thân không giết hại người, không trộm cướp tài sản người,
không dâm dật phi pháp là nghiệp thiện của thân. Tại sao không làm ba việc ấy là
thiện? Bởi vì con người quí nhất là sanh mạng, chúng ta không hại sanh mạng họ thì
họ đến với chúng ta một cách an ổn không sợ sệt. Thứ yếu là tài sản, con người tự thấy
tài sản là huyết mạch của họ, chúng ta nhất quyết không trộm cướp thì, họ đến với
chúng ta cũng như chúng ta đến với họ, đều được an vui không hồi hộp lo âu về mất
của. Hạnh phúc của gia đình là vợ chồng hòa thuận tin yêu trinh bạch với nhau, nếu vợ
hay chồng có tình ý riêng tư với ai là gia đình mất hạnh phúc. Chúng ta giữ gìn không
theo sự dâm dật phi pháp, đến với gia đình ai họ đều an ổn vui vẻ không nghi ngờ sợ
sệt chi cả. Gìn giữ ba điều này, chúng ta đã ban sự an ổn vui tươi cho bao nhiêu người
rồi, cũng chính là đem lại sự an ổn vui tươi cho gia đình chúng ta.

- Miệng làm lành:  
Miệng không nói dối trá, không nói ác độc, không nói ly
gián, không nói thêu dệt là miệng làm nghiệp lành. Vì sao? Bởi vì, nói dối trá khiến
người nghi ngờ mất niềm tin, đã không tin nhau làm gì có thương mến. Thế nên nói
dối là căn bản khiến con người mất hết tình thương. Nói ác độc khiến người nghe sanh
phẫn nộ bực dọc đau khổ. Nói ly gián làm cho thân thuộc họ phải chia lìa, tạo thành
cái khổ ái biệt ly. Nói thêu dệt là tô điểm không đúng chân lý, khiến người không tìm
ra được lẽ thật. Chúng ta quyết định gìn giữ miệng không nói bốn điều trên là tạo được
tình thân giữa mình và người, đem lại cho mọi người sự an ổn, bảo vệ được tình thân
của người, giúp cho người dễ nhận ra lẽ thật. Thế là, chúng ta đã tạo điều kiện tốt đẹp
cho xã hội biết mấy.

- Ý làm lành:  
Ý không có tham sân si là ý làm nghiệp lành. Chúng ta thường
thấy mọi sự bất bình đổ vỡ đều phát nguồn từ tham sân si. Nếu chúng ta không để cho
tham sân si dẫn dắt hoành hành thì cả cuộc đời chúng ta được an ổn, cũng là nguồn an
ổn cho mọi người. Ba thứ này gọi là tam độc, vì nó gây đau khổ cho mình và người
không thể lường trước được. Người nào kềm cương giữ thắng được nó, bảo đảm được
một đời sống an lành, cũng bảo vệ được an ninh trật tự cho mọi người. Ngược lại, kẻ
nào buông cương thả thắng nó sẽ lôi đời họ vào hố sâu nguy hiểm, cũng gây họa hại
cho khách bàng quan không ít. Thế nên, không cho tham sân si nổi dậy là gìn giữ sự an
ổn vẹn toàn cho mình và mọi người.

### Khả năng của nghiệp {- #kha-nang-cua-nghiep}

Nghiệp là cái không có hình tướng mà có khả năng
đáng kể. Ví như gió, tuy không thấy hình tướng mà nó thổi đất nước đều lung lay.
Nghiệp cũng thế, bình thường chúng ta không thấy nó, mà nó lôi chúng ta đi khắp nẻo
luân hồi. Sở dĩ nó có khả năng mạnh mẽ như vậy là do tập quán lâu ngày. Như người
tập hút thuốc, buổi đầu khói thuốc chỉ cảm thấy khó chịu, nhưng tập lâu ngày thành
ghiền, khi ghiền rồi với giá nào cũng phải tìm cho có nó. Thử hỏi cái ghiền ấy hình
tướng ra sao, mà điều khiển con người một cách mãnh liệt như thế? Quả thật không ai
biết tướng mạo của nó, nhưng khi nó đòi hỏi, người ta phải chạy ngược chạy xuôi tìm
cho ra thuốc hút. Bệnh ghiền rượu khả năng còn mạnh hơn, từ những hớp rượu cay xé
mồm, tập mãi thành quen, bắt đầu ghiền rượu. Khi ghiền không có rượu khiến người ta
phải ụa phải mửa, oằn oại nhọc nhằn, ngáp trời ngáp đất, quả thật chi phối hết khả
năng con người.   

Chúng ta tự đặt câu hỏi, ai đem bệnh ghiền ấy đến cho chúng ta?
Chính chúng ta tự tập, tập lâu thành ghiền, cái ghiền ấy do mình tạo rồi mình chịu. Cái
ghiền ấy có ma lực gì mà đày đọa hành hạ con người đến thế? Hắn không có ma lực gì,
chẳng qua tập lâu ngày thành thói quen, thói quen càng lâu sức càng mạnh. Đã tự
chúng ta tập thành bệnh, khi muốn hết bệnh cũng tự chúng ta gan dạ bỏ nó, không ai
có thể bỏ thế cho chúng ta. Khả năng của bệnh ghiền giống hệt khả năng nghiệp chi
phối chúng ta trong lục đạo luân hồi vậy. Tự chúng ta tạo nghiệp lành hoặc nghiệp dữ,
tạo càng lâu thì sức mạnh càng lắm, đến cuối cùng chúng chi phối dẫn dắt chúng ta đi
vào con đường lành hay dữ tùy chỗ gây tạo của mình. Không phải hóa công đày đọa,
không phải Thượng đế bày ra, chính chúng ta tự tạo rồi tự thọ. Khi đã thành nghiệp,
chúng ta khó cưỡng được nó.  
  
Thế nên, biết chọn nghiệp lành để tạo là đã tự gây một
sức mạnh đưa mình đến cõi lành. Cắm đầu gây nghiệp ác là tạo áp lực lôi mình vào cõi
dữ. Chính đây là quyền lựa chọn của con người, quyền định đoạt số phận ở mai hậu.
Nếu cứ sống say chết ngủ đẩy đâu đi đấy, những kẻ này về sau than trời trách đất nào
có ích gì. Chúng ta có đủ thẩm quyền quyết định đời mình hiện tại và vị lai, tại sao
chúng ta lại bỏ mất cái giá trị cao cả ấy. Những kết quả tốt xấu dở hay ở hiện nay và
mai kia đều nằm sẵn trong tay chúng ta. Chúng ta có quyền phán quyết một bản án tốt
xấu trong đời sống mai sau của mình. Đừng cầu khẩn van xin bất cứ một năng lực nào
ngoài chúng ta. Nói đến khả năng nghiệp là khả năng của chúng ta, nghiệp và chúng ta
không phải là hai. Nếu chúng ta khôn ngoan khéo léo lo tạo nghiệp lành, chúng ta dại
khờ ngu muội gây tạo nghiệp ác. Khổ vui sẽ tùy nghiệp mang đến với chúng ta một
cách chân thành.

## Tất yếu của luân hồi {- #tat-yeu-cua-luan-hoi}

Tạo nghiệp là nhân, thọ báo là quả. Tất yếu của sự luân hồi là nhân quả. Lăn lộn
trong ba cõi sáu đường đều tùy thuộc nhân quả. Mình đã gây nhân nhất định mình phải
chịu quả, quả khổ quả vui là do gây nhân khổ vui. Nhân quả là lẽ công bằng chân thật,
bởi mỗi cá nhân gây tạo khác nhau, nên sự thọ nhận cũng sai biệt. Sự công bằng từ
nhân đến quả, không phải sự công bằng do ai khác áp đặt cho mình. Nếu do kẻ khác áp
đặt cho mình là đã bất công rồi. Ngày nay chúng ta tạo nhân, ngày mai chúng ta thọ
quả, thật là rõ ràng rành mạch biết bao. Song nói tới nhân quả là căn cứ trên thời gian
suốt cả quá khứ hiện tại vị lai, trong quá khứ có cái gần có cái xa, vị lai cũng thế, khiến
có những kết quả xảy đến mà đương sự không bao giờ nhớ. Lại có những sự kiện gây
nhân mà không thấy kết quả. Do đó nhân quả trở thành rắc rối khó khăn, người ta khó
tin khó nhận. Nhưng sự thật lúc nào cũng thật, bởi khả năng nhớ hiểu của con người
quá giới hạn, nên có những thắc mắc thế thôi. Nếu người nhận hiểu sâu về lý nhân quả
thì cuộc sống này đã có tiêu chuẩn nhắm đến và an ổn vô cùng. Vì mọi kết quả hiện
chịu trong đời đều do nhân gây ra từ thuở trước, nên khổ không oán hờn, vui không
ngạo mạn. Mình làm mình chịu, chỉ quí ngang đây phải chọn lấy nhân tốt mà làm, để
mai kia khỏi phải thọ quả đau khổ, cho nên trong kinh nói: *“Bồ-tát sợ nhân, chúng
sanh sợ quả”*. Kẻ trí thì sợ nhân, người ngu thì sợ quả. Do cái nhìn thấu suốt và cái
nhìn nông cạn, nên có chia Bồ-tát và chúng sanh. Nhân có thiện ác thì quả cũng có khổ
vui.

Những kẻ gây tạo nghiệp ác, ắt phải thọ quả khổ trong ba đường dữ, địa ngục
ngạ quỉ súc sanh. Nghiệp ác là mình làm cho kẻ khác khổ, cân xứng với nhân mình
gây, thọ quả khổ một nơi trong ba đường dữ. Nhân khổ có khi không thành quả, do
nửa chừng mình biết hối cải, hoặc chuyển đổi. Nhân khổ nhất định thọ quả khổ, do sự
nuôi dưỡng một cách sung mãn. Ví như có người uống rượu mà không ghiền, vì họ
biết giới hạn chừa bỏ. Có người uống rượu nhất định phải ghiền rượu, vì họ mãi tiếp
tục và say mê. Có nhân khổ mà không thọ quả khổ, hoặc nhất định phải thọ quả khổ,
cũng như thế.

Người gây tạo nghiệp thiện ắt thọ quả vui trong cõi người, cõi a-tu-la và cõi
trời. Cân xứng với nghiệp lành mình đã tạo, nhiều ít cao thấp, kết quả cũng có hơn
kém thấp cao. Có khi người tạo nghiệp lành mà không được quả lành, hoặc người tạo
nghiệp lành nhất định hưởng quả lành. Ví như, một số sinh viên vào học y khoa, có
người không đủ khả năng học hoặc lười biếng học, nên tuy học y khoa mà không kết
quả thành bác sĩ. Có người đủ khả năng lại cần cù học tập, nhất định một ngày kia sẽ
thành bác sĩ. Từ nhân đến quả còn cần có những sự kiện trợ giúp đầy đủ mới được
viên mãn. Không thể có nhận định tất nhiên rằng có nhân là có quả. Bởi vì thời gian từ
nhân đến quả là giai đoạn biến động, hoặc được tăng trưởng, hoặc bị tiêu mòn, tùy
theo những sự kiện trợ giúp. Biết thế, chúng ta có thể chuyển nhân xấu thành tốt, hoặc
nhân tốt trở ra xấu.

Sự tất yếu của luân hồi tùy thuộc nhân quả, không có kẻ nào khác áp đặt khổ
vui cho chúng ta, cũng không có bàn tay nào lôi kéo chúng ta phải đi đường này hay
lối khác, mọi sự kết quả đều cân xứng với nhân mình gây tạo. Nắm vững yếu tố này,
mới thấy chúng ta trọn quyền định đoạt số phận của chúng ta. Nếu cuộc đời của chúng
ta hiện nay được tươi sáng hay đen tối, đều do sự khéo léo hay vụng về của ta ngày
xưa. Can đảm nhận lấy trách nhiệm của mình, không oán trách kêu ca, không than thân
tủi phận. Chúng ta gan dạ trong cuộc sống hiện tại, song phải khôn ngoan chọn lấy lối
đi ở ngày mai.

## Thoát ly luân hồi {- #thoat-ly-luan-hoi}

Đạo Phật giải rõ lý luân hồi, nhưng không phải để mãi chịu luân hồi. Biết luân
hồi tường tận rồi, Phật chỉ ra con đường thoát ly luân hồi. Đúng như ý nghĩa biết khổ,
chúng ta mới tìm cách thoát khổ. Luân hồi là vòng loanh quanh lẩn quẩn, nhào đi lộn
lại không thể thoát ra. Chấp nhận trong vòng quanh quẩn đó, do người không tìm được
manh mối thoát ra, hoặc không đủ khả năng để thoát ra. Như các nhà khoa học phát
minh được sức hút của trái đất, mọi vật cam chịu trong vòng vọt lên rớt xuống, không
sao thoát ra ngoài được. Nhưng cũng các nhà khoa học chế phi thuyền đủ khả năng vọt
ra ngoài vòng hút của trái đất, đi thám hiểm các hành tinh khác. Biết rõ sức hút của trái
đất rồi, mới chế được phi thuyền vọt ra ngoài sức hút. Cũng thế, Phật giải rõ lý luân
hồi rồi, mới dạy phương pháp thoát ly luân hồi. Mục đích của đạo Phật là thoát ly sanh
tử luân hồi, không chấp nhận sự loanh quanh trong vòng sanh tử. Còn trong sanh tử dù
dài ngắn khổ vui , đạo Phật đều kết luận là đau khổ, vì cùng một số phận vô thường.
Chỉ thoát được luân hồi mới là an vui giải thoát.


## Kết luận {- #ket-luan-luan-hoi}

Đạo Phật nói lý luân hồi cũng là phát minh một sự thật của vạn vật và con
người. Vì đối tượng của đạo Phật là con người, nên chung qui đặt nặng về sự luân hồi
của con người. Con người nhận hiểu thấu đáo về lý luân hồi, nếu họ không có khả
năng thoát khỏi luân hồi, tự mình chọn lựa cuộc luân hồi an vui và thoải mái. Nếu họ
có khả năng thoát ly luân hồi, do hiểu luân hồi tiến tu đạo giải thoát. Biết được lý luân
hồi, chúng ta biết được lẽ công bằng của con người, cũng nhận lấy sự tự do căn bản
nơi chúng ta. Mọi mê tín ỷ lại đều tiêu tan, do biết ta là người quyết định thân phận của
mình. Tất cả oán hờn tủi hận đều sạch hết, vì có ai áp đặt sự đau khổ cho mình mà than
thở. Quả chúng ta là con người độc lập tự do của chính mình trong hiện tại và vị lai.
Dù chưa giải thoát, biết được lý luân hồi, chúng ta cũng sáng suốt và an ổn ngay trong
đời sống này. Mọi tương lai đều nằm trong tay chúng ta, chúng ta trọn quyền chọn lấy
một tương lai nào theo sở thích của mình.
