
# Mê tín chánh tín {- #me-tin-chanh-tin}

## Mở đề {- #mo-de-me-tin-chanh-tin}

Đạo Phật chủ trương giác ngộ mang ánh sáng trí tuệ soi rọi cho thế gian. Mọi lẽ
thật đều hiện bày dưới ánh sáng giác ngộ, nhận thấy lẽ thật rồi mới khởi lòng tin đó là
*“chánh tín”*. Ngược lại, bày những điều mê hoặc làm mù quáng người đời, lừa bịp thế
gian, ấy là *“mê tín”*. Hoặc không hiểu rõ, không có lý lẽ, mà tin càn tin bướng là *“mê
tín”*. Tin bướng là họa hại đưa con người đến đường mù tối. Thấy rõ biết đúng mới tin
là sức mạnh vô biên khiến người thành công trên mọi lãnh vực. Thế nên trong kinh
Hoa Nghiêm có câu: *“Tin là nguồn của đạo, là mẹ của mọi công đức. Tin hay nuôi lớn
các gốc lành”*. Vì thế người học đạo cần có lòng tin, song lòng tin đã qua sàng lý trí
gạn lọc kỹ càng. Tuyệt đối không được tin càn, tin bướng làm băng hoại tinh thần giác
ngộ của đạo Phật. Chính trong kinh Di Giáo Phật dạy: *“... Xem tướng lành dữ, trông
xem sao hạn, xem xét thạnh suy, coi ngày đoán số đều không được làm...”*

## Mê tín {- #me-tin}

Mê tín là lối tin mù quáng khiến con người mất hết trí thông minh. Những kẻ
chủ trương mê tín là người làm hoặc loạn thế gian, đưa dân tộc lùi lại bán khai. Một
tôn giáo chân chánh, một dân tộc văn minh, không cho phép mê tín len lỏi trong tín đồ
mình, trong dân tộc mình. Thế mà, đồng bào chúng ta, trong Phật giáo chúng ta, tệ
đoan mê tín vẫn còn nhiều.

### Đồng cốt {- #dong-cot}

Đồng cốt là hiện tượng mê hoặc khủng khiếp. Những kẻ làm ông đồng, bà cốt
đều là người sống trong trạng thái bất bình thường. Bản thân họ đã mất hết khả năng tự
chủ, họ bị sai sử bởi một ma lực huyền bí nào đó. Khi ma lực ấy dựa vào họ, liền lạm
dụng các danh hiệu thánh, những bậc vĩ nhân của thuở xưa dùng mạo xưng để lừa bịp
người đời. Những kẻ yếu vía dễ tin nghe xưng danh hiệu Phật, Bồ-tát hay những vị
tiên thánh liền khiếp đảm kính tin. Họ không dám phê phán đó là tà hay chánh. Thế
rồi, họ một mực quì mọp để được phong chức, hoặc nhận phép lành. Họ bị gạt bằng
những danh hão trong cõi vô hình, hoặc bằng những bùa tà phép lạ, những huyền hoặc
về quá khứ vị lai. Từ đây họ sống bằng ảo vọng mơ huyền, mất hết lý trí thực tại.

Chúng ta phải khám phá dẹp tan những lối mê hoặc ấy. Riêng về nhà Phật trong
kinh đã dạy rõ, khi chứng đến quả Phật, Bồ-tát, A-la-hán đều có đầy đủ lục thông, tam
minh... Vì thế, Bồ-tát hay A-la-hán muốn hóa độ kẻ hữu duyên liền dùng thần thông
hiện giáo hóa, như Bồ-tát Quán Thế Âm, trong phẩm Phổ Môn của kinh Pháp Hoa
chẳng hạn. Không khi nào các bậc Thánh phải gá vào thân kẻ phàm tục khác làm việc
giáo hóa. Vì các ngài đầy đủ thần thông biến hóa vô ngại. Như thế, những ma lực tựa
vào đồng cốt đều là sức của quỉ thần. Vì sợ người đời không tin, nên chúng mạo xưng
những danh hiệu cho to để gây uy tín. Biết rõ tính cách ma mị của chúng, người Phật
tử phải tránh xa, tuyệt đối không được phụ họa với chúng, huống là qui kính. Có thế
mới tỏ ra là người Phật tử chân chánh.

### Lịch số, sao hạn {- #lich-so-sao-han}

Thời gian không thật do khái niệm con người đặt ra, huống là trên thời gian lại
đặt ra ngày tốt ngày xấu, năm lành năm dữ... Thử đặt ra một thí dụ, chúng ta đốt một
ngọn đèn đặt ở bên phải, lấy một cái gương tròn nhỏ để ở bên trái, cách nhau năm tấc
tây, khoảng giữa đặt một quả bóng *(trái banh)*. Chúng ta dùng tay xoay tròn quả bóng,
phía nằm bên ngọn đèn là sáng, phía khuất ngọn đèn là tối, cứ xoay mãi, quả bóng đối
chiếu tối sáng liên tục. Trục quay ấy có lúc tiến đến trước ngang ngọn đèn làm khuất
ánh sáng soi vào mặt gương, ánh sáng mặt gương không phản chiếu vào quả bóng, có
lúc lùi lại sau, ánh sáng ngọn đèn soi vào mặt gương, ánh sáng từ mặt gương phản
chiếu lại quả bóng, phía khuất ngọn đèn. Có những con kiến ở trên quả bóng, thấy quả
bóng mặt sáng gọi là ngày, mặt tối gọi là đêm, những lúc mặt gương không phản chiếu
ánh sáng vào quả bóng gọi là ba mươi, những lúc mặt gương phản chiếu ánh sáng vào
quả bóng đầy đủ gọi là rằm... Lại đặt mặt sáng của quả bóng vòng một là ngày tốt,
vòng hai là ngày xấu... Cảm thông được điều đó, chúng ta có tức cười cho loài kiến
hay không? Quả thật, chúng bày biện một cách vô lý. Ngọn đèn, quả bóng, mặt gương
đều là vô tri, động lực quay nó thì cứ quay vậy thôi, có gì là linh thiêng huyền diệu, mà
chúng lại đặt là ngày tốt ngày xấu.

Cũng thế, nhật cầu, nguyệt cầu và địa cầu đều là vô tri, chúng quay gần nhau
theo cái trục cố định, mặt địa cầu hướng về nhật cầu thì sáng, mặt khuất thì tối. Cái
trục quay ấy có khi địa cầu xê tới che khuất ánh sáng nhật cầu không soi đến nguyệt
cầu, có khi sụt lại, ánh sáng nhật cầu soi đầy đủ vào nguyệt cầu, ánh sáng nguyệt cầu
phản chiếu lại mặt tối của địa cầu. Thế rồi, con người sống trên địa cầu trông vào sự
sáng tối tùy khái niệm đặt thành ngày đêm và giờ phút, theo sự phản chiếu của nguyệt
cầu đặt ra rằm, ba mươi, thành tháng, năm. Thời gian là do tưởng tượng của con người
đặt ra không thật. Phương chi trên thế gian ấy lại còn đặt thêm lành dữ tốt xấu... Quả
thật con người quá bày biện, quá rối ren. Đã bày biện ra rồi, tự cột trói mình. Khi đã có
ngày tốt ngày xấu, đi đâu phải chọn ngày tốt mới dám đi, làm gì phải đợi ngày tốt mới
làm. Thậm chí cất nhà xây bếp cũng phải lựa ngày chọn tháng, định đôi gả lứa cũng
phải coi tuổi hạp, không hạp. Con người bị bao phủ trong ổ tơ rối nùi ấy, rồi than khóc
rồi khổ đau. Chính vì ngày tháng tuổi tác tạo ra cho con người không biết bao nhiêu
đau khổ. Chúng ta hãy nghe người nông dân miền Nam nguyền rủa họ qua bài hát:
    
<div class="align-center">
> Cọp mà vật mấy ông thầy địa  
> Yêu mà nhai mấy chú coi ngày  
> Trớ trêu họ khéo đặt bày  
> Hai đứa mình thương thiệt, ông trời rày bảo thương.  
</div>
  
### Coi tay, xem tướng {- #coi-tay-xem-tuong}

Coi tay, xem tướng cũng có khi trúng, song ông thầy ấy luôn luôn nói câu
thòng: *“Tay hay tướng của ông có hiện điều xấu, có thể đến tháng đó sẽ mắc nạn, nếu
ông biết làm lành làm phước có thể qua.”* Thế thì đến tháng đó, nếu người ấy mắc nạn
thì khen ông thầy xem trúng, bằng không mắc nạn thì ông thầy đổ tại làm lành làm
phước! Như thế, mặt nào ông thầy cũng hay hết. Nhưng chúng ta thử kiểm điểm xem,
cả hai mặt mắc nạn và không, có lợi gì cho người đi coi không? Nếu coi tay tốn một số
tiền, đến khi mắc nạn cũng phải tự chịu, ông thầy có cứu giúp cho mình được gì đâu.
Nếu đến tháng thọ nạn, người coi tay không thọ nạn, cho là làm lành làm phước được
qua thì mình tự cứu mình, ông thầy cũng không làm gì cho mình. Như vậy đi coi chi
cho uổng tiền.

Hơn nữa ở đầu quyển sách tướng có bài kệ:  
  
Hán:  

<div class="align-center">
> Hữu tâm vô tướng  
> Tướng tự tâm sanh  
> Hữu tướng vô tâm  
> Tướng tùng tâm diệt  
</div>
  
Dịch:  

<div class="align-center">
> Có tâm tốt không tướng tốt  
> Tướng tốt theo tâm tốt sanh  
> Có tướng tốt không tâm tốt  
> Tướng tốt theo tâm xấu mất  
</div>

Thế thì, chúng ta cần phát tâm tốt làm việc tốt thì điều tốt sẽ đến. Chúng ta chứa
chấp những tâm niệm xấu xa thì mọi điều dữ sẽ đến. Điều căn bản là chúng ta làm tốt
hay làm xấu, quả tốt xấu sẽ đến với chúng ta. Không phải quan trọng ở bàn tay hay
tướng mạo. Thế mà, chúng ta không ứng dụng ngay cội gốc, lại chạy theo ngọn ngành,
hao phí tiền bạc một cách vô ích, đó gọi là mê tín.

### Xin xăm, bói quẻ {- #xin-xam-boi-que}

Xin xăm bói quẻ là một việc làm cầu may. Rủi may là điều xảy ra không có
duyên cớ. Phó thác hành động của mình, cho đến phó thác cả đời mình vào chỗ không
có duyên cớ, thật là tệ hại. Thánh, Thần có rảnh đâu mà ngồi sẵn trên bàn để ứng hiện
trong xăm quẻ cho quí vị. Nếu người xin xăm bói quẻ có trúng, chẳng qua phước
nghiệp, lành dữ của mình mà hiện ra. Như sách nói: *“Phước chí tâm linh, họa lai thần
ám”*. Nghĩa là người gặp lúc phước đến thì giở quẻ ra đều tốt, khi họa lại thì rút lá xăm
nào cũng xấu. Thế là tốt xấu tại mình, không phải tại xăm quẻ. Chúng ta cứ sửa mình
cho tốt thì mọi việc đều tốt, đi xin xăm bói quẻ làm gì? Xin xăm bói quẻ chỉ khiến
chúng ta lo sợ thêm. Ca dao Việt Nam có câu:
<div class="align-center">
> Tay cầm tiền quý bo bo  
> Đem cho thầy bói mang lo vào mình  
</div>

Làm việc không lợi ích, lại tốn hao tiền bạc, mang lo sợ vào lòng, không phải
mê tín là gì?

### Cúng sao xem hướng {- #cung-sao-xem-huong}

Lệ cúng sao hạn, thật là lạc hậu lỗi thời, sao là những hành tinh cách xa chúng
ta bao nhiêu ngàn cây số. Nó là cái gì mà chúng ta phải cúng! Tục lệ các chùa quê, vào
ngày mùng chín tháng giêng là cúng sao Hội. Người Phật tử nào không gửi tên cúng
sao, xem như năm ấy không được bảo đảm an ninh. Song người chủ cúng sao cho quí
vị, có bảo đảm an ninh chưa? Có lẽ quí vị ấy quên ghi tên mình trong bài sớ cúng sao
chớ gì? Thật là vô lý, đạo lý nhân quả đức Phật dạy rành rành trong kinh, mà người ta
bất chấp. Thân tổng báo của chúng ta có lẫn lành với dữ, khi nhân lành đến thì hưởng
quả lành, khi nhân dữ đến thì chịu quả dữ, không thể chạy trốn được. Chỉ có tạo nhân
lành nhiều, khi quả dữ đến sẽ nhẹ đi hay giảm bớt. Ví như trước kia chúng ta đã làm
khổ một người, vì lúc đó họ thiếu khả năng trả thù nên dường như thông qua. Đến lúc
nào đó, họ đủ điều kiện trả thù, nếu chúng ta không được nhiều người thương che chở
thì, quả đó sẽ đúng với nhân kia. Ngược lại, nếu chúng ta được quá nhiều người ủng hộ
che chở, quả phải trả sẽ nhẹ hoặc giảm mất cũng có. Bởi thế nên, sợ quả khổ không gì
hơn, chúng ta phải tạo nhân vui. Không nên cúng sao cúng hạn để cầu được an vui là
điều phi lý.

Xem hướng cất nhà, xây bếp cũng là một lối mê tín. Có lắm người trong nhà
chồng vợ bất hòa, con cái ngỗ nghịch, liền rước thầy đến xem hướng sửa cửa, đổi bếp.
Nếu cửa và bếp biết nói, sẽ cãi lại với bà chủ nhà rằng: *“Cãi lẫy nhau tại ông bà không
biết nhường nhịn nhau, chúng tôi có tội lỗi gì mà phải dời chỗ này đổi chỗ kia?”*
Những việc làm này đủ nói lên người ta trốn tránh trách nhiệm, không bao giờ dám
nhìn thẳng những sái quấy lỗi lầm của mình, tìm cách đổ lỗi cho cái gì mà không thể
cãi lý được với họ. Như thế dù họ có sửa đổi trăm ngàn lần, lộn xộn vẫn lộn xộn, bất
an vẫn bất an. Vì cái chủ động trong việc bất an ấy, có chịu sửa đổi đâu. Thế nên,
người học đạo phải thấy rõ chỗ vô lý này, không nên lầm lẫn một cách tối dốt như vậy.

### Đốt giấy tiền vàng mã {- #dot-giay-tien-vang-ma}

Tục đốt giấy tiền vàng mã lại là việc vô lý trên vô lý. Không thể người có đôi
chút nhận xét, lý luận mà chấp nhận việc ấy được. Chính trên thế gian này, đồng tiền
của nước này mang sang nước khác còn khó được chấp nhận, huống là nhân gian in,
xuống âm phủ xài, có lý lẽ gì tin được. Những chiếc lầu bằng giấy, quần áo bằng giấy,
làm xong đốt gởi xuống âm phủ cho thân nhân dùng, quả là việc làm phí của vô ích.
Thử hỏi thân nhân họ là cái gì mà chờ đốt quần áo gởi xuống. Họ đều là đồ vô chủ cô
hồn hết sao? Hay họ đã theo nghiệp lành dữ mà sanh nơi khác? Nếu là Phật tử còn
không ai biết rõ Phật dạy: *“Chúng sanh tùy nghiệp thiện ác, theo đó thác sanh nơi cõi
lành cõi dữ”*. Thân nhân chúng ta chết cũng theo nghiệp thọ sanh, chớ đâu ngồi chờ
chúng ta gởi nhà cửa áo quần xuống xài. Như thế, việc làm ấy vừa trái đạo lý, vừa phí
tổn tiền bạc vô ích. Người Phật tử không bao giờ chấp nhận việc làm mù quáng ấy.

## Tai hại mê tín {- #tai-hai-me-tin}

### Quàng xiên khờ khạo {- #quang-xien-kho-khao}

Người mê tín theo quỉ thần là tin một cách quàng xiên không có căn cứ, không
có lý luận, tin bướng tin càn, mất hết lý trí, trở thành con người khờ khạo. Đó là hình
ảnh những người tin vào ông đồng bà bóng, xác cô xác cậu tạo nên. Tại sao họ như
thế? Bởi vì họ gởi gấm tâm hồn vào sự huyền bí, vào thế giới vô hình, họ mất hết trí
thông minh thực tế. Có khi họ gần như người điên nói lảm nhảm một mình, hoặc nói
những việc đâu đâu vô căn cứ...

### Bị cột trói, ích kỷ, tàn nhẫn {- #bi-cot-troi}

Người mê tín vào lịch số, ngày giờ, là kẻ bị cột trói một cách thảm hại. Họ
không bao giờ dám quyết định, một việc làm thích hợp với thời biểu hiện tại. Họ đợi
giờ lịch xem giờ tốt hay xấu, ngày lành hay dữ. Thế rồi họ bị chết khô trong cái rọ
ngày giờ. Bởi quen lựa ngày giờ tốt xấu, nên họ trở thành con người ích kỷ dễ sợ. Có
những việc đáng làm ngay lúc đó để giúp người, họ lại sợ giờ xấu rồi không chịu làm.
Cho đến việc ma chay cha mẹ, họ vẫn lựa ngày tốt, giờ tốt để lợi cho con cháu họ,
không nghĩ gì đến người chết. Có khi còn dùng thuật trấn ếm, nếu cha mẹ họ chết
nhằm ngày trùng. Thật là tàn nhẫn, họ không còn chút tình thương đối với người chết.
Mọi việc ma chay, chọn lựa ngày giờ, họ đều một bề vì họ. Những người ấy lúc nào họ
cũng nơm nớp lo sợ, trên đầu trên cổ họ đã cột sẵn trăm ngàn mối dây năm tháng ngày
giờ, không cho họ thong thả một phút giây nào.

### Khiếp nhược mất tự tín {- #khiep-nhuoc-mat-tu-tin}

Người tin vào bói xăm, sao hạn... là con người khiếp nhược mất tự tín. Bởi
không tự tín nên làm việc gì họ cũng phải đi hỏi thần, hỏi thánh. Họ lo âu, sợ hãi năm
nào gặp sao La Hầu, Kế Đô. Nhân lành họ không chịu tạo, nhân dữ không chịu tránh,
mà một bề sợ sao sợ hạn, quả là những con người mù mịt, tối tăm. Họ sợ những cái
không đáng sợ, họ cầu những điều không thể cầu, thật là oái ăm vô lý. Người Phật tử
thấy rõ lẽ tà chánh ấy, can đảm quăng đi những tệ tục sai lầm, mới có thể sống với tinh
thần đạo giác ngộ.

## Cầu nguyện là chánh tín hay mê tín? {- #cau-nguyen}

Trong nhà chùa mỗi khi tụng kinh, mọi Phật sự đều có cầu nguyện. Sự cầu
nguyện này là chánh tín hay mê tín? Câu hỏi này không thể trả lời một chiều, tùy chỗ
hiểu biết của mỗi người, sự cầu nguyện là mê tín, cũng là chánh tín.

### Mê tín {- #cau-nguyen-me-tin}

Nếu chúng ta khẳng định rằng mọi sự cầu nguyện đều được toại nguyện, đó là
mê tín. Vì sao? Bởi vì, nếu cầu nguyện mà được, thì không cần nói đến nhân quả
nghiệp báo. Nếu mọi sự kiện xảy ra đều do nhân quả thì sự cầu nguyện khó mà toại
nguyện. Bởi lẽ, thế gian có kẻ tạo nghiệp lành, người tạo nghiệp dữ. Người tạo nghiệp
lành khi phước báo đến thì được như nguyện. Kẻ tạo nghiệp dữ khi nghiệp báo đến, dù
có nguyện cầu cũng khó thoát khỏi quả khổ. Thế thì làm sao dám cố định cầu nguyện
là được như ý. Người chấp cố định, là sai lầm không hợp lý, nên thuộc mê tín.

### Chánh tín {- #cau-nguyen-chanh-tin}

Chúng ta chỉ xem cầu nguyện như những lời chúc lành là chánh tín. Vì quí kính
cha mẹ, quí kính người thân, chúng ta hằng cầu nguyện cho những vị ấy song có được
như nguyện hay không, còn tùy thuộc phước duyên dày mỏng của những vị ấy. Mặc
dù không được như nguyện, cũng nói lên được lòng hiếu thảo chân thành của chúng ta.
Cũng như vì hiếu kính những người trưởng thượng, những bạn bè thân hữu, đầu năm
mọi người chúc lành cho nhau. Những lời chúc lành này không hẳn thể hiện được,
nhưng cũng nói lên được lòng quí mến nhau.

Hơn nữa, người tu Phật cầu nguyện với mục đích phá tan tâm niệm vị kỷ của
mình. Bất cứ một Phật sự nào, chúng ta đều hồi hướng nguyện cầu cho tất cả chúng
sanh đều thành Phật đạo. Mới nghe qua dường như những lời nguyện suông, không thể
thực hiện được. Song trên tinh thần phá ngã, cứ lập tới, lập lui mãi tâm niệm vì tất cả
chúng sanh, khiến người ta quên bẵng bản ngã riêng tư của mình. Mọi việc làm đều
không phải vì mình, không được nghĩ lợi ích riêng cho mình, mà phải vì nhân loại, vì
tất cả chúng sanh. Hằng ngày cứ huân tập mãi tâm niệm này, đến một khi nào đó,
chúng ta không còn thấy bản ngã riêng, đồng hóa mình và chúng sanh không khác. Thế
là chúng ta phá được chấp ngã và phát tâm đại từ bi, xem mọi khổ vui của người như
của chính mình. Hiểu cầu nguyện và ứng dụng cầu nguyện như vậy, quả thật là chánh
tín.

## Chánh tín {- #chanh-tin}

### Tin nhân quả {- #tin-nhan-qua}

Đứng về chiều thời gian, vạn vật hiện có trong vũ trụ này, không một vật nào
thoát ngoài nhân quả mà được hình thành. Trên tiến trình sanh diệt, quyết hẳn vạn vật
từ nhân tiến đến quả, từ quả trở lại nhân. Nhân quả, quả nhân xoay vần không dứt. Đó
là hiện tuợng sanh hóa trên cõi nhân gian. Nghiệm xét thấu đáo, chúng ta không thấy
có một vật gì không nhân mà có, ngẫu nhiên mà thành. Thấy rõ lý nhân quả, chúng ta
khéo uyển chuyển cái xấu trở thành tốt, cái dở trở thành hay. Thấy rõ lý nhân quả,
chúng ta nắm chắc quyền tự chủ, tạo dựng tương lai tươi đẹp cho chính mình. Lý nhân
quả vừa là khoa học vừa là sức mạnh chuyển tiến của con người. Tìm hiểu tường tận lý
nhân quả là người thông minh. Biết ứng dụng lý nhân quả là con người tiến bộ. Khảo
sát theo nhân quả là lý luận chặt chẽ, là hiểu biết thấu đáo. Cho nên nghiệm xét lý nhân
quả tường tận rồi, chúng ta tin tưởng là chánh tín.

### Tin nhân duyên {- #tin-nhan-duyen}

Đứng về mặt không gian, vạn vật trong vũ trụ đều do nhân duyên hợp thành.
Không một vật nào do một đơn vị làm nên, mà phải nhiều đơn vị hợp lại mới thành
hình. Chính thế, lý nhân duyên thích ứng với tinh thần phân tích của khoa học hiện
nay. Nếu sự vật do một đơn vị làm nên thì còn gì phân tích. Bởi nhiều đơn vị hợp
thành một vật thể, người ta mới phân tích chia ra nhiều đơn vị, nhiều loại. Nhỏ nhất
như một nguyên tử, người ta phân tích trong đó vẫn có nhiều phần hợp thành, huống là
những vật thể to tát. Do đó, chúng ta thấy rõ lý nhân duyên nhà Phật nói, là một lẽ thật,
đúng với tinh thần khoa học hiện thời. Hiểu được lý nhân duyên, chúng ta phá tan cái
chấp lầm vô nhân và nhất nhân. Hiểu được lý nhân duyên, chúng ta thấy rõ muôn vật
trên thế gian có sự liên quan chằng chịt với nhau. Chúng ta không thể tách một cá thể
đứng ngoài tập thể, một cá nhân đứng ngoài nhân loại. Đây là lý do khiến dẹp được
quan niệm cá nhân ích kỷ. Chúng ta tích cực xây dựng nên hạnh phúc chung cho nhân
loại, không riêng của một cá nhân. Tin lý nhân duyên là tin bằng trí tuệ, bằng khoa
học, cho nên chánh tín.

## Lợi ích chánh tín {- #loi-ich-chanh-tin}

### Trí tuệ {- #loi-ich-tri-tue}

Nhận rõ lý nhân quả, lý nhân duyên là tác dụng của trí tuệ. Chính do nhận xét
thấu đáo, phân tích rành mạch, khiến trí tuệ càng ngày càng phát triển. Nếu một đối
tượng trước mắt, chúng ta cứ thầm nhận là tự nhiên nó có, do tạo hóa làm nên, thế là
còn gì phải nhận xét, phải phân tích. Cứ thế mãi, trí tuệ sẽ cùn mằn, không thể nào bén
nhạy được. Đó là cái cớ khiến người ta lười suy xét, lâu ngày trở thành tâm trí ù lỳ chai
cứng. Người Phật tử phải sống bằng trí tuệ, nên thấy rõ vạn vật sanh thành hoại diệt
đều nằm trong hệ thống nhân quả, nhân duyên. Sự vật hiện có mà không do nhân quả,
nhân duyên là phi lý luận, phản khoa học. Vì thế người chánh tín là người thực tế,
khoa học, nhận xét bằng trí tuệ.


### Chịu trách nhiệm {- #loi-ich-chiu-trach-nhiem}

Thâm đạt lý nhân quả nhân duyên, người ấy sẽ nhận lấy trách nhiệm nên hư,
hay dở, tốt xấu đều do mình. Mình là chủ động gây thành nhân tốt, tạo ra duyên lành.
Mọi việc đều không được tốt lành là do mình không chịu gây tạo, đây là lỗi tại mình
nào phải tại ai. Biết thế, chúng ta không trốn tránh, không kêu than, trái lại can đảm
chấp nhận để rồi xoay chuyển. Bởi nhận rõ nhân quả nhân duyên, chúng ta xét một sự
kiện xảy ra tốt xấu, phát xuất từ nhân nào, hội đủ nhân duyên gì mới xảy ra như thế.
Thế thì dù có việc dở việc hay, chúng ta đều thấy rõ không lầm. Chúng ta nỗ lực cố
gắng tạo điều kiện để chuyển đổi nó. Chịu trách nhiệm để chuyển đổi, không phải chịu
trách nhiệm để thông qua, đó là tinh thần của người chánh tín.

### Tự tín {- #loi-ich-tu-tin}

Biết rõ dở hay do mình, quả thật mình là chủ nhân của mọi thành bại. Đau khổ
an vui, chính mình là người tạo ra. Ngày mai tươi sáng, ngày mai tối tăm, ta là người
chủ động. Do thấu hiểu lý nhân quả nhân duyên, con người sẽ có sức tự tín mãnh liệt.
Nhờ sức tự tín, con người mới cố gắng chuyển đổi, vươn lên trong mọi lãnh vực. Một
dân tộc có đức tự tín, không bao giờ cam chịu khuất phục, chậm tiến. Có tự tín là có
một sức mạnh phi thường. Có tự tín, sự tu hành mới không thối chuyển.

## Kết luận {- #ket-luan-me-tin-chanh-tin}

Mê tín và chánh tín là hai con đường tối sáng khác nhau. Nếu đi bên tối là
không thấy bên sáng, nếu đi bên sáng thì không kẹt trong tối. Đạo Phật chủ trương
chánh tín, không bao giờ chấp nhận mê tín. Do vì người truyền đạo không thông lý
đạo, nên ghép những tập tục thế gian vào trong đạo, khiến người ta hiểu lầm đạo Phật
mê tín. Bản chất của đạo Phật là trí tuệ, là giác ngộ, làm sao dung nạp được mê tín.
Nếu người ta thấy trong chùa chiền hiện nay còn những hiện tượng mê tín, vội phê
bình đạo Phật mê tín. Đây là những oan tình của đạo Phật. Tất cả những kinh Phật
không có nói những việc mê tín ấy, chẳng qua một số người vì tùy tục, vì thiếu hiểu
Phật pháp vẽ bày ấy thôi. Người học Phật chân chánh phải gan dạ loại bỏ những tập
tục sai lầm ấy, can đảm dứt khoát đập tan mọi tệ đoan làm suy giảm giá trị Phật pháp.
Có khi dẹp bỏ những điều đó, có thể thiệt thòi chút ít quyền lợi của mình. Song chúng
ta cương quyết vì chánh pháp, chớ không vì lợi dưỡng, vì đưa người ra khỏi đường mê,
không vì sợ mất mát bản đạo. Được thế, chúng ta mới xứng đáng là người lãnh đạo tín
đồ, mới không hổ thẹn là hàng Tăng Bảo.
