
# Tội phước {- #toi-phuoc}

## Mở đề {- #mo-de-toi-phuoc}

Nói đến tu hành là nói đến tội phước, nếu không rõ tội phước tức là không rõ sự
tu hành. Nếu người tu mà cứ lao mình trong tội lỗi, ấy là người tạo tội chớ không phải
là người tu hành. Mọi sự an vui và đau khổ gốc từ tội phước mà sanh ra. Vì thế muốn
thấu hiểu sự tu hành chúng ta phải thấu hiểu tội phước. Tội phước là những hành động
thiết thực trong cuộc sống này, không phải là chuyện siêu huyền mờ ảo đâu đâu. Thế
nên người tu hành phải thấu đáo phải phân rành vấn đề tội phước.

## Thế nào là tội? {- #the-nao-la-toi}

Tội là hành động làm cho mình và người đau khổ trong hiện tại và vị lai. Người
làm tội cũng gọi là người dữ, người xấu. Tội, có tội ngoài đời và tội trong đạo. Tội
ngoài đời là những kẻ phạm luật pháp nhà nước, bị tù đày đau khổ. Tội trong đạo có
hai loại: tội do hứa nguyện gìn giữ mà không giữ, tội làm đau khổ chúng sanh. Tội do
hứa nguyện gìn giữ mà không giữ, như trước nhận giữ năm giới hoặc mười giới là điều
cao cả quí báu, ở trước Tam Bảo nguyện trọn đời gìn giữ, mà sau này không giữ được
một hoặc nhiều điều, gọi là tội phạm giới. Tại sao phạm giới gọi là tội? Bởi vì trước
mình đã nhận định những giới luật đó là hay là đúng, nếu giữ được sẽ lợi ích cho mình
và chúng sanh, nên nguyện gìn giữ. Sau này mình không gìn giữ, thế là đã phá hoại sự
lợi ích của mình và của chúng sanh nên phạm tội. Thí dụ như giới ăn trộm chẳng hạn.
Bất cứ một hành động nào làm khổ cho người hiện tại hoặc mai kia đều là tội. Bởi vì
mình đã gây ra nhân đau khổ thì quả đau khổ mình phải lãnh lấy. Do làm khổ mình
khổ người nên gọi là tội. Tội có tội nhẹ và tội nặng.

### Tội nhẹ {- #toi-nhe}

Những điều làm đau khổ cho người cho chúng sanh do thân miệng chúng ta gây
ra mà không cộng tác với ý là tội nhẹ. Bởi vì việc làm ấy là vô tâm, hoặc không có ý
thức. Việc làm vô tâm, khi nạn nhân cảm thông được, họ sẽ bớt thù hận, nếu họ đại
lượng có thể tha thứ luôn. Thí dụ chúng ta đi đường, có đứa bé cầm hòn đất ném chơi,
lại trúng vào chúng ta. Nếu chúng ta biết nó không có ý ném mình, tuy đau điếng mà
chúng ta không giận nó. Thế nên mọi hành động bằng thân bằng miệng làm đau khổ
cho người mà không có ý thức là tội nhẹ, xin lỗi hoặc sám hối sẽ hết. Việc làm đau
khổ chúng sanh chút ít cũng là tội nhẹ.

### Tội nặng {- #toi-nang}

Những điều làm đau khổ cho người cho chúng sanh do thân miệng cộng tác với
ý chúng ta gây ra là tội nặng.

Bởi vì việc làm ấy là có cố tâm, có hữu ý, khiến người oán giận không thể tha
thứ. Thí dụ như có người cố tình đánh chúng ta, dù cái đánh ấy bị cản trở không chạm
đến thân chúng ta song biết kẻ ấy cố tình đánh mình, chúng ta cũng giận họ đời đời. Vì
thế hành động cố tâm, hữu ý là hành động quan trọng nên tạo thành tội nặng.

Thế nên tội phát xuất từ ba nghiệp chúng ta. Nơi thân: giết người, trộm cướp, tà
dâm. Nơi miệng: nói dối, nói hai lưỡi, nói thêu dệt, nói hung ác. Nơi ý: tham, sân và tà kiến. Sự hợp tác chặt chẽ của ba nghiệp này là tội nặng.

## Thế nào là phước? {- #the-nao-la-phuoc}

Phước là những hành động đem lại sự an vui cho mình, cho người ở hiện tại và
mai kia. Người làm phước cũng gọi là người lành, người tốt. Bởi vì những hành động
đem lại sự an vui cho người, người sẽ quí mến. Chính sự quí mến ấy nên gặp nhau vui
vẻ và sẵn sàng giúp đỡ nhau. Chúng ta giúp đỡ hoặc an ủi khiến người được an vui,
người thù đáp lại chúng ta bằng cử chỉ biết ơn vui vẻ quí mến, đó là làm phước gặp
phước. Vì thế người biết làm phước hiện tại được an vui, mai sau vẫn an vui. Làm
phước có hai thứ: phước hữu lậu và phước vô lậu.

### Phước hữu lậu {- #phuoc-huu-lau}

Làm cho mình cho người an vui tương đối trong vòng sanh tử là phước hữu lậu.
Do ba nghiệp chúng ta hoạt động đem lại sự an vui cho người, chính hành vi ấy là sanh
diệt giới hạn, còn trong vòng sanh tử hiện tại cũng như mai sau. Chúng ta phải nỗ lực
tạo điều kiện cho mình và mọi người thường được an vui. Muốn thực hiện được việc
đó, ngay nơi ba nghiệp chúng ta phải ứng dụng các điều này:

#### Về thân {- #phuoc-ve-than}

- Cứu mạng:  
Chúng ta phải sẵn sàng cứu giúp bảo vệ sanh mạng người.
Nếu người gặp tai nạn sắp mất mạng, theo khả năng mình, chúng ta tận tâm cứu giúp.
Giải cứu cho người thoát chết, hoặc ngừa đón những sự việc có thể làm nguy hiểm đến
sanh mạng người, đó là việc làm phước của thân. Bởi vì sanh mạng đối với con người
là tối thượng, cho nên ai giải cứu khỏi chết, là an vui và biết ơn vô kể.

- Bố thí:  
Kế đến, sẵn sàng cứu giúp người khi gặp cảnh cơ hàn nguy
khốn. Nỗi khổ đói rét cũng đe dọa đến sanh mạng, người đang lâm vào cảnh khổ này,
nếu được cứu giúp, họ cũng vui mừng vô hạn. Chúng ta muốn được an vui thì phải sẵn
sàng mang sự an vui bủa khắp mọi người, đó là nền tảng phước đức. Hạnh phúc không
phải đến riêng với chúng ta, mà do sự thù đáp từ hạnh phúc của mọi người mang lại.
Chúng ta đừng dại khờ cứ bo bo giữ lấy tài sản vô thường làm của riêng mình, cần
phải ban bố cho những người đang thiết tha cần nó. Những cái vô thường mà cứ giữ,
có ngày sẽ khổ đau khi nó không còn ở trong tầm tay mình nữa. Mượn của cải vô
thường làm phương tiện an vui cho người, nguồn an vui ấy sẽ trở về với chúng ta một
cách bền vững lâu dài.

- Trinh bạch:  
Cần phải giữ hạnh trung thành trinh bạch. Người biết đạo
lý đã không dám xâm phạm đến danh giá và hạnh phúc của gia đình người, còn phải
trung thành trinh bạch với gia đình mình. Tinh thần trung trinh ấy giúp cho người
trong gia đình tín cẩn lẫn nhau. Do sự tín cẩn nhau nên trong gia đình được sự an ổn
vui tươi. Trong gia đình đã thế, chúng ta cần nhắc nhở chỉ dạy cho mọi người chung
quanh đều tập hạnh trung trinh này. Được thế, sự an vui không những chỉ ở trong
phạm vi gia đình, mà tràn lẫn đến xã hội.

#### Về miệng {- #phuoc-ve-mieng}

Tu phước ở miệng phải tập bốn điều này:

- Nói chân thật:  
Nói chân thật để đem lại niềm tin tưởng an ổn cho
người. Bất cứ ở trường hợp nào, chúng ta cũng cố gắng nói lên những lẽ thật. Luôn
luôn tôn trọng và yêu chuộng lẽ thật, cho nên phát ngôn lúc nào cũng hợp với sự thật.
Chân thật là nguồn gốc tin yêu nhau, do đó mọi sự mến thương được bền bỉ.

- Nói đúng lý:  
Nói đúng lý để giúp mọi người nhận được lẽ chánh.
Trong cuộc sống phức tạp này khiến mọi người khó tìm được con đường chánh. Cho
nên chúng ta cố gắng nói ra lời đúng lý, hầu làm sáng tỏ mọi chỗ ngờ vực của người.
Sống đúng, nói đúng, thật là sự hi hữu trong cuộc đời hỗn độn hiện nay. Chúng ta mãi
tôn trọng câu *“mặc người phi pháp, chúng ta vẫn giữ đúng pháp”*.

- Nói hòa thuận:  
Nói hòa thuận để đem lại tình đoàn kết cho mọi người.
Tất cả việc làm phân ly chia rẽ đều là tạo nên thống khổ cho con người. Chúng ta đã
không làm thế, mà luôn luôn dùng lời hòa thuận để hàn gắn lại những mối tình đã rạn
nứt. Ngôn ngữ chúng ta phát ra đều đem lại tình thương gắn bó cho mọi người. Thấy
đâu có sự rạn nứt, có mầm tan rã, chúng ta đều nỗ lực dùng lời hòa thuận là chất keo
hàn gắn lại. Tận dụng ngôn ngữ mình để đem lại tình đoàn kết an vui cho nhân loại.

- Nói nhã nhặn:  
Nói nhã nhặn để đem lại sự ôn hòa vui vẻ cho người.
Mọi sự căm phẫn, bực tức đều làm cho người đau khổ. Chúng ta tập nói nhã nhặn là
làm dịu mọi sự bực dọc của người. Lời nói nhã nhặn khiến người dễ mến và vui vẻ.
Trọn đời chúng ta đem lại sự an vui cho chúng sanh, không có lý do nào lại dùng lời
thô ác. Chúng ta phải thực hiện lời nhã nhặn mãi mãi với mọi người.

#### Về ý {- #phuoc-ve-y}

Chúng ta phải tập từ bi, nhẫn nhục và chánh kiến. Mang lại tình thương cho
chúng sanh là tiêu diệt mầm tham lam độc ác. Nỗi khổ của chúng sanh ngập trời đều
do lòng tham ác của con người tạo nên. Chúng ta tận lực gây dựng tình thương để
giảm thiểu đau khổ cho chúng sanh. Tập lòng nhẫn nhục để chịu đựng mọi cảnh ngang
trái mà không sanh sân hận. Có nhẫn nhục được, chúng ta mới giữ được tình thương
lâu dài với chúng sanh. Chánh kiến là nhận định đúng đắn, đưa chúng ta đi đúng
hướng, sáng suốt vui tươi. Do chánh kiến mới có nói đúng, làm đúng. Ba nghiệp tạo
phước, chánh kiến là đội binh tiên phong. Tóm lại, ba nghiệp làm mười điều trên là tu
phước hữu lậu. Phước này khiến chúng ta qua lại trên con đường an vui tươi đẹp. Mặc
dù còn tương đối sanh tử, song đến đâu cũng là hài lòng mãn ý.

### Phước vô lậu {- #phuoc-vo-lau}

Phước vô lậu là sự an vui tuyệt đối không giới hạn. Do thoát ly sanh tử nên an
vui miên viễn. Bởi sự an vui nào mà còn sanh tử đều tạm bợ đối đãi. Chỉ có tiêu diệt
hết mầm sanh tử, an trụ vô sanh, mới là an vui viên mãn. Tu phước vô lậu là chúng ta
nhắm hướng vô sanh làm mục đích, hàng ngày buông xả cái chủ động sanh diệt và
dùng trí thấy rõ các tướng giả dối sanh diệt, không lầm, không kẹt nó. Cứ thế tiến mãi,
cho đến bao giờ viên mãn mới thôi. Mình làm như vậy, chỉ dạy người làm như vậy là
tu phước vô lậu.

## Cần tránh tội làm phước {- #can-tranh-toi-lam-phuoc}

### Tránh tội {- #tranh-toi}

Đã biết tội là nhân khổ đau bất như ý, chúng ta cố gắng tránh đừng gây nên tội.
Cuộc đời đã khổ đau lắm rồi, chúng ta không thể làm cho nó tươi đẹp, ít ra cũng đừng
tô thêm cho đậm nét khổ đau. Tránh gây khổ đau cho người tức là tránh tạo khổ cho
mình. Có ai ngu dại đến nỗi lấy dây tự trói, lấy roi tự đánh, để rồi kêu khóc thở than.
Mầm khổ đau không gieo thì cây khổ đau làm sao đâm chồi nảy lộc. Biết thế, chúng ta
dè dặt tối đa trong việc gieo nhân đau khổ. Dù một tội nhỏ, tránh được, chúng ta cũng
cố gắng tránh. Như trong Luật nói: *“Giọt nước tuy nhỏ, rơi mãi cũng đầy chậu lớn”*.
Người biết sợ tội là người sẽ khỏi tội. Chỉ có kẻ liều mạng xem thường tội lỗi, càng lún
sâu trong tội lỗi. Đã có tội lỗi là có khổ đau, như có hình thì có bóng, có tiếng thì có
vang. Người học đạo phải sáng suốt thấy rõ lý lẽ ấy, để không lầm, làm khổ mình khổ
người.

### Làm phước {- #lam-phuoc}

Hạnh phúc an vui là điều ai cũng ước mơ, mong mỏi. Người học đạo không ước
mơ mong mỏi suông, phải thực tế gầy dựng hạnh phúc cho người tức là gầy dựng hạnh
phúc cho mình. Hạnh phúc không thể ngẫu nhiên đến với chúng ta, mà do công phu
bồi đắp. Một hành động, một lời nói, một ý nhiệm mầu đem an vui lại cho người,
chính là gây dựng hạnh phúc cho ta. Trong cuộc đời tương phản, kẻ buông xả hết lại là
người được nhiều nhất. Ngược lại, người cố giữ gìn lại là người mất mát nhất. Tạo
hạnh phúc cho mình, không phải bo bo gìn giữ những cái gì của mình mà phải xả bỏ
cái của mình, tạo cho người an vui. Chúng ta làm cho trăm ngàn người an vui, quả
thực đã tạo trăm ngàn điều an vui cho chúng ta. Vì thế làm phước không bao giờ thấy
đủ, chúng ta làm mãi đến suốt đời, mà vẫn thấy chưa xong. Có một lần đức Phật đang
ngồi trong một tịnh xá, ở phòng khác ngài A-na-luật đang xỏ kim vá y, vì mắt không
tỏ, Ngài xỏ hoài mà chẳng được. Ngài buột miệng than: *“Có ai mắt sáng làm phước xỏ
kim hộ tôi”*. Đức Phật nghe, Ngài đi đến chỗ A-na-luật bảo: *“A-na-luật! Đưa kim ta xỏ
hộ”*. Thế Tôn đầy đủ vô lượng phước đức, mà còn mót từ cái phước xỏ kim. Thử hỏi
chúng ta là người gì mà không cố gắng làm phước? Phước càng to thì an vui càng lắm,
có thiệt thòi gì đâu mà không chịu làm!

## Kết luận {- #ket-luan-toi-phuoc}

Tội phước là điều thực tế trên cõi nhân gian. Cổ động khuyến khích người tránh
tội là hành động giảm thiểu khổ đau cho nhân loại. Tán thán ca ngợi làm phước là
mang lại hạnh phúc an vui cho chúng sanh. Lý đáng mọi người chúng ta đều tận lực
làm điều này. Vô lý những kẻ đã không làm, lại công kích người khác làm. Còn ai
không xót xa khi thấy con người sát phạt con người. Người có lương tâm, đầy lòng
trắc ẩn không thể ngó lơ trước huynh đệ tương tàn. Cho nên tránh tội làm phước là
điều mỗi con người chúng ta phải ứng dụng. Biết tội phước là cội nguồn của đạo đức.
Song chúng ta đừng bị phỉnh gạt bằng những tội phước rỗng. Tội là cấy mầm đau khổ
nơi con người, phước là gieo hạt hạnh phúc cho chúng sanh. Thực tế như vậy, không
phải việc huyễn hoặc viễn vông.
