

# Pháp tu căn bản của Phật tử *(Phật pháp hóa nhân gian)* {- #phap-tu-can-ban-cua-phat-tu}

Đa số người xưng là Phật tử mà không biết rõ đường lối tu hành, ai bày sao làm
vậy, trở thành mê tín sai lầm, khiến người đời phê bình đạo Phật là huyền hoặc, là vô
ích. Để bổ cứu những sai lầm ấy, chúng ta phải biết rõ đâu là pháp tu căn bản phải
hành, đâu là lối tu siêu thoát phải đến. Ứng dụng Phật pháp ngay trong cuộc sống thực
tế của chúng ta, để minh chứng rõ ràng đạo Phật cứu khổ thật sự, đạo Phật mang hạnh
phúc cụ thể lại cho con người. Được thế, chúng ta mới khỏi hối hận là đệ tử của Phật
mà làm nhục nhã cho đạo Phật.

## Pháp tu căn bản {- #phap-tu-can-ban}

Bước đầu trên đường tu hành của người Phật tử, phải “*chuyển ba nghiệp ác
thành ba nghiệp lành”*. Ba nghiệp là thân miệng ý của chúng ta. Khi xưa chưa biết tu,
chúng ta buông lung thân miệng ý làm những việc xấu xa tàn bạo độc ác. Đã tạo những
điều xấu xa tàn bạo độc ác là làm đau khổ cho mình, cho người, cho gia đình, cho xã
hội. Những kẻ cướp của giết người sớm muộn gì cũng ngồi khám, cha mẹ vợ con ở
nhà đau khổ, gia đình của nạn nhân cũng khổ đau, chánh quyền cũng phải bận tâm
điều tra truy nã. Chỉ một việc làm cuồng dại độc ác của một vài người, khiến guồng
máy xã hội bị rối bời. Hành động ấy gọi là tạo nghiệp ác. Ngày nay biết tu, chúng ta
chuyển thân miệng ý làm việc tốt đẹp thanh cao hiền thiện. Thấy người trên đường bị
tai nạn xe cộ, mà không có thân nhân, chúng ta thành thật xót thương, dùng lời hiền
hòa an ủi, đích thân săn sóc chở đến bệnh viện... đây là tạo nghiệp lành. Làm được
việc lành bản thân chúng ta đã vui, người bị tai nạn cũng bớt khổ, người chung quanh
trông thấy cũng tán thành. Hành động lành này là cụ thể xây dựng xã hội tốt đẹp. Hành
động xấu mà cứ lặp đi lặp lại mãi là nghiệp ác, vì đã thành thói quen khó sửa đổi. Ví
như người uống rượu, uống một vài lần không thành ghiền *(nghiện)*, ngày nay uống
ngày mai uống, uống nhiều ngày như vậy thành người ghiền rượu. Cái ghiền là thói
quen, gọi là nghiệp. Người thấy ai thiếu thốn liền giúp đỡ, lúc nào cũng thế, lâu ngày
thành thói quen là nghiệp lành. Cũng là thói quen, một thói quen đưa đến đau khổ, một
thói quen khiến đến an lạc. Vì thế, người Phật tử phải tránh thói quen đau khổ, phải tạo
thói quen an lạc, đó là tu chuyển nghiệp ác thành nghiệp lành. Kẻ ngu muội mới tìm
hạnh phúc trên đau khổ của người khác, người sáng suốt chỉ thấy hạnh phúc khi giúp
người khác hết khổ.

## Quan niệm sai lầm {- #quan-niem-sai-lam}

Có nhiều Phật tử phát tâm qui y chỉ vì cầu cho gia đình bình an, cuộc sống được
mọi sự như ý. Vì thế, gia đình có người bệnh hoạn hay xảy ra tai nạn gì thì thỉnh thầy
cầu an. Nếu thầy bận việc không đi thì phiền não, giận không đi chùa. Trong cuộc sống
gặp nhiều điều bất như ý thì buồn, cho rằng Phật không hộ độ. Nghe miếu Bà, miếu
Ông nào linh ứng liền đến đó cầu xin. Chỉ vì mong được bình an mà đi chùa, đến với
đạo, khi mục đích ấy không thành thì họ bỏ đạo dễ dàng. Lại có những người sau khi
qui y rồi thì mọi việc đều giao phó cho thầy, cất nhà cũng thỉnh thầy coi ngày, gả cưới
con cái cũng thỉnh thầy xem tuổi, đau ốm bệnh hoạn cũng thỉnh thầy cầu an, ma chay
cũng thỉnh thầy cầu siêu. Thầy là người chịu mọi trọng trách trong gia đình, nếu thầy
không chiều theo là buồn, không đi chùa. Lối qui y này, giống hệt đi đóng tiền bảo
hiểm cho cá nhân và gia đình vậy.

Lại có những người tu một cách hời hợt, chỉ biết giờ tụng kinh, giờ niệm Phật,
ngày ăn chay là tu. Ngoài những giờ đó ra, mọi việc đều như ai, ăn miếng trả miếng
không thua kém. Một ngày mười hai giờ, chúng ta chỉ tu có một hai giờ, làm sao đủ?
Mười giờ tạo ác, hai giờ tu thiện thì quá ít oi. Hoặc một tháng ăn sáu ngày chay, chỉ tu
trong sáu ngày này, còn hai mươi bốn ngày kia không tu thì có thấm vào đâu. Có khi ai
lỡ xúc phạm đến họ trong những ngày chay, họ sẽ nói *“hôm nay tôi ăn chay, nếu
không ăn chay thì biết!”*. Tu như thế, quả thật rất hời hợt.

Còn tệ hại hơn, có người sợ tu thiền đổ nghiệp. Mỗi khi phát nguyện tụng kinh
Pháp Hoa chẳng hạn, ở gia đình có xảy ra tai biến gì, liền đổ thừa tại tụng kinh đổ
nghiệp. Không biết đổ nghiệp là rơi rớt hết hay sanh ra nghiệp? Nếu đổ nghiệp là rơi
rớt hết thì cố gắng tụng cho nó rớt sạch luôn. Nếu đổ nghiệp là sanh ra nghiệp thì điều
này thật là vô lý. Vì giờ tụng kinh thì ba nghiệp thanh tịnh - thân nghiêm trang là thân
nghiệp thanh tịnh miệng tụng lời Phật là khẩu nghiệp thanh tịnh - ý duyên theo lời kinh
là ý nghiệp thanh tịnh - làm sao sanh ra ác nghiệp được? Tin như thế thật là hoàn toàn
vô căn cứ. Người Phật tử phải sáng suốt không nên tin theo lối nhảm nhí ấy.

## Tu là tuyên chiến với ma quân {- #tu-la-tuyen-chien-voi-ma-quan}

Người phát tâm tu hành như một chiến sĩ tuyên chiến với ma quân. Chúng ta
phải hùng dũng quyết chiến. Trước tiên, chúng ta chiến đấu với bọn ma phiền não
nghiệp chướng của mình. Ví như người vừa phát nguyện tu hạnh nhẫn nhục, liền bị
người thóa mạ, tâm sân hận nổi lên, ngay đây phải dẹp bỏ, đè bẹp nó là thắng, để nó
phát hiện ra miệng, ra thân là thua. Có người trước đã ghiền *(nghiện)* rượu, nay phát
tâm qui y thọ trì năm giới ngang đây phải bỏ *(cai)* rượu, nếu can đảm bỏ được là thắng,
bỏ không được là thua. Thắng được cơn giận dữ nổi lên là thắng ma phiền não, thắng
được bệnh ghiền lâu năm là thắng ma nghiệp chướng. Phiền não nghiệp chướng của
chúng ta rất nhiều rất nặng, chiến thắng được nó phải là một dũng sĩ kiên cường. Hai
thứ này là nội ma.

Những khó khăn chướng ngại do ngoại cảnh gây nên là ngoại ma. Một người
tuổi độ ba mươi, đã có gia đình, vừa thọ ngũ giới xong, liền có một người đẹp đeo đuổi
mến yêu. Chiến thắng tình cảm bất hợp pháp này là một trận chiến gay go, nếu đương
sự không can đảm quyết liệt, khó mà giữ toàn vẹn được giới thứ ba đã thọ. Một người
khác sau khi qui y thọ giới rồi, nguyện bỏ *(cai)* rượu, trong lúc tranh đấu một mất một
còn với con ma ghiền, lại gặp bạn bè mời đi nhậu, còn dùng nhiều thủ thuật bắt ép,
trường hợp này không phải là người có ý chí kiên cường thì khó mà thắng được, ngoại
cảnh chướng ngại nhiều khó thể kể hết, người Phật tử hùng dũng quyết thắng, đừng để
giặc ngoại ma áp đảo phải đầu hàng.

Đã là chiến đấu thì phải đương đầu, vì vậy chúng ta không thể khiếp nhược yếu
hèn chỉ một bề cầu được bình an. Người chiến sĩ có đối đầu với giặc, chiến thắng được
giặc, mới thăng quan tiến chức, mới có ngày ca khúc khải hoàn, quàng vòng hoa danh
dự vào cổ. Người tu cũng vậy, chiến thắng được nội ma, ngoại ma, mới có ngày bước
lên đài vinh quang của con người vẹn toàn đức hạnh. Đã là chiến sĩ thì mắt phải sáng,
tai phải thính luôn luôn theo dõi mọi hành động của kẻ thù. Một phút giây hời hợt sơ
suất có thể tán thân mất mạng. Người tu cũng thế, phải thấy rõ từng tâm niệm, từng
hành động của mình, một phút giây lơi lỏng, bọn giặc phiền não nổi dậy, phải bị mất
giới thân tuệ mạng. Do đó, không thể chỉ tu trong giờ tụng kinh, niệm Phật, ăn chay
mà phải tu trong mọi lúc mọi giờ. Được vậy mới mong chiến thắng bọn ma quân.

Tu là dẹp bỏ những thói hư tật xấu, tuổi trẻ chưa tập nhiễm những cái dở ấy,
ngang đây biết tu thì dễ biết dường nào. Người chưa biết uống rượu, không tập uống
rượu thật là dễ. Người đã ghiền rượu, bỏ không uống rượu là thiên nan vạn nan. Biết tu
từ thuở nhỏ thì thuận lợi dễ dàng biết mấy, để đa mang nhiều bệnh nhiều tật rồi mới tu,
thật là khó khăn trăm bề. Song người có ý chí mãnh liệt thì cái khó nào cũng làm được.

## Cụ thể hóa pháp tu căn bản {- #cu-the-hoa-phap-tu-can-ban}

Để cụ thể hóa pháp tu căn bản này, đức Phật bắt buộc người Phật tử sau khi qui
y Tam Bảo phải thọ trì năm giới. Trong năm giới ba giới đầu là giữ thân không tạo
nghiệp ác, hai giới sau giữ khẩu không tạo nghiệp ác. Thế là, người Phật tử chỉ mới
chuyển hai nghiệp. Chuyển hai nghiệp thôi, mà công hiệu lợi ích đã to lớn lắm rồi.
Như người không sát sanh, là không giết người *(chỉ trừ trường hợp nghĩa vụ quân sự)*,
không trộm cướp, không tà dâm, không nói dối, không uống rượu, bản thân họ đã là
một con người tốt. Họ lại giảm được bao nhiêu việc lo âu sợ sệt tốn hao trong cuộc
sống hiện tại. Cha mẹ anh em vợ chồng con cái nhờ đó được an ổn vui tươi. Mọi người
trong xã hội khỏi phải phiền hà lo âu vì họ. Chúng ta có thể hình dung trong một xóm,
mà mọi người đều giữ năm giới hết, trong xóm đó có xảy ra chuyện giết hại, trộm
cướp, lừa đảo, hiếp dâm và say sưa phá làng phá xóm không? Chắc hẳn là không, trừ
phi những kẻ khác xâm nhập vào. Chúng ta hiện nay đi đâu cũng lo âu sợ sệt là tại
sao? Phải chăng, vì sợ người hãm hại, sợ người móc túi giựt đồ, sợ người lường gạt...
Chánh quyền phải bận tâm nhọc sức điều tra theo dõi, vì dân chúng không biết tu. Nếu
người dân biết tu và chịu tu như vậy, chánh quyền sẽ thảnh thơi nhàn rỗi biết chừng
nào. Bởi vì con người ai cũng có sẵn những thói xấu, nếu không cấm đoán hạn chế, nó
sẽ tạo ra lắm chuyện xấu xa hèn hạ khổ đau cho nhau. Vì lòng từ bi, đức Phật như bắt
buộc các đệ tử của Ngài phải tuân theo những điều cấm đoán, nhờ đó sẽ dẹp bớt những
thói xấu, nết tốt dần dần tăng trưởng, khổ đau sẽ tiêu mòn, an vui thêm lớn. Đây là chủ
đích cứu khổ của đạo Phật.

Để thành một con người hoàn hảo hơn, Phật dạy phải tu Thập thiện. Pháp Thập
thiện mới thật sự đầy đủ tu chuyển ba nghiệp. Chuyển ba nghiệp ác của thân, không sát
sanh, không trộm cướp, không tà dâm. Chuyển bốn nghiệp ác của khẩu: không nói dối,
không nói lật lọng *(ly gián)*, không nói hung ác, không nói vô nghĩa *(thêu dệt)*, chuyển
ba nghiệp ác của ý: bớt tham, bớt sân, không tà kiến *(chấp lệch, sai)*. Mười điều lành
này xây dựng một con người toàn hảo. Chúng ta phân tích từ tế đến thô sẽ thấy pháp
Thập thiện công hiệu không thể kể hết. Một con người không bị tham lam xúi giục thì
sẽ làm chủ mình trước mọi thứ cám dỗ của trần gian. Tài sắc danh lợi không lung lạc
được, người này mới hoàn toàn thanh bạch cao thượng. Không bị nóng giận áp đảo,
chúng ta mới bình tĩnh sáng suốt giải quyết mọi vấn đề. Làm chủ được nóng giận,
chúng ta không nói lời thô ác, không có hành động tàn nhẫn. Đời chúng ta không bị
hối hận bao giờ, người thân chúng ta không hề chán ghét. Sự việc xảy đến, giải quyết
một cách sáng suốt khôn ngoan chúng ta mới đủ khả năng đảm đang việc lớn được.
Mọi lý thuyết, mọi vấn đề, chúng ta không thấy một chiều, không nhìn phiến diện,
quần chúng mới dễ cảm thông, mới thật lòng yêu mến. Tà kiến là cái thấy lệch lạc,
thấy sai lầm cục bộ, dễ sanh tranh cãi, dễ sanh oán hờn. Không tà kiến là một tâm hồn
cởi mở, bao dung, suốt thông, trong sáng. Không tà kiến, chúng ta hòa hợp được mọi
người, mọi chánh kiến khác nhau. Cuộc sống hạnh phúc hay khổ đau, nẩy mầm từ
thông cảm nhau hay chống đối nhau. Không tà kiến mà lại có chánh kiến, thật hạnh
phúc thay cho kiếp con người. Thân khẩu trở thành hay hoặc dở đều phát nguồn từ ý
tốt hay xấu. Sở dĩ Thập thiện xây dựng con người hoàn hảo là chú trọng đến ý nghiệp.
Pháp ngũ giới mới chuyển hóa hai phần nổi, thân khẩu mà thôi. Bởi vậy Phật tử chúng
ta không phải chỉ dừng ở Ngũ giới mà phải tiến lên Thập thiện mới thật đầy đủ.

## Tu chuyển ba nghiệp là căn bản Phật pháp {- #tu-chuyen-ba-nghiep-la-can-ban-phat-phap}

Đời Đường ở Trung Hoa, có một Thiền sư thấy trên cây có chỗ thuận tiện ngồi
tu được, ông liền gác cây bẻ nhánh lót thành chỗ ngồi, giống như ổ quạ và ngồi đó tu.
Thời gian sau, ông ngộ đạo tại đây, dân chúng gọi Ngài là Ô Sào Thiền sư *(Thiền sư
ngồi trong ổ quạ)*. Ông Bạch Cư Dị, nhà văn nổi tiếng thời ấy, được cử làm quan ở
huyện này, nghe danh tiếng Thiền sư Ô Sào, ông liền đến hỏi đạo. Khi gặp nhau, ông
hỏi nhiều câu, câu chót: *“Thế nào là đại ý Phật pháp?”*. Thiền sư Ô Sào ngồi trên ổ quạ
đáp: *“Chư ác mạc tác, chúng thiện phụng hành, tự tịnh kỳ ý, thị chư Phật giáo.”* *(Chớ
tạo các điều ác, vâng làm mọi việc lành, giữ tâm ý trong sạch, đây lời dạy chư Phật)*.
Ông Bạch Cư Dị cười thưa: *“Bài kệ Ngài dạy, con nít tám tuổi cũng thuộc rồi”*. Thiền
sư bảo: *“Phải, con nít tám tuổi cũng thuộc, song ông già tám mươi làm chưa xong”*.
Bạch Cư Dị đảnh lễ rồi lui về.

Qua câu chuyện này, chúng ta thấy cốt yếu của đạo Phật là dạy Phật tử phải
chuyển ba nghiệp ác thành ba nghiệp thiện. *“Chớ tạo các điều ác”* là dừng ba nghiệp
ác. *“Vâng làm mọi việc lành”* là tu ba nghiệp lành. *“Giữ tâm ý thanh tịnh”* phải chú
tâm nhiều về ý nghiệp. Ý nghiệp thanh tịnh thì thân khẩu mới tốt, mới thanh tịnh. Ý
nghiệp là chủ động, nên dành riêng một câu để thấy tầm vóc quan trọng của nó. Dạy tu
chuyển ba nghiệp thanh tịnh này, không phải chỉ riêng Phật Thích-ca dạy mà chư Phật
đều dạy như thế, *“đây lời dạy chư Phật”*. Còn một điểm quan trọng chúng ta phải chú
ý, Bạch Cư Dị nghe bài kệ này thấy dễ nhớ dễ hiểu nên xem thường bảo rằng *“con nít
tám tuổi cũng thuộc”*. Thiền sư giáng cho ông một đòn đau điếng bằng câu, *“con nít
tám tuổi cũng thuộc, song ông già tám mươi làm chưa xong”*. Đạo là để hành để tu chớ
không phải hiểu nhớ suông. Nếu hỏi đạo để hiểu nhớ, chỉ là việc đùa cợt vô ích. Ứng
dụng lời Phật dạy vào cuộc sống, mới thấy hữu ích thật sự. Dầu một thứ thuốc hay đến
đâu, nếu người ta chỉ biết tên, đọc nhãn hiệu, nghiên cứu công thức, mà không chịu
uống thì con bệnh không bao giờ lành. Phật tử chịu thực hành lời Phật dạy, như con
bệnh chịu uống thuốc, mọi bệnh khổ không còn đeo bám chúng ta. Học Phật pháp để
hiểu để nói, như người khoe ăn nhiều thứ bánh vẽ, mà bụng vẫn đói. Người học đạo để
hành, để tu mới thật chân chánh Phật tử.

Kết thúc bài này, chúng ta thấy trọng tâm chủ yếu đạo Phật dạy “*chuyển hóa ba
nghiệp ác thành ba nghiệp thiện”*, là căn bản bước đầu không thể thiếu, ở mỗi người
Phật tử. Mỗi người hoàn thiện thì xã hội mới toàn mỹ. Chúng ta tu chuyển nghiệp ác
thành nghiệp thiện là tự mình thẳng tiến trên bước đường đạo đức, đóng góp sự vui
tươi an lạc cho gia đình mình, xây dựng hoàn hảo cho xã hội văn minh. Văn minh ở
đây là văn minh đạo đức, văn minh của tình thương chia ngọt sẻ bùi, văn minh của
những con người thanh bai cao thượng. Cho nên trong kinh Thập Thiện nói người tu
Thập thiện sẽ được sanh lên cõi trời, gọi là Thiên thừa Phật giáo. Song với chúng tôi,
người tu Thập thiện là con người hoàn hảo, trong xã hội có đa số người tu Thập thiện
là xã hội văn minh hoàn hảo. Đây là Phật pháp giáo hóa dân gian.
