
# Tu trong mọi hoàn cảnh {- #tu-trong-moi-hoan-canh}

Có nhiều người nghĩ rằng, tu là phần riêng của những kẻ rảnh rang nhàn hạ,
những người thừa của thừa tiền, còn mình làm đầu tắt mặt tối, cơm không đủ no áo
không đủ ấm, có thì giờ đâu mà nói chuyện tu. Hoặc có những người nghĩ, tu là việc
của những kẻ thiếu phước bần hàn, cô quả, tật nguyền, nhờ tu họ được an ủi bớt khổ,
còn ta phước nhiều của lắm, thân quyến đầy đàn, đẹp đẽ sang trọng mà tu làm gì. Lại
có người nghĩ, tu là việc của những kẻ tội lỗi ác độc, bởi họ tạo nhiều tội lỗi nên phải
tu để chuộc tội, còn tôi hiền lành có làm gì hại ai đâu mà tu. Bởi có những quan niệm
này, nên người ta không màng không nghĩ đến tu. Họ đâu biết rằng, mọi chúng ta
trong tâm niệm có cả xấu lẫn tốt, nếu thả nổi mặc tình niệm xấu hoành hành, là sống
theo bản năng, mất hết tư cách của con người và sẽ gây tội lỗi ngập trời. Để hạn chế
tâm niệm xấu, khiến nó tiêu mòn, khởi dậy tâm niệm tốt, khiến nó tăng trưởng, đây là
việc làm của người tu. Có giảm tâm niệm xấu, tăng tâm niệm tốt, người này mới đủ tư
cách con người và làm nhiều việc tốt đẹp với mọi người chung quanh. Thế là, có hoàn
cảnh nào mà chẳng nên tu?

## Tu trong cảnh bận rộn {- #tu-trong-canh-ban-ron}

Có những người bận lo sinh kế gia đình, tửng bưng sáng đã có mặt ở chợ, đến
sẩm tối mới về tới nhà, rồi lo ăn uống giặt giũ cho con cái là tối mò, có rảnh lúc nào
đâu mà tu? Nếu bảo những người này phải tụng kinh, phải lần chuỗi niệm Phật, chắc
hẳn không thế nào làm được. Nhưng tu ở đây là, bỏ ý nghĩ xấu, nuôi dưỡng ý nghĩ tốt,
bỏ lời nói dữ, nói lời nói lành, dừng những hành động ác, tạo những hành động thiện,
có mất thì giờ chút nào mà tu không được. Trái lại, chính khi buôn bán làm ăn ấy,
chúng ta có ý nghĩ tốt, thốt lời nói lành, có hành động thiện, người khách hàng mến
thương, khiến khách mua hàng càng lúc càng đông, việc làm ăn dễ phát đạt. Ví như cô
bán hàng có khách đến mua, giá món hàng một ngàn đồng, cô nói một ngàn hai, chờ
khách trả một ngàn là cô bán. Song trớ trêu, người khách không trả một ngàn, mà trả
ba trăm. Trường hợp này, nếu cô bán hàng không biết tu thì nổi giận quát tháo ầm ĩ,
gây ra cuộc cãi vã ồn ào. Ngược lại, cô bán hàng biết tu, chỉ cần cười, nói nhẹ nhàng
*“trả chưa tới giá, bán không được”*. Mọi việc êm ái, không ai thiệt thòi gì, mai kia
người khách ấy còn có thể đến gian hàng này mua hàng. Trước những cảnh bất như ý,
chúng ta biết kềm hãm sự nóng giận, biết lựa lời ôn hòa để đáp, biết giữ thái độ bình
tĩnh, là khéo tu. Ở giữa chợ, mỗi ngày sự bất như ý diễn ra liên tục, nên tu hành là điều
tối cần cho người sống trong hoàn cảnh này. Vì thế người xưa nói: *“Nhất tu thị, nhị tu
sơn”*.

Nếu là người nông phu làm nghề ruộng khi vác cuốc ra đồng, chúng ta nghĩ
*“cần mẫn làm cho lúa trúng, để có cơm cho gia đình mình ăn, vơi ra giúp đồng bào
mình cùng có cơm ăn”*. Quan niệm ấy là ý nghĩ lành, đó là tu. Thấy thửa ruộng bên
cạnh tốt hơn ruộng mình, không có tâm đố kỵ, mà lòng mừng thầm bạn mình được lúa
trúng, gia đình ấm no..., mình gắng học hỏi theo cách làm ăn ấy, đây là tâm niệm của
người biết tu. Lại, khi làm việc đắp bờ cuốc ruộng, trong tâm vừa nảy ra niệm xấu, ta
liền diệt trừ, trong tâm nảy ra niệm tốt, ta liền khơi dậy cho nó tăng trưởng, ấy là tu,
một cuốc là một câu niệm Phật, hoặc một cuốc tận kim cang địa ấy là tu.

Là học trò bận việc học hành, công phu tu không hề chướng ngại. Khi cắp sách
đi học, em nghĩ “ta cố gắng học cho giỏi, để mai kia giúp cha mẹ khi tuổi già, có tài để
góp công mình xây dựng quê hương tốt đẹp hơn”, đó là em tu. Thầy giáo, cô giáo nhọc
sức giảng dạy bài vở, em lắng nghe và cố học thuộc, vì thương sợ thầy cô buồn, đấy là
em biết tu. Bạn bè trong lớp có những trò học giỏi hơn em, em không ganh tỵ, trái lại
còn kính phục để bắt chước theo, ấy là tâm niệm người tu. Người tu là người biết phục
thiện, mỗi khi có lỗi lầm bị rầy, bị phạt, biết lỗi sửa ngay, không oán hờn trách móc.
Có những đứa học hành thua kém và thiếu phương tiện hơn em, em thương mến hướng
dẫn và giúp đỡ nó, là em khéo tu. Xã hội ngày mai sáng sủa hơn, tốt đẹp hơn, chính
nhờ những mầm non biết tu.

## Tu trong cảnh nghèo khó {- #tu-trong-canh-ngheo-kho}

Chúng ta nghèo tiền nghèo của chớ đâu có nghèo ý nghĩ, lời nói, hành động.
Chuyển hóa ý nghĩ xấu thành tốt, lời nói dữ thành hiền, hành động ác thành thiện là tu.
Việc này đâu đòi có tiền có của, nhàn rỗi mới làm được. Chính trong cuộc sống vất vả
nghèo nàn của chúng ta cần thiết phải có nó. Như có người nghèo khó vất vả mà lòng
tốt, lời nói hiền hòa, hành động lương thiện, khiến mọi người thương mến giúp đỡ, nhờ
đó mọi khó khăn giảm bớt đi. Ngược lại, nếu ở trong cảnh khó khăn mà ý ngang
ngạnh, lời nói hung dữ, hành động bạo ngược, khiến ai nghe thấy cũng ghét cũng lánh
xa, nhờ điều gì họ cũng không giúp, thì khó khăn lại càng khó khăn hơn. Hơn nữa, tâm
hồn trong sáng, lời nói hiền hòa, hành động thanh cao, dù chúng ta sống trong cảnh
nghèo vẫn thấy êm đềm hạnh phúc. Chồng biết nhường vợ, vợ biết kính chồng, con
hiếu thuận cha mẹ, cha mẹ thương yêu con cái, gọi là cuộc sống hạt muối cắn hai, thật
là lý tưởng biết bao.

## Tu trong cảnh bệnh hoạn {- #tu-trong-canh-benh-hoan}

Bình thường người ta cho khi bệnh hoạn là chướng ngại tu hành, đây cũng là
quan niệm sai lầm về việc tu. Nếu thấy tụng kinh, tọa thiền mới là tu, khi bệnh hoạn
tụng kinh không nổi, tọa thiền không được, đó là chướng ngại tu. Song tu cốt ngăn
ngừa phiền não, chiến thắng vọng tưởng, dù có tụng kinh tọa thiền, không tụng kinh
tọa thiền đều tu được. Nếu có người bệnh nặng không đi đứng được, nằm một chỗ, khi
ấy nằm nhiếp tâm niệm Phật, niệm chí tử, chẳng buồn nghĩ đến ai, lo việc gì, chỉ một
bề niệm Phật thôi. Đây là tu đại tinh tấn theo pháp môn Tịnh độ, đâu có chướng ngại
gì. Hoặc có người bệnh, không niệm Phật mà thích quán chiếu, liền quán thân này thấy
nó là gốc khổ đau, là tướng vô thường, là hiện tượng nhớp nhúa, là không có chủ,
nương thân bệnh quán chiếu tường tận như vậy, thấy được tướng thật của thân, đây là
pháp trí tuệ sẽ gần với Niết-bàn, là tu thiền. Khổ nỗi, người Phật tử bình thường tinh
tấn tu hành, gặp lúc bệnh hoạn lại thối chuyển, sanh phiền não với con cháu, đây là
việc đáng tiếc. Khi mạnh chúng ta tu, để khi yếu bệnh có đủ đạo lực tiếp tục, vì lúc này
là lúc gần với tử thần, là phút chiến đấu cuối cùng, nếu ngang đây mà dừng, mà hướng
đi chiều khác, thật là một việc hoài công vô ích. Bởi vậy nên, Phật tử chúng ta phải
thấy khi bệnh là cơ hội tốt, dồn hết tâm lực vào sự tu, chuyên tâm không lơi niệm,
được vậy là gần với Phật, gần Niết-bàn, mới mong thoát khỏi khổ luân hồi muôn kiếp.

## Tu trong cảnh tại gia {- #tu-trong-canh-tai-gia}

Có một số Phật tử nghĩ rằng, ở tại gia phiền rộn khó tu, được xuất gia rảnh rang
tu hành mới giải thoát. Quan niệm này cũng không đúng. Nếu thấy tại gia là nhiều
việc, vào chùa chắc gì ít việc? Người xưa nói: “Ca-sa vị trước hiềm đa sự, trước dĩ ca-
sa sự cánh đa” *(Ca-sa chưa mặc than nhiều việc, được mặc ca-sa việc lại nhiều)*. Câu
này thật là chua chát đối với người tu. Đây quả là sợ ông táo gặp ông lò, chạy ô mồ
mắc ô mả. Chúng ta đâu không nghe quí thầy trụ trì thường than: *“Trụ trì làm dâu trăm
họ”*. Thế là ít việc hay nhiều việc, phiền rộn hay rảnh rang. Yếu điểm tu hành là hiểu
đạo, vững lòng tin. Đủ hai điểm này, ở tại gia hay xuất gia đều tu được. Nếu không đủ
hai điểm này, dù ở chùa chưa chắc đã tu được. Chúng ta phải khéo linh động trong mọi
hoàn cảnh, đừng đòi hỏi phải cảnh thế ấy tu mới được. Sự đòi hỏi đó là cái cớ để
chúng ta không tu. Vì có những người không thể tạo được hoàn cảnh như ý. Có những
Phật tử nam cũng như nữ, con cái đầy đàn đầy đống mà cứ nằng nặc đòi xuất gia,
quăng đại cho người ở nhà làm sao thì làm. Nếu thỏa mãn nguyện vọng, vào chùa một
lúc, gặp khi gia đình thiếu thốn, con cái nheo nhóc, nóng lòng rồi gởi ca-sa cho chùa
trở về nhà. Đây là việc làm nông nổi.

## Chứng minh mọi hoàn cảnh đều tu được {- #chung-minh-moi-hoan-canh-deu-tu-duoc}

Ngày xưa, đời Đường ở Trung Hoa có gia đình ông Bàng Long Uẩn, vẫn làm cư
sĩ tại gia, mà tu đến được chỗ sanh tử tự tại. Trong giới học Phật từ trước đến nay vẫn
ngưỡng mộ công đức tu hành của gia đình ông. Như trong bài sám tu Tịnh độ đã đọc
buổi tối, có câu: *“in như thiền định họ Bàng thuở xưa...”*. Ông Bàng Long Uẩn trước
theo Nho học, sau nghiên cứu Phật thấy thích thú, ông tìm đến tham vấn các Thiền sư.
Ban đầu, ông đến hỏi Thiền sư Hy Thiên *(Thạch Đầu)*: *“Người không cùng muôn pháp
làm bạn là người gì?”*. Hy Thiên liền bụm miệng ông. Ngay đây ông được ngộ. Sau ông
đến tham vấn Mã Tổ *(Đạo Nhất)*, cũng đem câu ấy ra hỏi. Mã Tổ bảo: *“Ông hớp một
ngụm cạn hết sông Tây Giang, ta sẽ vì ông nói”*. Ông càng tin sâu hơn.

Gia đình ông, hai ông bà và một con trai, một con gái. Ông cất nhà gần chân
núi, mỗi ngày chẻ tre đan sáo, cô con gái gánh ra chợ bán. Sống đạm bạc qua ngày để
tu hành.  

Một hôm, trong nhà cùng ngồi bàn việc đạo, ông nói: “Nan nan nan, thập tạ
du ma thọ thượng thang” *(Khó khó khó, mười tạ dầu mè trên cây vuốt)*.  

Bà đáp: “Dị dị dị, bách thảo thượng đầu Tổ sư ý.” *(Dễ dễ dễ, trên đầu trăm cỏ ý Tổ sư)*. 

Cô con gái tên Linh Chiếu đáp: “Dã bất dị, dã bất nan, cơ lai khiết phạn, khốn lai thùy” *(Cũng chẳng dễ, cũng chẳng khó, đói đến thì ăn mệt ngủ khò)*.   

Với cái nhìn của ông, thấy sự tu hành thật khó khăn vô kể, giống như người trèo lên cây cao mà bị thoa dầu, trèo lên tuột xuống, không có chỗ để bám. Trái lại, bà thấy việc tu rất dễ, vì nhìn ở đâu cũng
thấy ý Tổ sư tràn khắp. Cô Linh Chiếu dung hòa, không nói khó, không nói dễ, khó dễ
là hai bên, vượt qua hai bên *(nhị kiến)* tâm sẽ thanh tịnh thản nhiên, khi ấy chỉ đói đến
thì ăn, mệt đến thì ngủ. Câu nói của cô Linh Chiếu dễ bị người sau hiểu lầm, người ta
nghĩ rằng tu thiền là đói ăn mệt ngủ, rồi sống theo bản năng, thật là tai họa, chủ yếu cô
nói là, khi nào tâm ta không còn mắc kẹt hai bên, khó dễ, tốt xấu, hơn thua, hay dở...,
mới đến chỗ đói ăn mệt ngủ.

Lại, ông có làm bài kệ nói sự đoàn tụ của gia đình ông như sau:  

<div class="align-center">
> Hữu nam bất thú  
> Hữu nữ bất giá  
> Đại gia đoàn biến đầu  
> Cộng thuyết vô sanh thoại  
</div>
  
Dịch:  

<div class="align-center">
> Có con trai không cưới vợ  
> Có con gái không gả chồng  
> Cả nhà cùng sum họp  
> Đồng bàn lời vô sanh  
</div>

Về già, một hôm ông lên ngựa giữa ngồi chuẩn bị tịch, bảo Linh Chiếu: *“Con ra
sân xem đúng ngọ vô cho cha hay”*. Cô Linh Chiếu ra xem trở vào thưa: *“Gần đúng
ngọ, mặt trời bị nguyệt thực, cha ra xem”*. Ông ra sân xem, trở vào, thấy Linh Chiếu
lên ngựa giữa ngồi kiết già tịch. Ông nói: *“Con gái ta lanh lợi quá!”*. Lo mai táng Linh
Chiếu xong, ông báo tin cho thân hữu hay sắp tịch. Hôm ấy bạn bè tụ hội, ông nằm gối
đầu trên đầu gối Châu Mục Công, nhắm mắt thị tịch. Tin này đến bà Long Uẩn, bà ra
đồng cho con trai hay, người con trai đang đánh trâu cày ruộng, bà bảo: *“Con ơi! Ông
già vô tri và con bé ngu si đã bỏ mình đi rồi”*. Người con trai thưa: *“Vậy hở mẹ!”*. Liền
đứng thẳng tịch. Bà nói: *“Thằng ngu si này cũng đi nữa”*. Bà lo mai táng con trai xong,
lên núi tịch. Đây là hiện tượng sanh tử tự tại của gia đình ông Bàng Long Uẩn. Ông
Long Uẩn đan sáo, cô Linh Chiếu bán sáo ngoài chợ, con trai ông cuốc cày ngoài
ruộng, bà Long Uẩn ở nhà nấu cơm, đều tu hành đắc lực đến sanh tử tự tại. Tại sao
chúng ta lại đổ tại hoàn cảnh này, hoàn cảnh nọ, tu không được?

Đến đời Trần ở Việt Nam, vua Trần Thánh Tông và Tuệ Trung Thượng Sĩ, một
ông vua, một ông quan vẫn tu hành đắc lực. Chúng ta ôn lại câu chuyện sau đây. Nhân
ngày làm tuần cho Hoàng thái hậu, vua Thánh Tông thỉnh các bậc tôn túc đến dự trai,
trong đó có Tuệ Trung Thượng Sĩ. Nhà vua yêu cầu các Ngài trình bài kệ ngắn để thấy
chỗ kiến giải của các ngài, qua nhiều bài kệ, nhà vua không hài lòng bèn trao giấy bút
cho Thượng Sĩ. Thượng Sĩ viết một mạch:  

<div class="align-center">
> Kiến giải trình kiến giải  
> Tợ niết mục tác quái  
> Niết mục tác quái liễu  
> Minh minh thường tự tại  
</div>
  
Dịch:  

<div class="align-center">
> Kiến giải trình kiến giải  
> Như dụi mắt thấy quái  
> Dụi mắt thấy quái rồi  
> Rõ ràng thường tự tại  
</div>
  
Nhà vua đọc xong, liền phê tiếp ở sau:  

<div class="align-center">  
> Minh minh thường tự tại  
> Diệc niết mục tác quái  
> Kiến quái bất kiến quái  
> Kỳ quái tất tự hoại  
</div>

Dịch:  

<div class="align-center">
> Rõ ràng thường tự tại  
> Cũng dụi mắt thấy quái  
> Thấy quái chẳng thấy quái  
> Quái ấy ắt tự hoại  
</div>

Kiến giải của chúng ta không thật, giống như dụi mắt trong hư không có những
đốm hoa. Khi con mắt bình thường trở lại thì những đốm hoa không còn. Những đốm
hoa mất đi, ấy là con mắt sáng. Tâm chúng ta bị kiến giải che mờ, một khi kiến giải
lặng mất, lúc ấy mới là tâm chân thật sáng suốt. Vua Thánh Tông và Thượng Sĩ chỗ
thấy như nhau, khác nhau chỉ đối ngược ý trước sau mà thôi. Thượng Sĩ nói con mắt
dụi thấy hoa đốm, khi hết lòa con mắt trước đã sáng rỡ. Thánh Tông nói con mắt trước
đã sáng rõ, do dụi nên thấy hoa đốm, chính khi thấy hoa đốm, biết là không thật thì hoa
đốm tự mất, trở lại con mắt sáng như trước.

Vua Thánh Tông đau nặng, Thượng Sĩ biên thơ hỏi thăm. Vua trả lời bằng hai
câu thơ:  

<div class="align-center">
> Viêm viêm thử khí hạn thông thân  
> Vị tằng uyển ngã nương sanh khố  
</div>

Dịch:  
  
<div class="align-center">
> Hừng hực hơi nóng toát mồ hôi  
> Chiếc khố mẹ sanh chưa từng ướt  
</div>

Thượng Sĩ bệnh sơ sài, Ngài kê một giường gỗ nằm tại Dưỡng Chân Trang.
Ngài nằm nghiêng bên phải theo phép cát tường, mắt nhắm lại, người hầu và thê thiếp
khóc rống lên. Ngài mở mắt ngồi dậy, sai lấy nước rửa tay súc miệng, liền quở nhẹ
rằng:

*“Sống chết là lẽ thường, buồn thảm luyến tiếc chi, làm não chân tánh ta.”*

Nói xong, Ngài nằm xuống yên lặng mà tịch.

Một ông vua khi sắp chết, thấy thân tứ đại tan rã đau đớn, song còn một cái
chưa bao giờ tan rã, đây là *“chiếc khố mẹ sanh”*. Một ông quan sống trong cảnh thê
thiếp tôi tớ đầy nhà, mà vẫn nhẹ nhàng thanh thản ra đi, trước mọi người khóc than
luyến tiếc. Nếu vì bận rộn khó tu, ai bận rộn hơn một ông vua, nhất là ông vua vì dân
vì nước trước cuộc xâm lăng của phương Bắc. Ai bị ràng buộc hơn một ông quan, có
đủ thê thiếp tôi tớ đầy nhà. Những vị này tu được, chúng ta không còn lý do gì thối
thác khó tu.

Tóm lại, chúng ta là con người chưa có ai toàn hảo, cần phải biết tu để chận
đứng những điều xấu dở xuất phát từ ba nghiệp của mình. Đồng thời chúng ta khéo
nuôi dưỡng những hành động tốt đẹp từ thân miệng ý phát ra. Dừng ác nuôi thiện là
điều không thể thiếu, nơi con người muốn vươn lên. Khước từ tu hành, là chúng ta
khước từ sự tiến bộ, là khước từ mọi đẹp đẽ cao quí, khước từ sự an vui hạnh phúc.
Nếu ai quyết chí vươn lên, muốn sống cuộc đời an lạc, muốn gia đình hạnh phúc,
muốn xứ sở huy hoàng, tu là chủ yếu thực hiện những điều mong muốn ấy.
