
# Hoa sen trong bùn {- #hoa-sen-trong-bun}

Có lắm người xuất gia cũng như tại gia cho rằng, chúng ta tu không thể nào giác
ngộ thành Phật. Vì đức Phật ra đời có những nhân duyên kỳ đặc, bản chất Ngài đã
thánh sẵn rồi; còn chúng ta nào là ham mê dục lạc, nào là tội lỗi đầy đầu, nào là sanh
nhằm thời mạt pháp căn cơ yếu kém ngu độn v.v... làm sao tu thành Phật được? Ở đây
chúng ta hãy nhìn Thái tử là một con người, thật là người để lấy làm mẫu mực hướng
theo tu hành.

## Thái tử Tất-Đạt-Đa *(Siddharta)* sống trong hoàng cung {- #thai-tu-trong-hoang-cung}

Khi là một ông hoàng ở trong cung cấm, Thái tử bị mọi thứ dục lạc bủa vây:
nào là vợ đẹp, hầu xinh, Ngài có cả thảy ba bà vợ, bà Cu-tỳ-gia *(Gapica)*, bà Gia-du-
đà-la *(Yasodhara)*, bà Lộc Giả *(Urganica)* và cung phi mỹ nữ. Nào là đàn ngọt hát hay,
cả ngày âm thanh dằng dặc không dừng nghỉ. Nào là sự chiều chuộng của vua cha, xây
cung điện thích hợp bốn mùa, tạo cảnh vui thích không để Ngài có một phút đăm
chiêu. Đây là cảnh thiên đàng ngay trong trần thế, Ngài vui hưởng cảnh này đến năm
mười chín tuổi.

## Thái tử đi tu và thành Phật {- #thai-tu-di-tu-va-thanh-phat}

Chỉ một lần Thái tử trông thấy cảnh già, bệnh, chết của con người, Ngài khổ
đau trằn trọc. Tại sao người ta phải chấp nhận lớp người này sanh ra, già, bệnh, chết,
rồi lớp khác tiếp tục, cứ thế tiếp tục mãi không có ngày cùng? Ngài cương quyết đập
tan cái tiền lệ ấy. Vì thế, bao đêm Ngài thức trắng, lòng Ngài băn khoăn đau xót giày
vò, cốt tìm ra lối thoát để cứu mình, cứu chúng sanh. Từ đây, sắc đẹp hát hay, trở
thành trơ trẽn tầm thường trước mắt Ngài. Thức ngon vị ngọt, trở thành nhạt nhẽo chán
ngán, khi chúng để vào miệng Ngài. Ngài ê chề ngán ngẩm mọi thứ dục lạc tạm bợ trá
hình. Ngài cương quyết rời hoàng cung xuất gia tầm đạo. Mặc dù con đường này giăng
trải trước mắt Ngài muôn vàn nguy hiểm thập tử nhất sanh, Ngài chấp nhận phải dấn
bước. Thế là Ngài xuất gia lúc mười chín tuổi.

Bao nhiêu năm lang thang trong rừng sâu học đạo, con người vương giả của
Ngài đã pha màu sương gió, đã từng trải mọi thứ đắng cay, song ý chí kiên cường quả
cảm của Ngài không suy giảm. Học đạo không thỏa mãn, Ngài nguyện thực hành khổ
hạnh tột cùng. Nhưng thân sắp hoại mà đạo chưa thấy, Ngài phải sống trung hòa và
đến dưới cội bồ-đề ngồi tu bốn mươi chín ngày đêm liền ngộ đạo. Ngang đây, Ngài
thành Phật hiệu là Thích-ca Mâu-ni. Đã qua rồi, con đường tầm đạo ngót mười một
năm.

Sau khi Ngài thành Phật, Ngài nhìn hồ sen thấy có những hoa đã nở tròn đầy, có
những hoa còn búp son trinh, có những hoa đang trụ hình trong nước, có những mầm
sen còn vùi trong bùn nhơ. Song tất cả đều có khả năng nở tròn khoe sắc, nhả hương
tinh khiết. Chúng đồng trong lòng đất nhớp nhúa vươn lên, khi được hớp sương phơi
nắng, chúng đều tròn đủ sắc hương như nhau. Ngài thấy con người cũng thế, khi sanh
ra và lớn lên trong vòng mê dục, một phen tỉnh giác con người sẽ tiến lên bậc giác ngộ
khó gì. Thế là, Ngài lấy hoa sen để biểu trưng cuộc sống và giáo lý của Ngài. Kinh
Diệu Pháp Liên Hoa là hình ảnh cụ thể nhất.

## Phật ngồi trên đài sen {- #phat-ngoi-tren-dai-sen}

Chúng ta đọc lịch sử Phật, ai cũng biết Bồ-tát đến cội bồ-đề trải cỏ làm tòa
ngồi, và thành đạo ngay dưới cội cây này. Hiện nay chúng ta thờ Phật đúng theo tài
liệu lịch sử, phải để Ngài ngồi trên tòa cỏ. Tại sao ngày nay chùa nào thờ Phật cũng
ngồi trên tòa sen? Đây là để biểu trưng con người của Ngài. Vì trước kia là ông hoàng,
Ngài cũng nhiễm ô ngũ dục, như mầm sen còn ở trong bùn. Khi Ngài vượt thành xuất
gia là mầm sen ra khỏi bùn, mà còn ở trong nước. Lúc Ngài ngồi tu ở dưới cội bồ-đề
và thành đạo là hoa sen ra khỏi nước nở tròn đầy hương thơm ngào ngạt. Hoa sen lại
tượng trưng cho sự bình đẳng giữa mọi người. Đã là mầm sen thì mầm sen nào cũng
có khả năng vươn lên khỏi bùn, khỏi nước và trổ hoa tươi thắm hương thơm ngạt ngào.
Đã là con người thì con người nào cũng có khả năng thoát khỏi dục lạc ô nhiễm, thức
tỉnh tu hành và đạt thành đạo quả. Phật quả không phải của riêng một người nào, mà
của chung tất cả ai có ý chí thoát trần, có quyết tâm đạt đạo. Vì vậy, Phật quả gọi là Vô
thượng giác, là giác ngộ không ai trên, song có người bằng; Phật cũng dùng hình ảnh
hoa sen để nhắc nhở Phật tử, ở giữa chốn ô nhiễm mà khéo vượt ra bằng trí tuệ sáng
ngời của mình.

Bài kệ nói :  
  
<div class="align-center">
> Như giữa đống rác nhớp. Quăng bỏ nơi bờ đầm  
> Chỗ ấy hoa sen nở. Thơm sạch đẹp ý người.  
> Cũng vậy, giữa quần sanh. Uế, nhiễm, mù, phàm tục  
> Đệ tử bậc Chánh Giác. Sáng ngời với trí tuệ.  
>  
> <div class="align-right">*(Pháp cú câu 58-59)*</div>
</div>

Hoa sen mọc chỗ nhớp nhúa mà thơm tho tươi đẹp, sống trong đời nhiễm nhơ
mù tối, người Phật tử chúng ta phải khéo dùng trí tuệ vượt ra để cứu mình, và cứu
người. Cái quí của hoa sen là sanh từ chốn bùn lầy mà tinh khiết, cái cao cả của người
tu là sống trong mọi dục lạc nhiễm ô mà vượt ra an toàn siêu thoát. Hoa hường, hoa
lan thơm hơn hoa sen, mà không được nhắc tới, vì sanh ở chỗ đất sạch. Nếu Thái tử là
người từ trên trời rơi xuống mà đắc đạo thì không có giá trị gì. Chính trong vòng kềm
tỏa của dục trần, mà thoát được mới là bậc đại hùng.

## Cá nhảy khỏi lưới {- #ca-nhay-khoi-luoi}

Đời Tống ở Trung Hoa có hai Thượng tọa Thâm và Minh. Hai vị có duyên sự
cùng sang đò qua sông Hoài. Đang sang sông, thấy người bủa lưới đang kéo, có con cá
to nhảy khỏi lưới ra ngoài. Thượng tọa Thâm vỗ tay khen: *“Hay thay! Như Thiền sư”*.
Thượng tọa Minh không đồng ý bảo: *“Phải ở ngoài lưới mới hay, đợi vào lưới rồi mới
nhảy là muộn”*. Thượng tọa Thâm nói: *“Huynh Minh chưa hiểu”*. Đi hơn dặm đường,
Thượng tọa Minh bỗng nhận ra chỗ sai, liền sám hối.

Qua câu chuyện trên, chúng ta thấy thế nào? Con cá trong lưới nhảy là hay, con
cá thong dong ngoài lưới là hay? Đạo lý nhà Phật dạy, trong cảnh bủa vây của phiền
não mà thoát ra được mới thật là hay. Đây mới thi thố được sức mạnh phi thường của
con người thoát tục. Nếu ở ngoài lưới nói gì nhảy, không nhảy làm sao biết được sức
mạnh của mình. Hơn nữa, bản thân con người đầy đủ tam bành *(tam độc)*, lục tặc *(sáu
giặc)* lại sáu trần dụ dỗ cuốn lôi, nếu không phải là bậc siêu quần bạt tụy làm sao thắng
trận giặc nội công ngoại kích này. Cùng là cá, bao nhiêu con khác bị lưới cuốn không
thể giãy vùng, cuối cùng bị người đánh cá bắt bỏ vào giỏ, chỉ một con này nhảy vọt
khỏi lưới, không đồng với người xuất trần thoát tục là gì? Nếu chúng ta sanh ra đã là
Thánh thì còn nói gì tu. Chính vì chúng ta mang đầy đủ thói hư tật xấu trong mình,
chứa đầy tham sân si trong lòng, cho nên gặp cảnh thì nhiễm, trái ý thì sân, quẳng
chúng thoát ra, thật là điều khó khăn trăm phần, ai làm được điều đó, đáng cho chúng
ta chấp tay tán thán. Vì thế, Tuệ Trung Thượng Sĩ đã làm bài kệ:  
  
<div class="align-center">  
> Xuất trần  
>  
> Tằng vi vật dục dịch lao khu  
> Bài lạc trần hiêu thế ngoại du  
> Tán thủ na biên siêu Phật Tổ  
> Nhất hồi đẩu tẩu nhất hồi hưu  
</div>

Dịch:  
  
<div class="align-center">  
> Ra khói bụi hồng  
>  
> Đã từng ham muốn phải long đong  
> Ném quách mà ra khỏi bụi hồng  
> Buông thõng bờ kia lên Phật Tổ  
> Một lần phủi giũ một lần xong  
</div>

Bởi vì chúng ta chạy theo vật dục nhân gian nên phải khổ sở gian nan. Nếu can
đảm ném phắt hết, vượt ra ngoài vòng trần lụy, quả là can đảm phi thường. Có thể,
mới buông thõng tay bước lên ngôi nhà Phật Tổ được. Song phải mạnh dạn dứt khoát,
một lần bỏ đi không thèm ngó lại. Chớ đừng học thói nhầy nhụa, dùng dùng thẳng
thẳng cắt không đứt, bứt không rời, một chân bước tới hai chân bước lui, không làm
nên trò trống gì, chỉ chuốc trò cười cho hàng thức giả. Bởi vậy nên nhà thiền thường
dùng câu *“giết người không ngó lại”* là ý này. Phải can đảm dứt khoát thì việc khó mấy
cũng thành công.

## Trần Nhân Tông ông vua, tu sĩ {- #tran-nhan-tong-tu-si}

Vua Trần Nhân Tông sanh năm 1258, lên ngôi vua năm hai mươi tuổi, xuất gia
năm bốn mươi mốt tuổi và năm mươi mốt tuổi tịch *(1308)*. Suốt hai mươi năm, Ngài là
bậc nhân chủ lãnh đạo quốc gia giữ nước chăn dân, ngồi trên ngai vàng sống trong
cung ngọc, mọi thứ dục lạc đều dư thừa. Hai phen cầm quân chống giặc xâm lăng,
nhân mạng hy sinh rất lớn. Bổn phận giữ nước chăn dân, Ngài làm đầy đủ. Năm bốn
mươi mốt tuổi, Ngài nhường ngôi cho con, đi xuất gia. Lúc nhỏ Ngài đã được vua cha
và thầy là Tuệ Trung Thượng Sĩ chỉ dạy đạo lý thiền nhuần thấm sâu xa, nên khi xuất
gia Ngài không cần tầm học, chỉ thực hiện điều đã học được.

Trong mười năm, là kẻ xuất gia Ngài mang hiệu Trúc Lâm Đầu-đà, tích cực
hoạt động truyền bá chánh pháp. Trong giới xuất gia, Ngài giáo dục chúng Tăng, có
khả năng đảm đang Giáo hội. Trong dân chúng, Ngài đem pháp Thập thiện giáo hóa
toàn dân, khiến Phật pháp mở rộng trong nhân gian. Công tác hoằng truyền Phật pháp,
giáo hóa nhân dân, Ngài làm suốt đời không dừng nghỉ.

Khi sắp tịch, Ngài nằm tại Ngọa Vân am sai người gọi Bảo Sát đến. Ngày một
tháng mười một, đúng nửa đêm, sao sáng đầy trời, Ngài hỏi: Bây giờ là giờ gì? Bảo
Sát thưa: Giờ Tý. Ngài đưa tay ra hiệu mở cửa sổ để nhìn ra ngoài, nói: Đến giờ ta đi
vậy. Bảo Sát hỏi: Tôn đức đi đâu bây giờ? Ngài đọc lại bài kệ:  
  
<div class="align-center">
> Nhất thiết pháp bất sanh  
> Nhất thiết pháp bất diệt  
> Nhược năng như thị giải  
> Chư Phật thường hiện tiền  
> Hà khứ lai chi hữu?  
</div>

Dịch:  
  
<div class="align-center">
> Tất cả pháp chẳng sanh  
> Tất cả pháp chẳng diệt  
> Nếu hiểu được như thế  
> Chư Phật thường hiện tiền  
> Nào có đi có lại?  
</div>

Bảo Sát hỏi thêm: Khi chẳng sanh chẳng diệt thì sao? Ngài khua tay nói: Thôi
đừng nói mê nữa. Rồi Ngài ngồi theo kiểu sư tử tọa mà tịch... *(Tam Tổ thực lục)*.  

Qua ba giai đoạn trên, chúng ta thấy Ngài sống giai đoạn nào ra giai đoạn ấy.
Lúc làm vua thì quên mình giữ nước, hết dạ chăn dân. Khi đi tu, nhiệt tâm vì đạo mài
miệt tu hành, chẳng ngại nhọc nhằn hết tình với Tăng tục. Vì thế, trên đường đời Ngài
thành công viên mãn, trên đường đạo thì đạo quả viên thành. Chính thái độ dứt khoát
tích cực, nên lãnh vực nào Ngài cũng thành công. Ngài cũng hưởng dục lạc trong
hoàng cung, cũng cầm binh khiển tướng ngoài trận mạc, nếu nói là tội lỗi thì cũng tràn
trề. Song khi dứt khoát tiến tu thì cắt đứt mọi quá khứ, sống kham khổ tu hành, nên lấy
hiệu Đầu-đà *(khổ hạnh)*. Với ý chí cương quyết đó, chỉ trong vòng mười năm, Ngài đã
tiến đến chỗ sanh tử tự tại. Đây là tấm gương sáng rỡ để nhắc nhở chúng ta, không sợ
mình trước mê lầm tội lỗi, chỉ sợ xuất gia rồi mà thái độ vẫn mập mờ. Ngài là con
người thấy được đạo lý và sống được đạo lý. Chúng ta đọc bài kệ kết thúc bài phú Cư
Trần Lạc Đạo của Ngài thì rõ:  
  
<div class="align-center">  
> Cư trần lạc đạo thả tùy duyên  
> Cơ tắc xan hề khốn tắc miên  
> Gia trung hữu bảo hưu tầm mích  
> Đối cảnh vô tâm mạc vấn thiền  
</div>

Dịch:  
  
<div class="align-center">
> Trong đời vui đạo hãy tùy duyên  
> Đói đến thì ăn mệt nghỉ liền  
> Nhà mình báu sẵn thôi tìm kiếm  
> Đối cảnh không tâm, chớ hỏi thiền  
</div>

Sống ngay trong lòng trần tục mà khéo biết đạo vẫn thấy an vui. Duyên cảnh
đổi thay tùy thời linh động, như khi đói thì ăn, khi mệt thì nghỉ, đừng cố chấp cứng
nhắc mà tự khổ đau. Phật đã sẵn nơi ta, khỏi phải nhọc nhằn sang đông tìm tây. Cái
khôn ngoan khéo léo của chúng ta là *“đối cảnh tâm không động”*, chính nơi đây là
thiền rồi, còn thưa hỏi đâu nữa. Người học đạo nhận thấy Phật đã sẵn nơi tâm mình,
song muốn Phật hiện thì tâm đừng chạy theo cảnh. Đây là lối tu thật giản đơn, thật cụ
thể, mà người đời khó tin khó nhận. Người ta chỉ tin Phật ở Tây phương, phải siêng
năng lễ bái thì được phước, được Phật rước về cõi Phật. Bởi vậy Tổ Lâm Tế nói:
*“Người ngu cười ta, kẻ trí biết ta”*. Cười, vì thấy không tụng kinh lễ bái, chẳng biết tu
cái gì? Biết, vì thấy lối tu tế nhị cụ thể thiết thực, không còn gì nghi ngờ. Một ông vua,
xuất gia chỉ có mười năm mà đạt đạo như vậy, thật đáng quí kính biết dường nào. Cho
nên triều đình tôn xưng Ngài là Điều Ngự Giác Hoàng.

## Thái tử Tất-Đạt-Đa và Trần Nhân Tông {- #thai-tu-tat-dat-da-va-tran-nhan-tong}

Thái tử là ông hoàng chưa từng đối đầu với mọi việc khó khăn ở đời, chỉ thấy
cảnh già, bệnh, chết là phát tâm đi tu. Mục đích Ngài đi tu để tìm phương pháp phá vỡ
cái luật khắc nghiệt của kiếp con người mà muôn thuở đã chấp nhận. Ngài phải trả cái
giá rất đắt là, mười một năm nằm gió phơi sương lang thang trong rừng núi, ăn uống
sơ sài cho đến kiệt sức. Đến khi giác ngộ viên mãn phương pháp giải thoát sanh tử
tuyên bố thành Phật. Đây là người khai mở con đường đạo giác ngộ giải thoát. Tức là
Ngài đã phá vỡ luật khắc nghiệt *(già bệnh chết)* chi phối mình và đem ra chỉ dạy mọi
người. Việc làm của Ngài là muôn thuở không hai.

Vua Trần Nhân Tông là người kế thừa con đường của Phật đã vạch sẵn. Bởi kế
thừa nên công phu đơn giản và nhẹ nhàng, chỉ cần đem đuốc mình mồi vào đuốc Phật
là cháy sáng. Do đó đi tu Ngài không khổ công tầm đạo, chỉ cần ứng dụng đạo đã sẵn
vào việc tu hành là thành công. Tuy vậy cũng không phải là việc dễ dàng, mặc dù có
công thức chỉ rõ, muốn ứng dụng công thức ấy phải gan góc cùng mình, phải mạnh tay
chặt đứt mọi xiềng vàng xích ngọc, phải hùng dũng nhảy vọt khỏi mấy lớp rào tình
cảm bịt bùng.

Hai Ngài đều chôn mình trong cung vàng điện ngọc, bị bao vây bởi đám cung
nữ phi tần, bị phủ kín trong tiếng đàn ngọt hát hay, bị siết chặt bởi mùi thơm vị quí.
Song cả hai đều quả cảm thoát ra không chút đoái hoài luyến tiếc. Do đó hai Ngài làm
được việc khó làm, để lại cho đời tấm gương phi phàm xuất chúng. Hai Ngài là hai
mầm sen chôn sâu trong vũng bùn ngũ dục, vươn lên khỏi nước nở tròn tươi thắm và
tỏa ra mùi hương tinh anh thanh khiết bủa khắp cả trần gian.

Qua những hình ảnh trên, chúng ta có đủ kinh nghiệm trong việc tiến tu, không
còn e dè nghi ngại gì nữa. Bởi vì không có vị nào đã là thánh rồi thành thánh, mà tất cả
đều bị bao vây bởi phiền não dục trần. Cái đặc điểm của các ngài là nhạy cảm sớm
thức tỉnh và anh dũng khi cần thoát nó. Điều đó chúng ta có thể học được, có ai thấy
cảnh già bệnh chết mà chẳng buồn, có ai không khí khái khi thốt ra những lời thề bán
mạng. Chỉ cần chúng ta triệt để ứng dụng cái nhạy cảm của mình để phát chí tu hành,
khéo xoay chuyển cái khí khái của mình vào con đường quyết tử cầu đạo. Dám hạ
quyết tâm trên đường hành đạo, chúng ta sẽ thu gặt được kết quả chắc chắn không
nghi. Chúng ta là những mầm sen phơi mình trên bùn ngũ dục, thoát khỏi nó để vươn
lên có khó gì? Chúng ta đâu có cung vàng điện ngọc, đâu có cung phi mỹ nữ... mọi dục
lạc tìm cầu rất khó, nếu thoát nó thì hết sức nhẹ nhàng, chỉ cần một cái nhảy nhẹ đã ra
khỏi rồi, thế mà chúng ta cứ chần chừ không ưng nhảy. Đây là yếu điểm muôn kiếp
chịu trầm luân của chúng ta.
