
# Bồ-tát sợ nhân chúng sanh sợ quả {- #bo-tat-so-nhan-chung-sanh-so-qua}

Là con người ai cũng sợ khổ cầu vui, song người mê chỉ biết sợ quả khổ cầu
quả vui. Ngược lại người tỉnh chỉ sợ nhân khổ, tạo nhân vui. Hai bên có cái nhìn khác
nhau, bên nào sẽ đạt được như sở nguyện? Dù ngây thơ thế mấy, người ta vẫn biết,
không tạo nhân lành mà cầu quả tốt là chuyện không đâu; sợ quả khổ mà cứ tạo nhân
ác là việc khó tránh. Nhân ác không gây, dù chẳng sợ quả khổ, nó vẫn không đến; nhân
lành cứ tạo, dù chẳng cầu quả vui, nó vẫn bò sang. Cho nên người trí nhìn từ cái nhân
mà chọn lựa, chọn nhân lành bỏ nhân ác. Cả đời mãi gây tạo nhân lành, loại trừ nhân
ác, người này bảo đảm gặt hái những kết quả đẹp đẽ an vui. Ai say sưa tạo nhân ác,
chẳng bao giờ nghĩ tới nhân lành, chắc chắn sẽ thu lượm được muôn vàn đau khổ, dù
họ sợ sệt khẩn cầu quả ấy đừng đến. Cho nên câu châm ngôn nhà Phật, ít Phật tử nào
không thuộc, là *“Bồ-tát sợ nhân chúng sanh sợ quả”*.

## Nghĩa Bồ-tát và chúng sanh {- #nghia-bo-tat-va-chung-sanh}

Bồ-tát *(Bodhisavattu)* là người giác ngộ, thấy tận cái manh nha cái đầu mối của
sự khổ đau và an lạc. Muốn hết khổ được vui, không gì hơn ngay cái mầm đau khổ
chúng ta đừng gieo, cái mầm an vui phải tung vãi. Không gieo nhân khổ thì quả khổ
làm gì có. Cứ tung vãi nhân vui thì quả vui không vời cũng đến. Đây là hành động của
người giác ngộ. Chúng sanh là những kẻ mê, chỉ nhìn trên cái quả mà sợ mà cầu. Luôn
luôn sợ khổ cầu vui, mà nhân đau khổ không tránh, nhân an vui không tạo. Một khi
quả đau khổ đến thì cầu khẩn van xin, song làm sao qua khỏi, vì đã hình thành. Cầu
mong mơ ước quả an vui, nhưng nhân không gây thì quả từ đâu mà đến. Đây là hình
ảnh trái ngược của kẻ mê người giác. Tuy nhiên, cái mê này ai cũng có thể bỏ, cái giác
này ai cũng có thể làm. Chỉ là nhắm vào nhân là giác, ai không thể làm được việc đó.
Thế nên, Bồ-tát là chuyện tất cả chúng ta có thể làm được và chúng sanh chúng ta cũng
bỏ được.

## Bồ-tát sợ nhân #{- #bo-tat-so-nhan}

Bồ-tát là con người giác ngộ và hay làm giác ngộ người khác. Bởi giác ngộ nên
thấy rõ cái gì là nhân đau khổ liền sợ hãi tìm mọi cách để diệt trừ. Thấy tham lam và
keo kiệt là nhân đau khổ, Bồ-tát tu bố thí để tiêu diệt nên nói bố thí độ san tham. Thấy
buông lung ngạo mạn là nhân phá hoại đức hạnh, Bồ-tát tu trì giới để khử dẹp, nên nói
trì giới độ phá giới. Thấy nóng giận là nhân gây nhiều tội lỗi. Bồ-tát tu nhẫn nhục để
dẹp, nên nói, nhẫn nhục độ sân hận. Thấy lười biếng bê tha là nhân hư thân mất công
đức, Bồ-tát tu tinh tấn để đánh đuổi, nên nói tinh tấn độ giải đãi. Thấy tâm tán loạn là
nhân điên đảo tối tăm, Bồ-tát tu thiền định để thu nhiếp, nên nói thiền định độ tán loạn.
Thấy ngu si là nhân trầm luân sanh tử, Bồ-tát tu trí tuệ để chiếu phá, nên nói trí tuệ độ
ngu si.

Sở dĩ Bồ-tát tu Lục độ là để diệt trừ sáu cái nhân xấu xa tội lỗi mù tối hiểm
nguy, dẫn con người đi mãi trong trầm luân đau khổ. Khi sáu cái nhân ấy bị tiêu diệt
hoàn toàn là giác ngộ giải thoát. Giai đoạn tu Lục độ là đang hành hạnh Bồ-tát, đến khi
giác ngộ là Bồ-tát thật sự. Phần này là tu hạnh Bồ-tát nặng về tự giác.

## Chúng sanh sợ quả {- #chung-sanh-so-qua}

Chúng sanh là những con người mê muội, một bề sợ khổ mà không biết nguyên
nhân. Thấy cái gì khổ đau đến là kinh hoàng khiếp sợ van xin cầu cứu, mà không biết
cái khổ ấy xuất phát từ nguyên nhân nào. Khi cái khổ qua rồi, thì bình thản như thường
không biết gì tu sửa. Những cái quả chúng sanh sợ nhất là:

Sợ người khác giết hại mình, mà tâm giết hại người không bỏ. Còn ôm mưu đồ
giết hại người thì quả người giết hại mình làm sao tránh khỏi. Sợ người khác lén lấy,
cướp giựt tiền bạc của cải của mình mà tâm tham lam của người không chừa. Đã tham
của người thì người tham của mình là sự đương nhiên. Sợ người ta xâm phạm tiết hạnh
vợ con mình, mà mình vẫn dòm ngó thèm thuồng vợ con người. Ôm lòng phá hoại sự
trinh bạch của gia đình người thì người phá hoại hạnh phúc gia đình mình khó tránh
khỏi. Sợ người ta dùng lời lường gạt vu cáo mình, mà mình vẫn thích lường gạt vu cáo
người. Đã có cái nhân lường gạt vu cáo người thì quả người lường gạt vu cáo mình
làm sao trốn được. Sợ say sưa như điên như dại bị người cười chê, mà rượu không từ
không kiêng. Sẵn sàng uống rượu thì phải chấp nhận say sưa. Đây là những cái quả
mà chúng sanh sợ hãi. Song sợ quả mà không tránh nhân, thật là khờ khạo ngây thơ.
Đó là nói lên tính mê muội của con người, được gọi là chúng sanh.

## Bồ-tát tạo nhân {- #bo-tat-tao-nhan}

Đến phần giác tha, Bồ-tát thấy bổn phận mình phải đem sự giác ngộ lại cho mọi
người. Để đạt mục đích ấy, Bồ-tát phải tạo dựng cho mình đầy đủ những điều thiết yếu
này:  

Một là Bồ-tát phải thông suốt Phật pháp *(nội minh)*. Vì mục đích dạy người tu
theo đường lối giác ngộ mà không thông suốt giáo lý Phật thì không thể thực hiện
được.  

Hai là Bồ-tát phải thông hết các môn tâm lý học, xã hội học, khoa học... *(ngoại
minh)*. Có suốt thông các môn này thì sự giáo hóa không bị chướng ngại.  

Ba là Bồ-tát phải biết các môn y dược *(y phương minh)*. Trị cho người được lành bệnh, chỉ dạy đạo
lý cho họ rất dễ dàng, vì họ có cảm tình sẵn sàng nghe mình dạy.  

Bốn là Bồ-tát phải học các nghề nghiệp thật hay thật khéo *(công xảo minh)*. Cần giúp đỡ mọi người,
chúng ta phải có tài giỏi nghề khéo, vừa chỉ dạy dân chúng, vừa gầy được nền kinh tế
tốt đẹp cho đồng bào. Nhờ tài nghệ đặc biệt của mình, người ta mới đến cầu học, là cơ
hội tốt để giáo hóa họ.  

Năm là Bồ-tát phải giỏi ngoại ngữ *(thanh minh)*. Muốn tiếp xúc
với nhiều hạng, nhiều giống người, cần phải biết nhiều thứ tiếng. Biết tiếng họ, chúng
ta mới dễ thông cảm và giáo hóa họ.  

Tạo dựng cho mình đầy đủ năm điều kiện này,
Bồ-tát mới làm tròn sự nghiệp giác tha. Chúng ta không thể ôm ấp lý tưởng suông rằng
*“thệ nguyện giác tha”*, khi đó nơi mình không có một chút khả năng, một ít phương
tiện thì sự giác tha trở thành vô nghĩa. Trước tiên chúng ta phải tạo dựng cho mình đầy
đủ điều kiện thiết yếu *(ngũ minh)*, sau đó mang hành lý lên vai tiến trên đường giác
tha, chúng ta mới làm tròn nhiệm vụ.

Tạo dựng cho mình đủ năm điều kiện trên rồi, Bồ-tát còn phải ứng dụng bốn
việc thì sự giáo hóa mới dễ thành tựu:  

Một là Bồ-tát phải sẵn sàng giúp đỡ tiền bạc của
cải hoặc sức lực của mình khi người cần. Nhờ sự giúp đỡ người ta dễ có cảm tình,
nhiếp hóa họ mới được *(bố thí nhiếp)*.  

Hai là Bồ-tát phải nói lời hòa nhã dịu dàng dễ
mến. Dù chúng ta có giúp ai bao nhiêu, mà thốt ra những lời thô bạo họ đều bực bội
chán ghét. Khéo dùng lời hiền hòa nhu nhuyến nhiếp hóa người *(ái ngữ nhiếp)* là dễ
thành công.  

Ba là Bồ-tát phải xông pha làm những điều gì để đem lợi ích thiết thực cho
người. Chúng ta không phải chỉ nói suông, mà phải làm thật sự. Ai cần điều gì có thể
làm được, chúng ta phải nỗ lực làm giúp, để đem đến kết quả lợi ích cho họ. Nhờ bàn
tay của mình giúp họ thành công một việc, sau đó mình đem chánh pháp giáo hóa họ,
họ dễ dàng thu nhận *(lợi hành nhiếp)*.  

Bốn là Bồ-tát phải lăn xả vào trong mọi ngành
mọi nghề để cùng làm cùng sống với họ. Dễ thông cảm nhau nhất là bạn đồng nghiệp.
Đồng trong một cảnh ngộ, có bàn luận điều gì thật là dễ cảm thông. Chính chỗ chung
nghề nghiệp, chúng ta đem chánh pháp giáo hóa họ được sự chấp nhận không khó
khăn gì *(đồng sự nhiếp)*.  

Bốn điều này là phương tiện không thể thiếu của Bồ-tát trên con đường giác tha.

## Chúng sanh cầu quả {- #chung-sanh-cau-qua}

Chúng sanh không ưa tạo nhân tốt mà mong cầu quả tốt. Quả tốt làm gì đến
được, bởi không có nhân. Tuy thế mà họ vẫn ước mơ trông đợi quả tốt. Như người ta
cứ mong cho mình được sống lâu mạnh khỏe, mà không chịu cứu người giúp vật. Sanh
mạng của người không được tôn trọng mà muốn mọi người tôn trọng sanh mạng mình
là điều không thể được. Hoặc cầu mong mình được giàu có ai nấy đều ủng hộ mình,
mà không chịu làm việc bố thí, giúp đỡ người lúc cùng khốn. Lại có người cầu cho gia
đình mình hòa vui hạnh phúc vợ con đều trinh bạch, mà không chịu sống hạnh trinh
bạch với mọi người. Cũng có người cầu xin đừng ai lừa gạt mình, mà không chịu nói
lời chân thật. Quả là muốn đi bên tây mà hướng mặt về đông. Có người cầu nguyện gia
đình mình sum họp thuận hòa, mà không dùng lời khuyên can cho mọi người cùng hòa
hợp. Có người cầu mong đừng ai dùng lời hung ác nói với mình, mà mình không chịu
dùng lời hiền hòa nói với người. Có những người muốn ai cũng trình bày lẽ thật với
mình, mà mình không trình bày với người. Có những người cầu mong đừng ai tham
lam với những cái có của mình, mà mình không chịu bỏ lòng tham với những cái có
của người. Có những người cầu xin đừng ai giận hờn mình, mà mình chưa chịu hỉ xả
cho người. Có những người cầu cho mình có trí tuệ sáng suốt, mà những cố chấp tà
kiến không chịu bỏ. Bao nhiêu thứ cầu mong này không bao giờ người ta toại nguyện,
chỉ vì mong quả mà không chịu tạo nhân. Đây là sự cầu mong suông của những con
người mê muội.

## Sự sai biệt giữa Bồ-tát và chúng sanh {- #su-sai-biet-giua-bo-tat-va-chung-sanh}

Nhìn trên cái *“sợ”* giữa Bồ-tát và chúng sanh đã quá khác biệt nhau. Bồ-tát biết
là nhân đau khổ liền hoảng sợ tìm mọi cách để tiêu diệt chúng. Còn một chút mầm đau
khổ, Bồ-tát vẫn không an. Bởi vậy Bồ-tát luôn luôn ứng dụng Lục độ để khử dẹp mọi
mầm nhân đau khổ. Nhân đau khổ đã diệt sạch, quả đau khổ do đâu đến được, nên Bồ-
tát không bao giờ quan tâm đến quả. Không sợ quả mà quả cũng không đến. Ngược
lại, chúng sanh nơm nớp sợ quả khổ, mà nhân đau khổ không ngăn ngừa, cho nên càng
sợ chúng lại càng đến. Người ta khóc lóc than van khi gặp quả khổ, mà không chịu
nhìn xem quả khổ ấy do ai gây nên. Kêu trời trách đất hận người, chỉ là việc vô ích, có
khi quả khổ lại tăng thêm. Không trời Phật nào cố làm chúng ta khổ, do sự dại khờ ngu
muội của chúng ta tạo thành những nhân đau khổ, nhân đã có thì quả cố nhiên phải
đến. Khóc than oán trách chỉ làm thêm đậm nét khổ đau mà thôi.  

Đến phần giác tha, Bồ-tát cố tạo cho mình đầy đủ khả năng, nào Ngũ minh, nào
Tứ nhiếp pháp, làm thuyền bè cứu vớt chúng sanh. Bồ-tát không mong ước viển vông,
mà phải cụ thể thực tế nhìn thẳng vào lẽ thật. Cho nên phải rèn luyện mình có thật tài,
thật đức, mới nói đến sự giáo hóa mọi người. Bồ-tát không có thái độ ngây thơ như
những người nói từ bi, nói thương chúng sanh, mà chỉ có ở đầu môi. Bồ-tát là con
người hành động, mang trí tuệ và tài năng của mình đi vào cuộc đời, sống bên cạnh
quần chúng, như pháp *“Lợi hành”* và *“Đồng sự”* của Tứ-nhiếp-pháp , Bồ-tát không
phải những hình ảnh thờ ở chùa ngồi trên tòa sen hay cỡi sư tử, mà là những người có
kỹ năng khéo léo, mình mẩy lem luốc, đang loay hoay trong xí nghiệp, trong hãng
xưởng chế tạo, tự mình làm và chỉ dạy người làm, đây là *“Công xảo minh”* trong Ngũ
minh. Ngược lại, chúng sanh một bề mong cầu quả đẹp, mà không tạo những nhân tốt.
Quả đẹp làm sao có, khi nhân tốt chúng ta chẳng gieo. Muốn gặt quả mà không gieo
nhân; nếu được, quả ấy chỉ là quả gian lận, quả cướp giựt, bất chánh. Ví như có người
thấy hàng xóm trồng cam trái chín oằn cây, mê quá lại hái ngang, nếu chủ vườn thấy
đánh gãy tay, nếu không thấy hái được đem về, cũng là cái quả ăn cắp, cái quả xấu xa
nhục nhã. Cầu quả mà không chịu gây nhân, là kẻ mơ ước hão huyền, xa rời thực tế, là
kẻ lười biếng muốn ăn mà không chịu làm. Không gây nhân cầu quả, là kẻ mê muội
nên gọi là chúng sanh.

Bồ-tát và chúng sanh, nào có cách biệt bao nhiêu, chỉ chịu đổi cái nhìn. Nhìn
thẳng vào nhân để thấy rõ nhân khổ thì tránh, nhân vui thì hành là Bồ-tát. Chỉ một bề
sợ quả khổ, cầu quả vui, mà không cần biết nguyên nhân, là chúng sanh. Bồ-tát, chúng
sanh trên con người không khác, chỉ khác cái nhìn nhân và nhìn quả thôi. Như hai
người cùng đứng một địa điểm, một người xây mặt về đông, một người xây mặt về
tây; nếu người xây mặt về tây chịu quay lại nhìn về đông, thì đâu có khác nhau. Như
thế thì tất cả chúng sanh đều có khả năng làm Bồ-tát, không phải việc Bồ-tát chỉ dành
riêng cho Bồ-tát, còn chúng ta không có phần.

Xuyên suốt bài này, chúng ta thấy rõ Bồ-tát và chúng sanh cách nhau chừng kẽ
tơ sợi tóc. Chúng sanh đổi cái *“sợ quả”* thành *“sợ nhân”* là chuyển thành Bồ-tát. Thật
là mê giác chỉ khác nhau một cái nhìn. Bồ-tát ở đây rất gần gũi thân thiết với chúng
sanh. Có khi là ông thầy giảng kinh cho mọi người nghe, đâu không phải là Bồ-tát, vì
ngài thông suốt *“Nội minh”*. Có lúc là ông thầy xem mạch bốc thuốc cho mọi người,
âu cũng là Bồ-tát, vì ngài thực hành *“Y phương minh”.* Một người thợ giỏi đang
hướng dẫn chỉ dạy đàn em với nhiệt tình không vụ lợi, biết đâu chừng cũng là Bồ-tát,
vì ngài thực hiện *“Công xảo minh”*. Cho đến người bạn cùng cuốc rẫy trồng khoai mà
nói đạo lý chân thật chúng ta nghe, ai ngờ là Bồ-tát, vì Ngài thực hành *“Đồng sự
nhiếp”*. Bồ-tát là những con người thiết thân với chúng ta, chỉ khác với chúng ta ở chỗ
thấy rõ nhân ác để tránh, nhân thiện để tạo. Còn chúng ta chỉ một bề sợ quả khổ cầu
quả vui, mà không chịu thấy tường tận nguyên nhân của nó. Gần đây bên ngành y học
cũng có câu *“ngừa bệnh hơn chữa bệnh”*, cũng na ná sợ nhân hơn là sợ quả. Đạo Phật
là đạo giác ngộ, thấy nguyên nhân rõ ràng là giác, giác là Bồ-tát. Chúng ta tu theo Phật
là đi trên con đường giác, xét rõ nguyên nhân của mọi việc xảy ra để ngừa tránh là theo
hạnh Bồ-tát. Mọi người chúng ta đều có khả năng thực hiện việc *“sợ nhân”*, thì chúng
ta ai cũng làm Bồ-tát được.
