
# Chấp là gốc đấu tranh là nguồn {- #chap-la-goc-dau-tranh-la-nguon}

## Đau khổ {- #dau-kho-1}

Mọi người chúng ta đều than cuộc sống là đau khổ..., người nghèo có cái khổ
của người nghèo, người khá giả có cái khổ của người khá giả. Biết là mình khổ mà
không biết cái khổ ấy xuất phát từ nguyên nhân gì. Khi khổ đến, người ta chỉ biết kêu
Phật kêu trời than vắn thở dài, cam chịu bất lực. Người học Phật không chấp nhận như
vậy, mà phải phăng tìm tận cội rễ thử xem nó phát xuất từ đâu. Không một kết quả nào
xảy ra mà không có nguyên nhân. Vậy khổ từ nguyên nhân nào tạo ra? Chính *“cố
chấp”* là nguyên nhân đấu tranh và đau khổ. Hết cố chấp là hết đấu tranh, hết đau khổ.
Chúng ta đọc đoạn kinh Phú-lâu-na sau này thì thấy rõ.

## Đại ý kinh Phú-lâu-na {- #kinh-phu-lau-na}

Thế Tôn ở nước Xá-vệ *(Savathi)* vườn Thái tử Kỳ-đà *(Jetavana)* tịnh xá ông
Cấp Cô Độc *(Anathapindika)*, tôn giả Phú-lâu-na *(Punna)* đến xin Phật dạy pháp tu
tóm gọn để vào rừng tinh tấn tu hành.  

Phật dạy: Nếu mắt thấy sắc đuổi theo chấp chặt là đau khổ. Tai nghe tiếng, mũi ngửi mùi, lưỡi nếm vị, thân xúc chạm, ý duyên pháp
đuổi theo chấp chặt là đau khổ *(xa Niết-bàn)*. Mắt thấy sắc, tai nghe tiếng cho đến ý
duyên pháp không đuổi theo không chấp chặt là hết đau khổ *(gần Niết-bàn)*.  

Phật hỏi Phú-lâu-na: Sau khi hiểu rồi, ông đến chỗ nào tu?  

Phú-lâu-na bạch: Con đến nước Du-na ở phương Tây tu.  

Phật bảo: Dân xứ ấy hung hăng bạo ngược, họ sẽ mắng nhiếc nhục mạ ông, ông nghĩ sao?  

Phú-lâu-na bạch: Con nghĩ, chúng còn hiền thiện chưa dùng tay đánh đập con.  

Phật bảo: Chúng dùng tay đánh đập ông, ông sẽ nghĩ sao?  

Phú-lâu-na bạch: Con nghĩ, chúng còn hiền thiện không lấy đất đá ném con.  

Phật bảo: Chúng lấy đất đá ném ông, ông sẽ nghĩ sao?  

Phú-lâu-na bạch: Con nghĩ, chúng còn hiền thiện chưa dùng cây, gậy đánh đập con.  

Phật bảo: Chúng dùng cây, gậy đánh đập ông, ông sẽ nghĩ sao?  

Phú-lâu-na bạch: Con nghĩ, chúng còn hiền thiện chưa lấy dao bén đâm chém con.  

Phật bảo: Chúng lấy dao bén đâm chém ông, ông sẽ nghĩ sao?  

Phú-lâu-na bạch: Con nghĩ, chúng thật hiền thiện chưa giết con chết.  

Phật bảo: Chúng giết ông chết, ông sẽ nghĩ sao?  

Phú-lâu-na bạch: Con nghĩ, chúng thật hiền thiện đã giúp con giải thoát thân ô uế khổ đau này.  

Phật bảo: Ông nên đến đó độ những người chưa được độ.

Phú-lâu-na đến xứ ấy an cư ba tháng chứng được Tam minh và độ được năm trăm cư sĩ nam, năm trăm cư sĩ nữ.

## Giải rộng pháp tu {- #giai-rong-phap-tu}

Mắt thấy sắc đuổi theo chấp chặt là đau khổ, tại sao? Vì con mắt chúng ta nhìn
sự vật không có cái thấy đồng nhất, do còn thói quen huân tập lâu đời của mỗi người
cộng thêm vào trong đó, nên thấy có sai biệt. Thấy sai biệt mà mỗi người đều cho
mình thấy đúng sự thật thì sự cãi vã không thể tránh khỏi. Có cãi vã là có buồn khổ,
nên chấp chặt là đau khổ. Ví như năm cô đi chợ cùng vào hàng vải. Có một loại vải mà
nhuộm đủ năm màu, năm cô nhìn qua mỗi cô thích mỗi màu khác nhau. Cô thích màu
xanh cho màu xanh là đẹp, cô thích màu hồng cho màu hồng là đẹp... Nếu mỗi cô đều
khẳng định màu mình thích là đẹp tuyệt, các màu khác không thể sánh được, sẽ có trận
cãi vã nổi lên chăng? Hẳn không tránh khỏi. Cãi vã là nhân giận hờn thù địch, đưa đến
kết quả đau khổ. Ai có thể đứng ra phân giải màu nào đẹp hơn màu nào. Chân lý sẽ đi
về đâu? Chúng ta khéo biết mỗi người có cái thấy khác nhau, chỉ có cái đẹp riêng của
mỗi người, không có cái đẹp chung cho tất cả, thông cảm nhau, đừng cãi vã vô ích, đây
là biết sống không gây đau khổ. Nếu thấy sắc liền đuổi theo là nhiễm ái, có nhiễm ái là
có bảo thủ. Ái, thủ là nhân sanh tử đau khổ ở đời vị lai. Chính ái thủ cũng là nhân đấu
tranh ngay trong hiện tại. Ta thấy sắc đẹp ấy ta thích, người khác thấy đẹp cũng thích.
Nếu ta được thì người mất, ai cũng muốn được thì phải đấu tranh, có đấu tranh là có
đau khổ. Bởi đấu tranh nên phiền não, đây là nhân xa Niết-bàn.

Tai nghe tiếng đuổi theo chấp chặt là đau khổ, tại sao? Tai chúng ta nghe tiếng
cũng không đồng nhau. Bởi mỗi người do huân tập sai biệt cao thấp, nên có nhận định
khác nhau. Ví như cùng nghe một bài pháp, mà có kẻ khen hay có người chê dở, hoặc
người khen đoạn này, kẻ khen đoạn khác. Như cùng nghe một bản nhạc, người tài tử
chuyên nghiệp chê nhạc không hay, người mới bập bẹ vài nốt nhạc khen bản nhạc rất
hay. Cái nghe của chúng ta còn tùy thuộc chỗ huân tập mà đánh giá khác nhau. Nếu
bảo cái nghe của ta là chân lý, cái nghe của người khác cũng nhận là chân lý. Hai chân
lý mà sai biệt nhất định phải tranh cãi. Đã tranh cãi thì đi đến khổ đau. Nên nói chấp
chặt là đau khổ. Thế mà người đời nói: *“Cái gì tai nghe mắt thấy mới là sự thật”*. Tai
nghe tiếng mà chạy theo tiếng cũng là đau khổ. Vì tiếng có hay dở, có tốt có xấu, có
khen có chê. Nếu nghe khen ta mừng, nghe chê ta giận, nghe hay ta thích, nghe dở ta
bực, đây là gốc phiền não, là nhân đau khổ, cũng là xa Niết-bàn.

Mũi ngửi mùi đuổi theo chấp chặt là đau khổ, tại sao? Mũi chúng ta cùng ngửi
một thứ mùi, mà kẻ khen thơm người chê hôi, tùy thuộc sự huân tập khác nhau. Ví như
một trái sầu riêng, người quen ăn nói là thơm, người chưa từng ăn nói là hôi. Hai
người đồng ngửi được mùi sầu riêng, mà hai người nhận định trái nhau. Như vậy,
thơm là chân lý, hôi là chân lý? Nếu ai cũng cho mình là chân lý thì khó tránh khỏi
một trận cãi vã. Lại nữa, như mùi nước mắm biển, người quen ăn khen thơm, người
không quen ăn chê hôi. Làm sao đánh giá đúng sự thật của nó. Chúng ta quen thói,
mình nói thơm bị người khác chê hôi là nổi giận. Nhân đấu tranh từ đây phát khởi, quả
đau khổ nhân đó mà thành. Nếu chúng ta phóng tâm chạy theo mùi thơm, dễ bị chúng
phỉnh gạt, đi đến chỗ sa đọa. Đây cũng là tâm ái nhiễm, sanh ra bảo thủ, tạo thành
nhân sanh tử đau khổ ở đời sau.

Lưỡi nếm vị đuổi theo chấp chặt là đau khổ, tại sao? Lưỡi chúng ta nếm vị cũng
không nhất định giống nhau, tùy thuộc chỗ huân tập riêng của mỗi người. Chính chúng
ta cũng thừa nhận mỗi người có khẩu vị khác nhau. Nếu mỗi người chấp chặt khẩu vị
của mình là đúng thì sự tranh cãi không có ngày dừng. Ví như người quen ăn mặn khi
nấu canh nếm thử rất vừa ăn, múc bưng lên bàn gặp người quen ăn lạt nếm thử liền chê
mặn. Cả hai đều nếm đến vị canh, một bên bảo vừa ăn, một bên chê mặn. Chân lý về
bên nào? Nếu mời người thứ ba nếm thử, người này quen ăn mặn thì đồng ý với người
ăn mặn, quen ăn lạt thì đồng ý với người ăn lạt. Nếu chấp theo cái lưỡi của mình thì sự
cãi vã không tránh khỏi. Có những thức ăn người chồng thích người vợ không thích,
người cha ưa, con không ưa. Chúng ta khẳng định theo khẩu vị mình bắt mọi người
phải theo thì họ bực bội. Bực bội thì mầm đấu tranh dễ bùng nổ. Chính đây là gốc đau
khổ. Người chạy theo vị ngon đòi thỏa mãn cái lưỡi, họ phải nhọc nhằn không có ngày
cùng. Anh thợ mộc làm mỗi ngày được năm ngàn đồng *(5.000đ tiền VN)*, hai bữa ăn
đòi phải ngon, chắc anh không còn dư đồng nào để giải quyết những nhu cầu khác, và
anh sẽ không có ngày nào được nghỉ. Thích thức ăn ngon là ái nhiễm vị, có ái nhiễm
thì có bảo thủ, ái thủ là nhân sanh tử đau khổ ở đời sau, là xa Niết-bàn.


Thân xúc chạm đuổi theo chấp chặt là đau khổ, tại sao? Thân xúc chạm cảm
giác không giống nhau, tùy cơ thể mỗi người. Một người mập *(béo)*, một người ốm
*(gầy)* ở chung nhau một căn phòng. Khí hậu khoảng mười tám độ C, người mập *(béo)*
cảm thấy mát, người ốm *(gầy)* phát run. Người ốm lại đóng kín cửa sổ, người mập bực
bội mở toác ra. Thế là, sự ẩu đả phải đến. Bởi chấp chặt vào cảm giác riêng mình, nên
dễ nổ ra sự chống đối. Ở chung mà chống đối nhau là phiền não, là khổ đau. Hơn nữa,
đuổi theo xúc dục là nhân tan nát gia đình, là mầm trầm luân khổ hải.

Ý duyên pháp trần đuổi theo chấp chặt là đau khổ, tại sao? Pháp trần là bóng
dáng ngoại cảnh do huân tập in sâu vào ý căn *(não bộ)* mà thành. Ý y cứ những bóng
dáng sẵn có ấy, nhận định mọi sự việc xảy ra, giống như người mang một thứ kiếng
màu nhìn cảnh vật. Bởi sự huân tập từ mỗi gia đình, hoàn cảnh xã hội khác nhau, nên
sự nhận định của mỗi người cũng khác nhau, như mỗi người mang một thứ kiếng màu.
Chấp chặt nhận định riêng tư của mình, bắt mọi người phải giống như vậy, là không
thể được. Cho nên sự đấu tranh cãi vã xảy ra thường nhật, vì chỗ không đồng ý nhau.
Vợ chồng cãi vã đến ly dị cũng vì không đồng ý. Anh em chống đối nhau đến tình cốt
nhục phải phân ly, cũng vì không đồng ý. Cha có thể từ con, cũng vì con không giống
ý mình... Vợ chồng làm sao đồng ý nhau được? Vì vợ quen nếp nội trợ, giao thiệp với
phái nữ, còn chồng hoạt động bên ngoài, phần lớn tiếp xúc phái nam, sự huân tập hai
bên khác nhau quá nhiều, làm gì có nhận định giống nhau như một được. Thế mà đòi
mọi việc phải đồng ý nhau, có chỗ bất đồng liền sanh sự, quả là điều không hợp lý.
Cha và con lại khó đồng ý nhau. Vì cha được học hỏi huân tập hoàn cảnh khác, con
được học hỏi huân tập một hoàn cảnh khác. Nếu con giống hệt cha là con đã lạc hậu, vì
sống lùi lại hai ba thập kỷ. Hiểu như vậy, chúng ta muốn được cuộc sống vui hòa, cần
phải thông cảm nhau và xả cái chấp riêng biệt của mình, mới đem lại đời sống an lành
hạnh phúc.

Nếu ý đuổi theo pháp trần là loạn động điên đảo, là phiền lụy khổ đau. Muốn
tâm an định, ý dừng lại không chạy theo pháp trần, lúc ấy là hết khổ, gần Niết-bàn.

Trên đây là nói rộng pháp tu ngài Phú-lâu-na nhận được một cách đơn giản nơi
đức Phật. Ứng dụng pháp tu này chỉ trong vòng ba tháng Ngài chứng được Tam minh
và độ được hàng ngàn cư sĩ.

## Lý do nào ngài tu chứng nhanh chóng {- #ly-do-tu-nhanh}

### Khéo ứng dụng pháp tu {- #kheo-ung-dung-phap-tu}

Do Ngài khéo ứng dụng pháp tu đúng như thật nên
kết quả nhanh. Sáu căn là cội nguồn tội lỗi, cũng chính sáu căn là gốc giải thoát. Cho
nên mê lầm sáu căn là “lục tặc” *(sáu đứa giặc)*, tỉnh giác sáu căn là “lục thông” *(sáu
pháp thần thông)*. Chúng ta tu mà không nắm được cội rễ này, cứ xoay quanh hình
thức bên ngoài, nên tu cả đời mà ít thấy tiến bộ. Vì tu mà vẫn thấy thị phi, vẫn tranh
hơn thiệt... làm sao hết phiền não, nên càng tu càng xa Niết-bàn.

### Tâm can đảm không sợ hiểm nguy {- #tam-can-dam}

Sau khi Phật hỏi ông định đến đâu yên
tu, Ngài thưa đến phương Tây nước Du-na. Phật liền cảnh cáo dân xứ ấy hung hăng
bạo ngược..., Ngài vẫn không chút nao núng và bạch một cách thoải mái với Phật. Phật
thấy ý chí vững chãi và tâm hiền hòa bao dung của Ngài, nên đồng ý cho đi. Chính
Phật cũng thấy trước là Ngài sẽ thành công, nên bảo *“ông nên đến đó độ những người
chưa được độ”*. Nếu chỉ riêng ý chí kiên cường xem thường họa hoạn cũng chưa đủ
cho Ngài sớm đắc đạo, còn nhờ tâm đại hỉ xả dù gặp cảnh nào vẫn thấy người ta còn
tốt. Mặc người đối xử cách nào, Ngài vẫn không ôm một chút oán hờn thù giận. Ngược
lại, chúng ta thì sao? Gan dạ xông pha vào chốn hiểm nguy đã không có, ai chạm đến
bản ngã thì hận thù không thể tha. Vậy chừng nào chúng ta mới đắc đạo?

## Kinh Phạm võng cũng đồng ý trên {- #kinh-pham-vong-dong-y}

Trong kinh Phạm Võng mỗi khi kết thúc kiến chấp của ngoại đạo, đức Phật đều
nói:  

> “Chỉ Như Lai biết rõ chỗ lầm chấp đó và biết nhiều hơn nữa họ đã tin như thế nào,
> chấp như thế nào, có báo ứng như thế nào, nhưng Như Lai không hề để ý chấp trước
> nên được giải thoát tịch diệt. Như Lai biết rõ sự sanh khởi và tận diệt của thọ, biết sự
> ái nhiễm và tội lỗi của thọ, biết sự thoát ly các thọ và đem trí tuệ quán sát bình đẳng
> mà được giải thoát hoàn toàn.”  
>  
> <div class="align-right">*(Kinh Phạm Võng. Trường A-hàm tr. 261 H.T. Trí Đức
dịch.)*</div>  

Qua đoạn kinh trên, chúng ta thấy Phật biết tất cả chỗ chấp của ngoại đạo và
biết nhiều hơn, song Phật không chấp trước nên được giải thoát tịch diệt. Đây là Phật
đánh giá đầy đủ biết chấp là triền phược trầm luân, biết tất cả mà không chấp là giải
thoát tịch diệt. Đến đoạn sau, Phật biết rõ sự sanh khởi và diệt tận của thọ cho đến biết
sự thoát ly các thọ... Chữ thọ ở đây là sáu căn tiếp xúc sáu trần là xúc có cảm thọ là
thọ, ái nhiễm là ái, tội lỗi là thủ, tạo thành đau khổ đời này và nhân sanh tử đời sau. Do
Phật dùng trí tuệ quán sát bình đẳng các thọ, dù thọ lạc, thọ khổ... bản chất nó là duyên
hợp hư dối, vô thường không lâu bền nên không ái nhiễm mà giải thoát.

Lại một đoạn khác, Phật nói:  

> “Các đạo sĩ và Bà-la-môn sở dĩ chủ trương thế gian thường trú cho đến chủ trương chúng sanh hiện tại Niết-bàn, cũng bởi họ dựa vào sự xúc đối phân biệt của sáu giác quan, nếu không xúc đối thời cũng không thể có các chủ trương...
>  
> Nếu vị Tỳ-kheo nào đối với sáu xúc đối của sáu giác quan biết được một cách đúng đắn như thật về sự phát khởi, sự diệt tận, sự nhiễm ái, sự tội lỗi, và sự thoát ly nó, thì sẽ vượt ra ngoài vòng các kiến chấp sai lầm trên.”  
> 
>  <div class="align-right">*(Trường A-hàm tr 269, H.T Trí Đức dịch)*</div>  

Ngoại đạo do sáu căn tiếp xúc sáu trần cảm thọ thế nào chấp cứng thế ấy,
cho cái ta nhận được là chân lý, khác với cái nhận của ta đều sai lầm. Bởi chấp như
vậy nên kẻ này cãi vã kẻ kia, nhóm này chống đối nhóm khác. Sự cãi vã chống đối ấy
rốt cuộc không đi đến đâu, chỉ ôm ấp phiền não thù hận. Vì cái cảm nhận của họ là cục
bộ, là phiến diện, làm sao giải quyết thỏa mãn được cái toàn diện. Chỉ có những người
qua sự xúc đối, có cảm nhận, biết rõ bản thân nó do duyên hợp sanh khởi, rồi vô
thường hoại diệt, ái nhiễm nó sẽ tạo nghiệp đau khổ, gỡ bỏ nó sẽ thoát ly ngoài vòng
kiến chấp, được giải thoát Niết-bàn.

Cũng kinh Trường A-hàm, Phật có thí dụ Mù rờ voi. Câu chuyện thế này: Một
hôm nhà vua ngự tại triều muốn thử nghiệm những người mù. Vua sai các quan tìm
một số người mù dẫn đến trước sân triều và dẫn một con voi đến. Công việc ổn định
xong, nhà vua và quần thần ra trước sân triều dự cuộc thử nghiệm. Vua bảo một vị
quan sắp đặt những người mù đứng hai hàng, khoảng giữa là chỗ con voi đứng. Xong
xuôi, vị quan bảo những người mù rằng: Trước các người là một con voi, hãy tiến đến
rờ xem, rờ rồi diễn tả hình dáng con voi cho nhà vua và bá quan nghe, ai diễn tả đúng
được hậu thưởng. Sau khi ào vào mò rờ, người chụp được cái chân nói con voi giống
cây cột, người rờ nhằm cái bụng nói con voi giống cái trống, người chụp được cái đuôi
nói con voi giống chổi chà..., mỗi người trình bày con voi mỗi cách. Chính vì mình sờ
tới nắm được nên khẳng định con voi như thế, người khác cũng sờ tới nắm được cũng
khẳng định chỗ biết của mình. Vì mỗi người đều chấp chặt vào chỗ xúc chạm riêng
mình nên không ai chịu nghe ai, nổ ra một cuộc cãi vã ồn náo. Những người mù yêu
cầu nhà vua và bá quan phân giải xem ai đúng. Trường hợp này, vua và quan là người
mắt sáng thấy rõ con voi, sẽ đáp thế nào? Chỉ có cách nói rằng *“các anh đều đúng cũng
đều không đúng”*. Những người mù có thỏa mãn chăng? Hẳn họ lên án những vị này
*“ba phải”*. Bởi vì sự việc hoặc đúng, hoặc sai, không thể có vừa phải vừa sai được.
Song nhà vua và bá quan thấy rõ toàn bộ con voi, làm sao chấp nhận một bộ phận con
voi là toàn thể được, cũng không thể phủ nhận một bộ phận con voi không dính dáng
gì đến con voi. Những người mù ví dụ chúng ta chỉ xúc chạm một phần chân lý rồi
chấp chặt vào đó tranh cãi nhau. Nhà vua và bá quan thí dụ đức Phật và các vị Bồ-tát
đã giác ngộ thấy chân lý viên mãn nên không chấp, cũng không về hùa với một phe
nhóm nào. Bởi vậy nên đức Phật gọi là Nhất thiết trí và Nhất thiết chủng trí, tức là Trí
biết tất cả và Trí biết tất cả loại. Cho nên đức Phật nói: *“Như Lai biết tất cả mà không
chấp trước được giải thoát tịch diệt”*. Ngược lại, chúng ta sống trong mù tối quen rồi,
chụp được điều gì hay liền cho là cứu kính, tuyên bố cho mọi người biết, nếu có ai
thấy khác chúng ta, liền bảo họ nói bậy là sai lầm. Do đó mà sự tranh cãi càng ngày
càng tăng, khổ đau càng ngày càng nhiều. Nếu chúng ta biết, cái thấy của mình chỉ là
một góc một cạnh chân lý, nếu có ai thấy khác cũng là một góc một cạnh chân lý khác,
chúng ta và họ *“đều một phần đúng”*, bổ túc cho nhau là hay, chống đối nhau là dở.
Thế gian này, mọi người đều có cái nhìn như vậy thì sống an lạc vô biên.
Trong kinh Phật nói về tôn trọng chân lý và bảo vệ chân lý rằng: *“Nếu ai nói
vấn đề này tôi thấy như thế là đúng, đây là cái thấy của tôi”*. Người này biết tôn trọng
chân lý. Ngược lại, *“nếu ai nói vấn đề này tôi thấy như thế là đúng, người nào thấy
như tôi là phải, thấy khác tôi là sai là bậy”*. Người này không biết tôn trọng chân lý và
bảo vệ chân lý. Hầu hết chúng ta đều đứng về hàng ngũ với người sau, người không
biết tôn trọng chân lý. Vì thế chúng ta bao giờ cũng thấy mình phải, mọi người đều sai,
đây là cái bệnh muôn đời của chúng ta.

## Kinh Kim Cang Bát-nhã tinh thần cũng tương tự {- #kinh-kim-cang-bat-nha}

Hai câu hỏi chủ yếu của toàn quyển kinh Kim Cang do tôn giả Tu-bồ-đề hỏi
Phật là: “*Nếu có người thiện nam thiện nữ phát tâm cầu Vô thượng Chánh đẳng Chánh
giác làm sao an trụ tâm? Làm sao hàng phục tâm?”*  

Phật trả lời câu an trụ tâm rằng:  

*“Nếu có người thiện nam thiện nữ phát tâm cầu Vô thượng Chánh đẳng Chánh giác,
chẳng nên dấy tâm trụ nơi sắc, chẳng nên dấy tâm trụ nơi thanh, hương, vị, xúc, pháp;
nên không có chỗ trụ mà sanh tâm Vô thượng Chánh đẳng Chánh giác.”*  

Quả là Phật dạy chúng ta tu cầu thành Phật, khi sáu căn tiếp xúc sáu trần đừng khởi tâm chấp trước
sáu trần, chính cái không chấp trước đó là Phật. Ở kinh A-hàm, Phật nói *“Như Lai biết
tất cả mà không chấp trước”*. Ở kinh này, Phật nói *“cái không chấp trước đó là Phật”*.
Bởi vì có giác ngộ viên mãn mới không chấp trước, chính chỗ không chấp trước là tâm
an trụ. Vì thế Lục Tổ nghe Ngũ Tổ giảng tới câu này liền phát ngộ kêu lên: *“Đâu ngờ
tánh mình xưa nay thanh tịnh, đâu ngờ tánh mình đầy đủ tất cả! Đâu ngờ tánh mình
không sanh không diệt!..”*. Lục Tổ không chỉ thấy sáu căn không dính mắc sáu trần
thành giải thoát tịch diệt, mà còn thấy khi sáu căn không dính mắc sáu trần, tánh thanh
tịnh sẵn có của mình hiện rõ ràng, tánh này đầy đủ tất cả, tánh này không sanh không
diệt... Thế là, Ngài nhảy vọt vào Pháp thân, không còn giải thoát như Nhị thừa. Đến
đây chúng ta thấy rõ cả hệ A-hàm đến hệ Bát-nhã đều chỉ chỗ chủ yếu tu hành được
giải thoát, được thành Phật gốc từ không cho sáu căn chấp trước với sáu trần. Thành
giải thoát hay thành trầm luân cũng chỉ là sáu căn không dính mắc sáu trần hay sáu căn
kẹt chặt sáu trần. Người học đạo giải thoát phải hiểu rõ điều này.

## Kinh Lăng Nghiêm cũng đồng tinh thần này {- #kinh-lang-nghiem-cung-dong-tinh-than-nay}

Trong kinh Lăng Nghiêm, A-nan sau khi nghe Phật dạy nghĩa quyết định thứ
hai, khởi nghi vấn:  

*“... Xin nguyện đức Đại Từ thương xót kẻ chìm đắm, chính nơi
thân tâm hiện nay, chỉ cho chúng tôi thế nào gút, do đâu mà cởi, cũng khiến cho chúng
sanh khổ não vị lai được khỏi luân hồi, không sa vào ba cõi...”*

Khi bấy giờ, ông A-nan và cả đại chúng đều nghe các đức Như Lai mười
phương, số như vi trần, tuy khác miệng nhưng đồng một lời, bảo A-nan rằng:  

*“Hay thay cho A-nan! Ông muốn biết cái câu sinh vô minh là cái đầu gút, khiến ông phải
luân hồi sanh tử, thì nó chính là sáu căn của ông, chớ không phải vật gì khác; ông lại
muốn biết tính Vô thượng Bồ-đề, khiến ông chóng chứng đạo quả an vui, giải thoát,
vắng lặng, diệu thường, thì cũng chính là sáu căn của ông, chớ không phải vật gì
khác.”*  

<div class="align-right">*(Kinh Lăng Nghiêm tr. 51, Tâm Minh dịch)*</div>

Ở đây không chỉ đức Phật Thích-ca mà cả mười phương chư Phật đồng nói sáu
căn là gốc luân hồi, sáu căn cũng là gốc giải thoát. Vô minh là cái mê chấp của sáu
căn, nó lôi chúng ta vào vòng luân hồi sanh tử. Vô thượng Bồ-đề là cái tỉnh giác của
sáu căn, nó đưa chúng ta đến chỗ an lạc giải thoát... Thấy được chỗ căn bản này, sự tu
hành của chúng ta, có nơi y cứ vững chắc, chúng ta không còn ngờ vực gì trên bước
đường tầm đạo giải thoát.

Ngài A-nan tuy nghe như vậy vẫn còn ngờ, cúi đầu bạch Phật:  

*“Làm sao cái khiến cho tôi bị luân hồi, sống chết hay được an vui, diệu thường, cũng đều là sáu căn, chớ không phải vật gì khác?”*

Phật bảo A-nan:  

*“Căn và trần đồng một nguồn, cột và mở không phải hai, cái
thức phân biệt là luống dối như hoa đốm giữa hư không. A-nan, nhân cái trần, mà phát
ra cái biết của căn, nhân cái căn, mà có ra cái tưởng của trần, tướng phần sở kiến và
kiến phần năng kiến đều không có tự tánh, như những hình cây lau gác vào nhau. Vậy
nên nay ông chính nơi tri kiến, lập ra tướng tri kiến thì tức là gốc vô minh; chính nơi
tri kiến, không có tướng tri kiến, thì đó là Vô lậu Chân tịnh Niết-bàn, làm sao trong ấy
lại còn có vật gì khác.”*  

<div class="align-right">*(Kinh Lăng Nghiêm tr 453-457, Tâm Minh dịch)*</div>

Đoạn này Phật nói rõ căn trần thức đều hư dối không thật như hoa đốm trong hư
không, như bó lau dựng nương vào nhau mà không có chủ. Cái không thật, không chủ
ấy, mà chấp thấy biết của sáu căn là thật, là gốc vô minh. Đã là vô minh thì đi trong
luân hồi sanh tử. Nếu thấy biết mà không chấp tướng thấy biết là Vô lậu Chân tịnh
Niết-bàn. Bởi vì từ cái gốc không thật có sanh ra ngọn ngành hoa quả cũng đều không
thật. Không thật chấp là thật tức vô minh. Không thật biết không thật là giác ngộ. Vô
minh thì luân hồi, giác ngộ thì giải thoát. Chỉ y cứ sáu căn, mê thì luân hồi, giác thì
giải thoát, không còn pháp gì khác nữa.

## Chấp là si mê {- #chap-la-si-me}

Cuộc đời là một dòng trôi chảy linh động, không dừng ở một phút giây nào,
không đứng mãi ở một vị trí nào. Thế mà, chúng ta cố giữ nó còn mãi và nguyên vẹn
với chúng ta. Quan niệm cố giữ là gốc từ si mê, bởi vì không thấy được lẽ thật. Như
thân này là vô thường sanh già bệnh chết, mà chúng ta có chịu già, chịu bệnh, chịu
chết đâu? Chúng ta muốn trẻ mãi, muốn khỏe luôn, muốn sống hoài. Song muốn mà
không được trở thành đau khổ. Cho nên nói già khổ, bệnh khổ, chết khổ. Nếu chúng ta
thấy rõ luật vô thường như thế, không mong muốn cố giữ, thì khi già, bệnh, chết đến
có khổ chăng? Họa chăng có khổ là khổ vì thân bại hoại thôi, chớ không có khổ do tâm
cố giữ mà không được. Vì thế, người thấy rõ lẽ này không chấp trước là bớt khổ năm
mươi phần trăm (50%).

Đến cái bệnh muôn đời của chúng ta là chấp cái thấy, cái nghe, cái ngửi, cái
nếm, cái xúc chạm, cái suy nghĩ của mình lúc nào cũng đúng. Ta một bề chấp cứng cái
thấy cho đến cái suy nghĩ của mình là đúng, khác đi là sai, người cũng một bề chấp
cứng như vậy, mà hai cái thấy và suy nghĩ đều khác nhau, chắc chắn sẽ nổ ra trận đấu
khẩu, đấu khẩu mà không giải quyết được, trận đấu võ ắt phải đến. Nhỏ thì chuyện rắc
rối giữa cá nhân với cá nhân, lớn hơn giữa gia đình với gia đình, lớn nữa giữa quốc gia
với quốc gia. Ngòi đấu tranh đã châm lên, thì lửa đau khổ sẽ lan khắp. Chính vì không
suốt thấu lẽ thật, nên sẽ sanh ra chấp chặt. Cái chấp chặt ấy vốn từ si mê mà ra. Do đó,
đạo Phật chủ trương lấy ánh sáng giác ngộ, phá tan đêm tối si mê, là cứu khổ chúng
sanh. Cái cứu khổ này không có hình tướng, nên không thấy cụ thể, song cái lợi ích
sâu xa bền bỉ của nó không thể đánh giá đến được. Người đời chỉ thấy cái gì cụ thể,
cho là thiết thực, không thấy cụ thể cho là huyền hoặc. Như một gia đình nghèo khổ
khốn đốn, người chồng là cột trụ trong nhà đi đạp xích lô, mỗi ngày được năm ba
ngàn, anh mắc phải cái bệnh ghiền rượu. Chiều nào anh cũng phải ngồi quán, số tiền
kiếm được của anh đã mất hết hai phần trong quán. Vợ con anh chỉ còn một số quá
nhỏ, nên phải khốn đốn. Chúng ta thấy thương, mỗi ngày đến giúp vài lít gạo, thử hỏi
chúng ta giúp đến bao giờ gia đình này hết khốn đốn? Chỉ cách duy nhất, chúng ta phải
khéo khuyên ông chồng nhà ấy bỏ rượu. Một khi ông thức tỉnh chịu bỏ rượu, gia đình
ấy sẽ bớt khốn đốn lâu dài. Lời khuyên để ông chịu bỏ rượu không có gì cụ thể, mà kết
quả không thể lường được. Chính vì cứu khổ chúng sanh, đức Phật vạch trần cho
chúng ta thấy cái mê chấp là đau khổ, là trầm luân. Một khi chúng ta thức tỉnh bỏ được
mê chấp là an lạc vĩnh viễn.

Tóm lại, trên đây đã trình bày đầy đủ cội gốc của đau khổ trầm luân và cội gốc
của giải thoát Niết-bàn. Chủ động của hai lối đi xuống và lên là sáu căn. Mê muội y cứ
vào sự thấy biết của sáu căn mà chấp chặt, là đau khổ trầm luân. Sáng suốt thấy rõ sự
thấy biết của sáu căn là giới hạn là góc cạnh, không chấp trước là an lạc giải thoát. Con
đường tu của chúng ta thật là đơn giản, chỉ ở sáu căn giác và mê mà được vui hay chịu
khổ. Không tìm cái vui ở phương trời nào, cũng không chạy trốn cái khổ ở núi non gì.
Chuyển hướng sáu căn không chạy theo không dính mắc sáu trần là thật sự giải thoát.
Có vị Tăng hỏi Thiền sư: *“Thế nào là giải thoát?”*. Thiền sư trả lời: *“Căn trần không
dính nhau là giải thoát”*. Câu này vừa là đơn giản vừa là thực tế. Dính mắc là bị trói
buộc, là mất tự do. Không dính mắc là tự do là giải thoát, thật không có gì lạ cả. Hơn
nữa căn trần là tướng duyên hợp không thật. Nếu thấy căn trần duyên hợp như huyễn
hóa, là phá được chấp ngã *(căn)*, chấp pháp *(trần)*, mới là hoàn toàn giải thoát.
