
# Thấy thân giả dối có phải quan niệm chán đời chăng? {- #than-gia-doi-co-phai-chan-doi}

Đa số người nghe trong kinh Phật nói *“xem thân như huyễn hóa”* cho là tâm
trạng bi quan, yếm thế. Trái lại, nhà Phật thấy thân như huyễn hóa là sức mạnh để làm
lợi ích chúng sanh. Như nói *“Bồ-tát lấy thân như huyễn độ chúng hữu tình như
huyễn”*, bởi Bồ-tát thấy thân hình không thật nên sẵn sàng lăn xả vào làm việc lợi ích
chúng sanh, dù gặp khó khăn nguy hiểm cũng không ngán sợ, vì thân như huyễn có
mất cũng không gì quan trọng. Thấy chúng hữu tình như huyễn nên độ chúng sanh mà
không chấp nhân ngã. Thấy thân như huyễn, khiến người ta mạnh mẽ lên, không còn
hãi sợ, trước vạn vật biến thiên mà tâm hồn mình vẫn an nhiên tự tại... Ta hãy nghe bài
kệ của Thiền sư Vạn Hạnh:  
  
<div class="align-center">
> Thân như điện ảnh hữu hoàn vô  
> Vạn mộc xuân vinh thu hựu khô  
> Nhậm vận thạnh suy vô bố úy  
> Thạnh suy như lộ thảo đầu phô  
</div>

Dịch:  
  
<div class="align-center">
> Thân như bóng chớp có rồi không  
> Cây cỏ xuân tươi, thu đượm hồng  
> Mặc cuộc thạnh suy không sợ hãi  
> Thạnh suy như cỏ hạt sương đông  
</div>
  
Biết bao lời Phật, ý Tổ trong các kinh, luận thấy thân như huyễn đạt tinh thần
vô úy như thế.

## Thấy thân huyễn hóa là đúng lẽ thật {- #than-huyen-hoa-dung-le-that}

Phật giáo nói thân này do tứ đại hòa hợp thành nên không chắc thật bền lâu. Tứ
đại là đất, nước, gió, lửa, bốn thứ này bủa khắp trời đất vạn vật nên nói là đại. Chất
cứng trong thân là đất, chất ướt là nước, chất động là gió, chất ấm là lửa. Bốn chất này
thiếu một thì thân phải hoại. Song bốn chất này luôn luôn thù địch chống đối nhau.
Lửa không ưa nước, đất không ưa gió, ngược lại cũng thế. Khi lửa thạnh hơn nước
sanh nóng bức đau đầu; gió thạnh hơn đất sanh nhọc nhằn đau nhức. Chúng hằng
chống đối nhau, nên lúc nào thân này cũng sẵn sàng bệnh hoạn hay chực tan rã. Ta
khéo điều hòa thì thân còn an ổn, không khéo chúng sẽ băng hoại. Sự băng hoại của
thân thật bất định, một mạch máu bể, một cái sẩy chân, một luồng gió độc, một viên
đạn xuyên qua... là mất mạng. Sự hòa hợp của tứ đại thật là khó khăn không bảo đảm
lâu dài, vì chúng mang bản chất thù địch nhau. Như bốn người thù địch nhau chung
làm một công tác, nếu thiếu một trong bốn người thì công tác phải đổ vỡ. Thử hỏi,
chúng ta dám bảo đảm bốn người này hòa hợp lâu dài chăng? Và công tác họ đang làm
có thể thành tựu viên mãn không? Thật không ai dám hứa điều đó hết, vì thấy rõ tính
chất thù địch của chúng. Sự hòa hợp của bốn kẻ thù, dù ai ngu tối mấy cũng biết rất
tạm bợ mỏng manh. Thế thì, nói thân tạm bợ hư dối là nói đúng sự thật không còn nghi
ngờ gì nữa.

Chẳng những sự hòa hợp của chúng rất tạm bợ mỏng manh, chính khi đang hòa
hợp, chúng cần phải vay mượn tứ đại bên ngoài hỗ trợ mới được tồn tại. Sự vay mượn
tứ đại bên ngoài bị thiếu hay ngưng trệ, nguy cơ tan vỡ xuất hiện ngay. Lỗ mũi chúng
ta đang hít thở là mượn gió, miệng ta uống nước, ăn cơm là mượn nước, mượn đất và
lửa. Sự vay mượn ấy được thuận chiều ổn thỏa thì thân an vui khỏe mạnh. Sự vay
mượn bị trở ngại khó khăn là thân đau đớn nguy kịch. Quả thật cuộc sống an vui hạnh
phúc là do sự vay mượn và tống trả một cách an ổn điều hòa, ngược lại là sự sống bất
hạnh. Sự sống còn là nhờ vay mượn, làm sao dám nói thân này là thật, là lâu dài?

Thế mà người đời bị si mê nhiều kiếp, cứ nghĩ thân này là thật, là lâu bền, là
của ta. Thậm chí đất nước gió lửa bên ngoài là của thiên nhiên trời đất, mà một khi
mượn vào xài, liền chấp của mình. Như lỗ mũi vừa mượn không khí đem vào chưa đến
một phút, thở trả ra liền nói hơi của tôi. Nước, đất cũng chấp như vậy. Một vật gì vừa
qua thân này đều nói là của tôi, không ngờ cái tôi này cũng vay mượn nốt. Bao nhiêu
đó đủ thấy, cái si mê chấp ngã của chúng ta thật quá nặng nề. Vì chấp ngã nên mù
quáng, không thấy lẽ thật. Bởi vậy nên nghe nói thân này như huyễn hóa liền hằn học
chống đối ngay.

Nếu thân này là thật, phải có bảo đảm tồn tại trong thời gian bao lâu. Quả thật
không dám bảo đảm, làm sao nói thân này là thật được. Có người ra chợ mua hàng,
thấy món hàng vừa ý muốn mua, song còn ngại đồ giả. Chàng ta hỏi cô bán hàng: Đây
là đồ thật hay đồ giả? Cô bán hàng đáp: Đồ thật! Tôi bảo đảm ông đồ tốt lâu bền... có
thật mới dám bảo đảm, nếu giả đâu dám bảo đảm, trừ kẻ bướng. Thân này đã không,
có ai dám bảo đảm, nói giả dối là hợp lý còn gì nghi ngờ. Song nói giả dối hay huyễn
hóa để chỉ sự có mặt của nó rất tạm bợ không lâu bền, không chủ tể, chớ chẳng phải
không ngơ, không có gì hết. Có người bảo đạo Phật nói thân như huyễn hóa, tại sao
các người tu theo Phật vẫn ăn, vẫn mặc v.v... và v.v...? Biết thân huyễn hóa là thấy nó
có một cách tạm bợ ngắn ngủi, dễ tan hoại, chẳng phải là không, sự ăn mặc đối với nó
là lẽ thường có gì phải nghi. Thấy được lẽ thật tạm bợ của thân này, chúng ta phá được
cái chấp ngã sai lầm vô lý, dừng tay, không tạo nghiệp ác, đem lại sự cảm thông tương
trợ lẫn nhau, để được chút an vui trong cuộc đời tạm bợ.

## Thấy thân huyễn hóa để trừ tam độc {- #than-huyen-hoa-tru-tam-doc}

Tham, sân, si là ba con rắn độc sát hại người không thể kể xiết. Chẳng những
chúng giết hại người trong đời này, mà còn gây họa ương không biết bao nhiêu kiếp
nữa. Còn tham sân si là con người còn đau khổ. Thấy thân như huyễn hóa là lối nhìn
đúng như thật bằng con mắt trí tuệ. Con mắt trí tuệ mở sáng thì si mê tan biến là phá
được si. Si đã tan thì tham theo đó mà dừng. Tham hết thì sân không còn lý do trỗi
dậy. Bởi si mê nên thân duyên hợp hư dối ta tưởng lầm là chân thật quí báu. Do tưởng
thân thật quí, nên sanh lòng tham muốn thu góp mọi nhu cầu mà thân yêu thích. Sự thu
góp bị ngăn trở liền nổi sân lên. Thế là, từ si khởi tham, từ tham sanh sân, tạo nghiệp
gây khổ cho mình cho người. Hành giả biết rõ cội gốc của tam độc là si mê dùng cây
xẻng trí tuệ bứng tung gốc si mê lên. Gốc si mê đã tróc thì thân tham và cành lá sân
cũng đổ ngã theo, cây tam độc ngang đây sẽ khô khan rã mục. Quả là chúng ta đã tháo
được cây chốt cửa giải thoát. Bài kinh Bát-nhã bổ khuyết cho tất cả thời khóa tu tập
chủ yếu là ở chỗ này. Chúng ta tu theo đạo Phật là đi trên con đường giác ngộ, nếu
không thắp sáng ngọn đuốc trí tuệ thì mục đích giác ngộ ắt phải xa vời. Kinh Pháp Cú,
Phật dạy: *“các ông tự thắp đuốc lên mà đi, thắp lên với chánh pháp”*. Trong mười hai
nhân duyên, bắt đầu từ vô minh. Từ vô minh tiếp nối đến sanh tử là lưu chuyển. Vô
minh diệt cho đến sanh tử diệt là hoàn diệt. Do vô minh dẫn mãi đi trong luân hồi sanh
tử. Vô minh là tên khác của si mê. Chúng ta đã thấy đích thực bộ mặt ác độc của hắn
rồi, không ra tay tiêu diệt hắn, biết bao giờ chúng ta mới hết khổ. Vì thế, hành giả
thẳng tay trừng trị đích đáng kẻ ác độc này, với cây kiếm trí tuệ cầm sẵn trong tay. Bất
cứ nơi chốn nào, thời gian nào, hành giả hằng lia kiếm trí tuệ, bọn quân si mê ngã rạp
không còn một đứa dám xáp lại gần là thắng trận, trên đường tiến đến thành giác ngộ.
Ngược lại, là kẻ bại trận không thể cứu.

## Thấy thân huyễn hóa đạt đến không huyễn hóa {- #dat-den-khong-huyen-hoa}

Lý do không bi quan của đạo Phật là thấy thân huyễn hóa để đạt đến không
huyễn hóa. Không phải như những kẻ phàm phu tục tử, có lúc nhàn hạ ngồi yên suy
gẫm cuộc đời, thấy nó ngắn ngủi tạm bợ đâm ra chán chường kinh hoảng. Thấy cuộc
sống đi vào ngõ cụt, họ ê chề chán ngán có khi liều mình tự tử. Hành giả dùng trí tuệ
quán sát thấy thân đúng lẽ thật, nó hư dối tạm bợ không có gì đáng quí. Song lại có cái
chân thật tàng ẩn trong ấy, chỉ có người đạt đạo mới thấy được. Ta hãy nghe ba câu
trong bài ca Chứng Đạo của Thiền sư Huyền Giác:  
  
<div class="align-center">
> Huyễn hóa không thân tức pháp thân  
> Pháp thân giác liễu vô nhất vật  
> Bản nguyên tự tánh Thiên Chân Phật  
</div>
  
Ngay trong thân không thật huyễn hóa này tức là Pháp thân. Giác ngộ pháp thân
thấy không có một hình tướng sự vật gì. Pháp thân này cũng gọi là Bản nguyên, Tự
tánh, Thiên Chân Phật. Pháp thân là tên khác của tâm thể lặng lẽ, tràn đầy trong sáng
của mọi chúng ta. Nó không có hình tướng nên không bị vô thường, không dấy động
nên không sanh diệt, hằng trong sáng nên chẳng phải không ngơ. Vì chúng ta quen
nhìn cái gì cũng theo hình tướng, theo dấy động mới cho là có, ngược lại bảo là
không? Để sáng tỏ ý này, chúng ta nghe lời đối đáp của Thiền sư Hoài Nhượng với
Lục Tổ. Sư đến Tào Khê, Lục Tổ hỏi: Ở đâu đến? Sư thưa: Ở Tung Sơn đến. Tổ hỏi:
Vật gì đến? Sư thưa: Nói in tuồng một vật tức không trúng. Tổ hỏi: Lại có tu chứng
chăng? Sư thưa: Tu chứng tức chẳng không, nhiễm ô tức chẳng được. Tổ bảo: Chính
cái không nhiễm ô này là chỗ hộ niệm của chư Phật, ngươi đã như thế, ta cũng như thế.

Tâm thể lặng lẽ tràn đầy trong sáng có sẵn trong mọi người, nên nói là bản
nguyên, là tự tánh. Tại vì vọng tưởng dấy khởi liên miên, khiến chúng ta chỉ thấy vọng
tưởng, không thấy được tâm thể này. Bởi chỉ thấy vọng tưởng nên chấp nhận vọng
tưởng làm tâm mình, hài lòng ngang đây, cam chịu nó lôi chạy trong lục đạo luân hồi.
Mỗi vọng tưởng dấy lên, hay mỗi niệm khởi, đã cắt xén tâm thể tràn đầy thành những
mảnh vụn. Những mảnh vụn này tung tóe lên che khuất tâm thể lặng lẽ tràn đầy trong
sáng. Như mặt biển lặng lẽ tràn đầy trong sáng, một cơn gió mạnh thổi qua, những
lượn sóng trỗi dậy nối tiếp, đã cắt xén mặt biển phẳng lì thành vô lượng mảnh vụn,
đang săn đuổi nhau. Khi này, người ta nhìn không còn thấy mặt biển phẳng, chỉ thấy
bao nhiêu lượn sóng gầm thét rượt bắt nhau.

Sóng đã dậy làm sao dừng? Chỉ khi nào gió lặng. Sóng tâm muốn dừng chỉ khi
nào gió nghiệp lặng. Vọng tưởng dấy lên đều có đối tượng. Ngã và pháp là đối tượng
chủ yếu của vọng tưởng. Nghĩ cái gì? Nghĩ về ta, về người hay vạn vật. Thấy thân
duyên hợp như huyễn, cảnh duyên hợp như huyễn là vô hiệu hóa gió nghiệp. Đã biết
thân cảnh hư dối còn gì phải bận lòng, đối tượng đã phá vỡ thì vọng niệm không còn
chỗ tựa để phát sanh. Thế là gió nghiệp lặng, sóng vọng niệm từ từ im bặt, chỉ còn mặt
biển tâm lặng lẽ tràn đầy trong sáng như xưa. Công tác quan trọng của người tu là trí
tuệ Bát-nhã, nhờ nó chúng ta mới phá được mê lầm muôn kiếp. Nó góp công lớn lao
trong việc đem lại an bình cho tâm thể.

Vọng niệm dấy khởi là loạn động, sanh diệt, là cắt xén vụn vặt, là che phủ ngàu
đục. Có vọng niệm thì không thể thấy được tâm thể lặng lẽ tràn đầy trong sáng. Vì thế,
mọi người đều có tâm thể lặng lẽ tràn đầy trong sáng mà ít người nhận ra. Đã không
nhận ra, dù tu hành cũng không tin mình thành Phật. Đây là nguyên nhân lui sụt của đa
số người tu. Nghe trong kinh nói có Chân tâm, Phật tánh, Tri kiến Phật..., thực tế
không bao giờ họ nhận thấy mặt mày của nó. Tu lâu rồi, họ xoay ra lo cất chùa to, tổ
chức lễ lớn... lấy đó làm Phật sự, việc giác ngộ giải thoát xem như vô phần. Muốn thấy
chân tâm, Phật tánh, trước tiên chúng ta phải dừng vọng niệm. Vọng niệm đã dừng thì
tâm thể lặng lẽ tràn đầy trong sáng hiện tiền, chẳng cần cầu mong trông đợi cũng tự
thấy. Song vọng niệm không phải dễ dừng, nó đã thành một dòng sanh diệt liên tục
trong chúng ta. Để chận đứng nó, trước tiên chúng ta phải đập nát đối tượng chủ yếu
làm cơ sở phát sanh của nó là ngã và pháp. Dùng trí Bát-nhã thấy ngã pháp như huyễn
hóa, là chiếc búa thần đập tan đối tượng chủ yếu của vọng niệm. Đối tượng đã đổ vỡ
thì vọng niệm còn nương đâu phát sanh. Thế là, nhờ trí tuệ Bát-nhã thấy ngã pháp như
huyễn hóa, hành giả đạt đến tâm thể chân thật không huyễn hóa.

## Bi trí tòn đủ {- #bi-tri-tron-du}

Trí tuệ khai phát, hành giả tháo gỡ lần những mối rối bòng bong trong tâm tư.
Đến khi mọi việc suôn sẻ, trí giác tròn sáng là xong phần tự giác. Phần giác tha do tâm
từ bi thúc đẩy, đến lúc viên mãn thì công phu hành giả mới được tròn đủ. Khi thực
hiện giác tha, hành giả phải chuẩn bị thế nào? Tâm từ bi là ban vui cứu khổ. Chúng
sanh có nhiều loại khổ, không ngoài hai thứ, khổ về vật chất, khổ về tinh thần. Khổ về
vật chất tuy cấp bách song không trầm kha miên viễn bằng khổ về tinh thần. Thể hiện
lòng từ bi bằng hành động bố thí, trong ba thứ bố thí, tài thí là đứng đầu. Vì thích ứng
với nhu cầu cấp bách vật chất, nên phải thực hiện tài thí trước. Người đang đói rét mà
mời đi nghe pháp là việc làm của kẻ dại khờ. Trước nhất, chúng ta phải cho họ có cơm
ăn, cả áo mặc, sau mới hướng dẫn về đạo lý thâm sâu. Do đó, pháp thí Phật đặt sau tài
thí. Phật tử muốn cứu người thoát khỏi cái khổ trầm kha, miên viễn của tinh thần,
trước phải lo giúp đỡ người giảm bớt cái khổ về vật chất. Vì thế, tuy thấy thân như
huyễn hóa, các pháp như huyễn hóa, chúng ta vẫn phải cần cù lao động làm ra nhiều
tài sản của cải để giúp những người cần giúp, nhiên hậu mới đem chánh pháp hướng
dẫn giáo hóa họ. Thấy thân như huyễn, các pháp như huyễn, để rồi nhìn cảnh ngắm
trăng nhịp đùi ngâm thơ, là người không có lòng từ bi, không hiểu thấu ý nghĩa Phật
dạy. Hoặc gặp ai cũng cố gắng khai mở trí Bát-nhã cho họ, mà không đếm xỉa gì bản
thân người đang no hay đói, là kẻ thuyết pháp chẳng hợp thời cơ. Vì muốn cứu cái khổ
trầm kha miên viễn tinh thần của mọi người, chúng ta phải cố gắng nỗ lực cứu cái khổ
cấp bách vật chất cho họ trước đã. Được vậy, sự tự giác giác tha, chúng ta mới tròn đủ.
Tự giác là trí, giác tha là bi, đạo Phật chủ yếu đưa người đến giác ngộ, nên bi trí đều
cùng một chữ giác.

## Kẻ si mê người trí tuệ can đảm hy sinh {- #si-me-tri-tue-hy-sinh}

Kẻ si mê can đảm hy sinh không ngoài ba yếu tố chính là tham lam, sân hận, si
mê. Vì tham danh, tham lợi, tham sắc..., họ can đảm hy sinh, vì đam mê không mãn ý,
họ can đảm hy sinh, vì nóng giận hận thù, họ can đảm hy sinh. Sự can đảm hy sinh của
họ do động lực bên ngoài thúc đẩy. Họ can đảm trong cái sợ sệt, hy sinh trong cái liều
lĩnh. Người đời muốn lợi dụng lòng can đảm, hy sinh của họ, bèn cám dỗ bằng danh
lợi, kích động bằng hận thù, xây dựng bằng lý tưởng. Bởi không tự chủ được, họ phải
làm theo cái gì mà người khác muốn họ làm. Cuộc sống của họ xem ra rất ngang dọc
anh hùng, song là cái anh hùng của người khác tạo nên. Họ hy sinh trong cái tự cao,
ngã mạn, hoặc trong nhắm mắt đánh liều.

Người trí tuệ can đảm hy sinh do nhận chân lẽ thật, vì lòng từ bi cứu khổ chúng
sanh. Khi thấy rõ thân này duyên hợp như huyễn, chúng sanh không biết chấp là thật,
gặp cảnh khổ liền kinh hoàng, hoảng sợ. Người trí tuệ thấy thế dám hy sinh thân mình
để đem sự an vui cho người. Đôi mắt trí tuệ với lòng từ bi, người trí tuệ can đảm hy
sinh giúp người, cứu vật, không do động lực nào khác thúc đẩy. Nói can đảm hy sinh,
mà thật không có gì đáng hy sinh. Bởi thấy thân như huyễn hóa, sự còn mất có đáng
gì, gọi là hy sinh. Cho nên, hy sinh cho mọi người, vẫn không thấy có mình hy sinh,
đây là tâm hồn Bồ-tát. Bồ-tát thấy chúng sanh khổ coi như mình khổ, xả thân mình
giải khổ cho người là việc làm dễ dàng thường nhật của Bồ-tát.

## Kết thúc {- #ket-thuc-than-gia-doi}

Qua những lý do trên, chúng ta được quyền khẳng định rằng thấy thân giả dối là
đúng lẽ thật, là diệt trừ tam độc, là giải thoát sanh tử, là tích cực vì người, là can đảm
hy sinh, không phải là quan niệm bi quan yếm thế. Mọi khổ đau, mọi hèn nhát, phát
nguồn từ bản ngã khổng lồ. Phá tan được bản ngã này, có sự lợi ích nào chẳng dám
làm, sự đau khổ nào mà chẳng dám cứu, sự hiểm nguy nào mà chẳng xông vào. Bồ-tát
Địa Tạng đâu không nói *“ta không vào địa ngục, ai vào địa ngục”*. Có phải chăng là
một sức mạnh vô biên, khi thấy thân không thật. Chỉ trừ bọn phàm phu, sau khi trà dư
tửu hậu, ngồi suy ngẫm cuộc đời, thấy kiếp sống mỏng manh cuộc đời tạm bợ, nảy sanh
ra quan niệm chán đời. Với cái nhìn của bọn người này, không dính dáng gì với trí tuệ
Bát-nhã. Trí tuệ Bát-nhã không rời từ bi. Bi trí viên mãn mới tròn Phật quả.
