
# Số mạng nghiệp báo đồng hay khác? {- #so-mang-nghiep-bao-dong-hay-khac}

Sự có mặt con người trong thế gian này, trọn một đời từng trải qua những cuộc
thành bại, thạnh suy, nhục vinh, vui khổ... dường như có sự an bài đâu sẵn. Cái gì an
bài đời sống con người? Nhà Nho gọi là số mạng hay thiên mạng. Họ cho rằng con
người sanh ra mỗi mỗi đều do số định sẵn, hoặc trời sắp đặt cho. Như câu “nhân
nguyện như thử thiên lý vị nhiên” *(người mong như thế, lẽ trời chưa vậy)*. Hoặc nói:
“Thiên võng khôi khôi, sơ nhi bất lậu” *(Lưới trời lồng lộng, thưa mà chẳng lọt)*. Chỉ
do số trời đã định không ai thoát ra ngoài được. Nhà Phật nói là nghiệp báo. Tất cả
chúng sanh có mặt trong vũ trụ đều do nghiệp trước tạo nên, phải chịu quả báo hiện
nay. Hai bên đều thừa nhận có cái sẵn từ đời trước quyết định cho cuộc sống hiện tại.
Vậy hai thuyết này đồng hay khác?

## Đồng {- #so-mang-nghiep-bao-dong}

Đứng về mặt sẵn có, hai bên đều thừa nhận như nhau. Con người sanh ra không
phải bỗng dưng mà có, đều mang sẵn cái quá khứ còn lưu lại. Vì thế, có kẻ sanh ra đã
sẵn sàng cho một cuộc sống sang cả sung túc, có người sanh ra gặp lầm than nghiệt
ngã. Tại họ chọn lựa chăng? Hẳn là không. Tại sao có sự bất công tàn nhẫn ngay từ
buổi đầu như thế? Nho nói: *“số trước đã định”*, Phật nói: *“Nghiệp trước gây nên”.* Cả
hai đều thừa nhận có cái sẵn từ trước. Song một bên nói số, một bên nói nghiệp, không
đồng nhau.

## Khác {- #so-mang-nghiep-bao-khac}

### Nguyên nhân {- #nguyen-nhan-khac}

Nói số định hay trời định cũng tương tợ. Số do ai đặt ra, hẳn là trời hay đấng
thiêng liêng tối thượng nào đó. Đã do trời định sẵn sự có mặt của ta; ta là công cụ của
Ngài, trọn một đời ta phải hành động theo cái khuôn định sẵn ấy. Quả thật đời sống
của ta không có giá trị gì hết. Nếu số định cho ta vui thì ta được vui, số định cho ta khổ
thì ta phải khổ. Ta khó bề thoát khỏi số phận ấy. Số hay trời định cho thân phận ta, mà
thật tình ta không biết gì về cái tột cùng ấy hết. Thật là gởi gấm thân phận mình cho
một cái viển vông mơ hồ.

Nói do nghiệp báo nên có mặt trên thế gian này để đền trả. Nghiệp từ đâu có?
Nghiệp do những tâm tư hành động của mình từ đời trước gây ra. Nếu đời trước hành
động thiện nhiều thì đời nay ta sanh ra gặp hoàn cảnh tốt, mọi việc như ý. Nếu đời
trước hành động ác thì đời này ta sanh ra trong hoàn cảnh xấu xa bất như ý. Thế là,
hiện nay ta sanh ra trong hoàn cảnh tốt hay xấu đều do hành động tốt xấu của ta đời
trước chiêu cảm. Ta là chủ nhân sắp đặt lấy cuộc sống hiện tại cho mình. Quyền tối
thượng định đoạt là ở chúng ta, không ai khác. Kinh Nhân Quả nói: *“Muốn biết nhân
đời trước, chỉ xem quả hiện tại đang thọ; muốn biết quả đời sau, chỉ xem nhân gây tạo
trong đời này”* (Dục tri tiền thế nhân, kim sanh thọ giả thị; yếu tri hậu thế quả, kim
sanh tác giả thị).

### Xuất phát {- #xuat-phat-khac}

Mọi khổ vui của con người do số định sẵn. Con người phải chấp nhận số phận
của mình, gặp hoàn cảnh nào cam chịu trong hoàn cảnh ấy. Nếu người gặp cảnh khắc
nghiệt quá, chịu không nổi, họ đâm ra oán trời trách đất. Họ cho rằng trời đất đã chơi
xấu với họ, đày ải họ, xử nghiệt ngã với họ, họ sống trong oán trách hận phiền.

Khổ vui do nghiệp chúng ta gây nên, dù gặp hoàn cảnh nào, chúng ta cũng can
đảm nhận chịu, không than thở oán trách ai. Mọi việc đều tại sự ngu khờ vụng dại của
ta trước kia gây ra. Ta phải vui vẻ nhận chịu, chỉ cần khôn ngoan đừng tiếp tục sự ngu
khờ như trước nữa. Ta làm ta chịu, nhận lấy trọng trách của mình. Không ai để chúng
ta van xin, không ai để chúng ta oán trách. Can đảm nhận lấy trách nhiệm, vui vẻ để trả
mối nợ tiền khiên.

### Cảm thọ {- #cam-tho-khac}

Số đã định thì chúng ta bất lực, làm sao đổi được số. Nhất là số trời còn ai dám
can thiệp vào. Trời đã định như vậy, chúng ta phải chịu như vậy. Người biết an phận,
không dám trái lòng trời.

Nghiệp thì biến chuyển, bởi vì nghiệp do hành động mà có, khi xưa ta hành
động theo ngu tối nên chiêu cảm quả khổ, nay đổi lại ta hành động theo tâm hồn trong
sáng thì quả khổ cũng suy giảm. Như trước ta xử sự xấu với một người bạn, gây ra sự
buồn phiền hờn giận, nay ta hối cải xử sự tốt với bạn, sự hờn giận trước dần dần suy
giảm. Hành động luôn luôn thay đổi, nghiệp cũng theo đó mà đổi thay. Nói nghiệp
không phải cái cố định cứng ngắc, mà chuyển biến linh động tùy thuộc tâm tư và hành
động con người. Vì thế, nếu trong hiện tại chúng ta cảm thọ cảnh vui hay khổ, biết do
nghiệp lành hay dữ trước kia tạo nên. Nếu hiện nay chúng ta chuyển tâm niệm hành
động thì sự cảm thọ cũng theo đó mà chuyển.

### Hoán cải {- #hoan-cai-khac}

Số mạng đã định thì làm sao đổi được. Cho nên nói số mạng đã định, con người
đành bó tay cúi đầu nhận lãnh, không ai có thể cưỡng được số. Con người hoàn toàn
bất lực dưới mệnh lệnh của đấng tạo hóa đã định sẵn.

Nghiệp do mình tạo, chính mình có quyền thay đổi nghiệp xấu thành nghiệp tốt.
Trước kia mình học nghề trộm cắp, sau này mình học nghề thợ mộc thợ nề. Nghề
nghiệp do sở thích của mình học tập mà thành. Trước mình dại khờ thích việc làm
không hay, sau mình nhận thức được đổi thành nghề tốt. Nghề nghiệp đổi thay tùy
theo tâm tỉnh giác của mình, đổi sang nghề nghiệp mới thì nghề nghiệp cũ từ từ phai
nhạt. Vì thế, nói nghiệp là sửa đổi, cố gắng tích cực chớ không có nghĩa cam chịu đầu
hàng. Tuy nhiên, có thiểu số người học Phật mà thiếu nghị lực, không có ý chí, họ
không vượt qua được những trở ngại của nghiệp cũ, đành cam bó tay đầu hàng rồi đổ
thừa tại nghiệp của tôi. Như đồng thời ghiền rượu, đồng biết rõ tai hại của rượu, cùng
hứa bỏ rượu, song anh A thì bỏ rượu được, anh B lại bỏ không được. Vì anh A đủ nghị
lực giàu ý chí, khi quyết định bỏ là can đảm bỏ, nên thắng trận. Anh B thì không có ý
chí, thiếu nghị lực, tuy cũng muốn bỏ rượu mà khi bị cơn ghiền hành hạ không kham
chịu, đành thua trận.  

Nghiệp chuyển được, song đòi hỏi giàu ý chí, đủ nghị lực.

### Định chế {- #dinh-che-khac}

Nói số mạng là do một đấng quyền lực tối cao, qui định hết mọi sanh hoạt của
chúng sanh trên thế gian này. Chấp nhận số mạng là con người thừa nhận và cam đặt
mình lệ thuộc vào quyền lực đấng thiêng liêng ấy. Vì thế, số mạng phù hợp với thể chế
quân chủ phong kiến, con người bị một đấng quân vương chi phối toàn bộ cuộc đời.

Nói nghiệp là quyền năng trong tay mình định đoạt. Cuộc sống đời này và đời
sau do mình an bài lấy. Muốn an vui do mình, muốn đau khổ cũng do mình. Ta là chủ
của mọi cuộc sống, nếu ta còn muốn tiếp tục. Không ai thay ta sắp đặt cuộc khổ vui,
chỉ có ta mới là người ban vui cứu khổ cho ta. Ta phải sáng suốt gan dạ chọn lựa một
cuộc sống đẹp đẽ vui tươi trong hiện tại và mai sau. Tự ta vạch sẵn một lối sống cho
ta, tự ta tô điểm đời ta cho tươi sáng. Nếu có khổ đau đến với ta, ta hãy cười, vì đây là
hành vi vụng dại ngày trước của mình. Chúng ta trả và chuyển những cái gì không hay
của quá khứ, đồng thời xây dựng những điều an vui hạnh phúc cho vị lai. Mọi quyền
lực trong tay chúng ta, thật thỏa thích thay! Cuộc sống của chúng ta là cuộc sống tự do
tự chủ. Cho nên, lý nghiệp báo thích ứng thể chế dân chủ tự do của nhân loại hiện nay.
Ta là chủ ta có quyền chọn lựa người thay ta lo việc nước việc dân.

## Phê bình {- #phe-binh-so-mang-nghiep-bao}

Nói số mạng là mơ hồ không xác thực. Nghiệp báo là thực tế rõ ràng. Thuyết số
mạng đưa con người đến chỗ vô trách nhiệm về hành động của mình. Nghiệp báo dạy
người nhận lấy trách nhiệm do mọi hậu quả tốt xấu đến với mình. Số mạng khiến con
người thụ động, tiêu cực, phó thác, liều lĩnh. Nghiệp báo xây dựng con người chủ
động, tích cực, nỗ lực và sáng tạo. Số mạng tập con người yếu đuối, an phận, đầu
hàng. Nghiệp báo chỉ cho ta phải cố gắng, can đảm và thăng tiến. Số mạng thích hợp
với thời quân chủ phong kiến. Nghiệp báo thích hợp với thời dân chủ tự do. Ứng dụng
thuyết nghiệp báo trong cuộc sống, chúng ta thấy mình đồ sộ hiên ngang, đầy đủ quyền
năng trong công cuộc kiến tạo con người và vũ trụ.

## Nghiệp báo không thật {- #nghiep-bao-khong-that}

Tuy thuyết nghiệp báo thực tế, chủ động, tích cực...Song cuối cùng nhà Phật nói
nó không thật. Bởi vì nghiệp do hành động tạo tác của con người. Hành động là tướng
sanh diệt, cái gì sanh diệt nhà Phật đều cho là hư dối.  

Trong bài Chứng Đạo Ca của
Thiền sư Huyền Giác có hai câu “liễu tức nghiệp chướng bản lai không, vị liễu ưng tu
hoàn túc trái” *(liễu ngộ tức nghiệp chướng xưa nay không, chưa liễu ngộ cần phải đền
nợ trước)*. Có Thiền khách hỏi Thiền sư Cảnh Sầm ở Trường Sa: Tổ Sư Tử liễu chưa
mà bị vua nước Kế-tân chặt đầu? Tổ Huệ Khả liễu chưa mà bị chết trong khám? Thiền
sư Cảnh Sầm đáp: Đại đức chưa hiểu nghĩa nghiệp chướng. Thiền khách hỏi: Thế nào
là nghiệp chướng? Thiền sư Cảnh Sầm đáp: Bản lai không.  

Qua câu chuyện này, đa số
người không hiểu gì cả. Sự thật là vầy, sau khi liễu ngộ Phật Tổ thấy các pháp duyên
hợp hư dối. Thân này là pháp duyên hợp nên hư dối. Hành động tạo tác từ thân phát
xuất lại càng hư dối hơn. Hành động đã hư dối thì nghiệp do hành động tạo thành làm
sao thật được. Bởi thấy nghiệp hư dối nên xem thường không quan trọng, có đến cũng
như trò chơi, có gì phải kinh hoảng sợ hãi. Cho nên khi vua nước Kế-tân muốn hại Tổ
Sư Tử, cầm dao đến trước Tổ hỏi: Ngài thấy thân năm uẩn đều không, phải chăng? Tổ
đáp: Phải. Vua nói: Ngài cho tôi cái đầu được không? Tổ đáp: Năm uẩn đã không, sá
gì cái đầu. Vua chặt đầu Ngài. Qua mắt chúng ta, thấy đó là trả nghiệp, đáng sợ, song
với Tổ đã không thấy thật, nói gì là trả.  

Cũng như ông A khi chưa hiểu đạo, bị ông B
làm vài hành động không vừa lòng, ông liền mắng chửi ông B. Thời gian sau, ông A
hiểu đạo, đúng lúc ông B trả thù mắng chửi thậm tệ hơn trước. Song ông A thấy lời nói
không thật, không có gì quan trọng, nên vẫn tươi cười không buồn, không đổi nét mặt.
Như thế ông A có trả nợ trước hay không trả nợ trước? Thật sự, nợ đã vay thì phải trả,
chỉ khác ở chỗ mê thì thấy thật, ngộ thì thấy không thật. Đã không thật thì trả cũng như
không trả. Vì thế, nói *“liễu tức nghiệp chướng bản lai không”*. Cứu kính thấy nghiệp
báo không thật, quả là thấu tột bản chất của nghiệp báo. Tuy không thật mà chẳng mất,
đây là bí yếu của đạo Phật.
