
# Phật là gì? {- #phat-la-gi}

Phật là lời nói gọn, nói đủ là Phật-đà *(Buddha)* dịch âm tiếng Phạn, dịch nghĩa
là Người Giác Ngộ. Phàm nói Phật là chỉ cho đức Thích-ca Mâu-ni *(Sakyamuni)*.
Trước đây hơn hai mươi lăm thế kỷ, ở thành Ca-tỳ-la-vệ *(Kapilavastu)* phía Bắc miền
Trung Ấn Độ, trong cung vua Tịnh Phạn *(Suddhodana)* đã sanh một vị Thái tử tên Tất-
đạt-đa *(Siddhartha)*. Lớn lên, có dịp Thái tử đi dạo bốn cửa thành, chứng kiến sự sanh
già bệnh chết của kiếp người, khiến Ngài xót xa đau đớn. Sau đó, Ngài quyết định từ
bỏ một cuộc đời sang cả trong hoàng cung, dấn thân vào rừng núi để tìm ra con đường
giải thoát sanh tử. Trải qua mười một năm trời học đạo và khổ tu, bốn mươi chín ngày
tọa thiền dưới cội bồ-đề, Ngài bỗng nhiên hoàn toàn giác ngộ, thành Phật hiệu là
Thích-ca Mâu-ni. Sau khi giác ngộ, Ngài thấy rõ manh mối lôi cuốn con người trôi lăn
trong dòng sanh tử và biết tột cùng con đường giải thoát sanh tử. Nói một cách khác,
Ngài biết rõ nguyên nhân và thành quả của sanh tử, biết rõ nguyên nhân và thành quả
của giải thoát sanh tử, đồng thời Ngài cũng biết rõ sự sanh thành và hoại diệt của mọi
sự vật. Cũng gọi sự giác ngộ ấy là “Trí biết tất cả loại” *(Nhất thiết chủng trí)*.

Chính trí tuệ này, Ngài đã được viên mãn và cũng đem nó giáo hóa chúng sanh
khiến tất cả đều được viên mãn, nên gọi là Phật.
Phật chỉ nguyên nhân đưa con người vào đường sanh tử và manh mối giải thoát
sanh tử một cách rõ ràng, là Mười hai nhân duyên: Vô minh duyên hành... cho đến sanh duyên lão tử. Đây là vòng tròn nối tiếp triền miên trong sanh tử. Muốn giải thoát sanh tử, tức là: vô minh diệt thì hành diệt... cho đến
sanh diệt thì lão tử diệt. Thế là vòng sanh tử rã rời. Nhìn vào mười hai nhân duyên,
chúng ta thấy vô minh là chủ động cuộc sanh tử, tiêu diệt vô minh là giải thoát sanh tử.
Thế thì, vô minh là đầu mối sanh tử, tiêu diệt vô minh là đầu mối giải thoát sanh tử.
Đầu mối còn thì chi mạt ngọn ngành tiếp nối sanh trưởng, đầu mối diệt thì chi mạt
ngọn ngành theo đó hết sạch.

Vô minh là gì mà có khả năng mãnh liệt như thế? Vô minh là không sáng, là mê
lầm. Ngay nơi cuộc sống này, mà không biết cái nào là giả dối, không nhận ra cái nào
là chân thật, là vô minh. Giả không biết, thật không hay, quả tang là kẻ mê lầm. Đức
Phật biết rõ những cái nào là giả dối, nhận chân cái chân thật, nên gọi là Người Giác
Ngộ. Được giác ngộ thì không còn vô minh, nên giải thoát sanh tử, đồng thời cũng có
đầy đủ mọi diệu dụng mà người đời không thể biết hết, nên nói *“giải thoát bất tư
nghì”*. Thế là, Ngài đã đạt được bản hoài trước khi phát nguyện đi tu. Cũng chính là cái
thành quả viên mãn của bao nhiêu năm Ngài khổ công đeo đuổi.

Sau khi đạt được sở nguyện, Ngài đem pháp của mình đã được chỉ dạy lại cho
mọi người, để cùng giác ngộ như Ngài. Trong thời gian ấy, Ngài đã giới thiệu bao
nhiêu bản nguyện công hạnh của chư Phật khắp mười phương cho đồ đệ nghe. Do đó,
chúng ta được biết thêm nhiều danh hiệu chư Phật khác. Đức Phật là một con người
thật, có cha có mẹ có lịch sử rõ ràng và sự giác ngộ của Ngài cũng hoàn toàn chân thật.
Chúng ta có thể kiểm chứng sự giác ngộ ấy qua Tam Tạng giáo điển của Ngài còn lưu
lại. Đó là vấn đề Phật pháp.
