
# Thế nào là Phật pháp? {- #the-nao-la-phat-phap}

Phật pháp là những điều đức Phật chứng kiến được sau khi giác ngộ, đem chỗ
chứng kiến ấy nói lại để cho mọi người hiểu biết để dứt sạch mê lầm và giác ngộ như
Ngài. Chính từ chỗ chứng kiến của Ngài nói ra, không phải do suy tư phỏng đoán như
nhiều triết thuyết khác. Vì thế, Phật pháp là những chân lý, tùy trình độ của người,
Phật nói có sai biệt: Chân lý phổ biến, Chân lý tương đối, Chân lý tuyệt đối.

## Chân lý phổ biến {- #chan-ly-pho-bien}

Chân lý phổ biến là những sự thật hiện hữu tràn đầy trên vạn vật. Những sự thật
ấy đức Phật chỉ ra, chúng ta chịu khó khảo sát một cách tinh tế sẽ thấy hiển nhiên
không sai lệch. Trước hết nhìn theo dòng thời gian, Phật nói:

### Nhân quả {- #chan-ly-nhan-qua}

Tất cả sự vật có hình tướng, có tác động đều hình thành bằng nhân quả. Nhân
quả trùm khắp cả mọi sự vật, không một sự vật nào có thể thoát ngoài nhân quả được.
Song trong nhân đến quả có chánh nhân, trợ nhân, thuận nhân, nghịch nhân nên trở
thành vấn đề phức tạp. Lại có những trường hợp vì nhân quá nhỏ nhiệm, nhân xa xôi
khiến người ta không thể thấy, không thể nhớ mà biến thành khó hiểu. Chúng ta thử
nhìn từ lãnh vực thực vật, động vật... để minh chứng lý nhân quả.

#### Về thực vật {- #ve-thuc-vat}

Không một thứ cây loại cỏ nào mà chẳng từ nhân thành quả.
Hoặc có thứ nhân của nó là hạt, có thứ nhân nó là lá, có thứ nhân nó là ngọn, có thứ
nhân nó là rễ, là thân. Từ cái nhân ấy nẩy mầm sanh trưởng thành cây, đơm hoa, kết
quả. Không có loài thực vật nào ngẫu nhiên không nhân thành quả.

Ví dụ, hạt cam là nhân, lên thành cây cam có trái cam là quả. Hạt ớt là nhân, lên
thành cây ớt có trái ớt là quả... Có nhân ắt phải có quả. Song trong ấy còn tùy thuộc
thuận nhân hay nghịch nhân, mà thành quả hay bất thành quả. Như có hạt cam là
chánh nhân, có phân, đất, nước, ánh nắng... là trợ nhân, được săn sóc vun quén là
thuận nhân, hạt cam ấy sẽ nẩy mầm sanh trưởng thành cây cam và có trái cam không
sai. Ngược lại, có hạt cam mà thiếu phân đất nước ánh nắng... thì không thể nẩy mầm
sanh cây cam, huống là có trái cam. Hoặc có hạt cam, có phân đất nước ánh nắng... mà
thiếu người săn sóc vun quén thì có thể có cây cam mà khó mong có quả cam. Hoặc có
hạt cam, có phân đất nước ánh nắng... có người vun quén, song bị sâu trùng ăn gốc,
đục trong thân cây - nghịch nhân - thì cây cam ấy sẽ bị hoại. Hoặc có trường hợp
dường như không nhân mà thành quả. Như chúng ta dọn sạch một thửa đất để trồng
trọt. Thửa đất ấy, chúng ta cuốc không còn một gốc cỏ, lượm sạch không sót một cọng
cỏ, ta tự cho là đất thật sạch. Thế mà, qua một vài trận mưa, chúng ta thấy từ lòng đất
cỏ vọt lên lấm tấm đều hết. Cỏ này từ đâu đến? Phải chăng đất sanh cỏ? Thật không
phải thế, bởi những hạt cỏ li ti đã nằm sẵn trong lòng đất mà mắt chúng ta không thể
thấy. Gặp mưa, chúng nẩy mầm lên cây là lý đương nhiên. Đây là vì nhân nhỏ nhiệm
chúng ta không thấy, nên có những nhận xét sai lầm.

Lại có trường hợp khác, một hôm Tăng chúng trong chùa chúng tôi ra thăm
vườn, bẻ được hai trái mãng cầu xiêm, từ hai cây mãng cầu cách nhau độ bốn thước
tây. Khi xẻ ra ăn, cả chúng đều ngạc nhiên, trố mắt nhìn nhau, đặt câu hỏi: Tại sao
cùng một loại, chung một thửa đất, mà trái này ngọt, trái kia chua? Mỗi người đều có
giả thuyết khác nhau, riêng tôi chỉ cười thôi. Cuối cùng, tôi giải thích cho họ nghe: Sở
dĩ hai cây cùng một loại, chung một thửa đất mà mùi vị khác nhau, do trước kia tôi lấy
hạt của hai trái mãng cầu chua và ngọt ương trồng, nên kết quả như thế. Đó là vì nhân
xa xôi khiến người ta không thể biết, nên sanh nghi ngờ. Bởi những lý do trên, nhân
quả trở thành tế nhị phức tạp, nếu người nhận xét nông nổi đơn thuần thì khó thấu triệt
được.

#### Về động vật {- #ve-dong-vat}

Tất cả loài động vật hình thành cũng từ nhân đến quả. Có loài
động vật nhân là trứng, có loài động vật nhân từ bào thai, có loài động vật nhân từ loài
khác hóa ra. Không có loài động vật nào tự nhiên mà có, song có cũng tùy thuộc chánh
nhân, trợ nhân, thuận nhân, nghịch nhân, sự sanh trưởng của nó được hoàn hảo hay suy
kém, hoặc hoại diệt chẳng hạn.

Đây là nói nhân quả trên vạn vật có hình tướng. Chúng ta có thể khẳng định
rằng *“tất cả loài sanh vật trên quả địa cầu và cả quả địa cầu này đều nằm gọn trong
lòng nhân quả”*.

#### Về tác động {- #ve-tac-dong}

Chẳng những nhân quả trùm khắp mọi loài mọi vật có hình
tướng, mà nhân quả cũng bao gồm mọi tạo tác mọi hành động của mọi loài. Ở đây
chúng ta chú mục vào loài người để thấy rõ nhân quả.

Những tác động về thân miệng của chúng ta có tánh cách lợi người, đem lại
nguồn an vui cho người, là tác động lành. Nó sẽ mang lại cho ta sự an vui ngay hiện
tại, hoặc sau này, gọi là quả lành. Những tác động có tánh cách thương tổn khiến
người đau khổ, gọi là nhân dữ. Nó sẽ chuốc lấy sự đau khổ trở về ta ngay hiện tại, hoặc
mai kia, gọi là quả dữ.

Ví dụ, chúng ta ra tay cứu giúp người hoạn nạn nguy khốn, qua cơn hoạn nạn
họ vui vẻ cám ơn ta. Chính khi thấy họ an ổn, lòng chúng ta cũng vui lâng lâng. Mặc
dù chúng ta không mong gì hơn nữa, song người thọ ơn bao giờ cũng nghĩ đến đền
đáp, nếu gặp cơ hội tốt, họ sẽ đền ơn ta. Ngược lại, chúng ta làm thương tổn khiến
người đau khổ, họ sẽ bực tức oán hờn phản kháng ta. Chính khi ấy lòng chúng ta cũng
bị bất an. Nếu mai kia họ gặp dịp thuận tiện sẽ trả thù, khiến chúng ta bị khổ đau hơn,
họ mới vừa lòng. Đó là nhân lành gặt quả lành, nhân dữ chịu quả dữ.

Nhưng cũng có những trường hợp dường như ngoại lệ, mà thật không phải. Như
chúng ta đã gieo nhân lành hoặc dữ, mà suốt đời không gặt được kết quả; vì nhân
chưa chín muồi mà báo thân chúng ta đã hoại, nhân ấy sẽ còn tiếp tục theo thời gian
chớ không mất. Hoặc có khi chúng ta không gây nhân lại chịu quả. Vì nhân xa xôi còn
lưu lại, chúng ta không nhớ.

Tác động của ý còn thầm lặng bên trong chưa phát lộ ra, song nó rất nguy hiểm.
Vì thân miệng đều do nó chủ động sai khiến. Nó dấy nhân lành thì thân miệng theo đó
tạo nhân lành, nó dấy nhân dữ thì thân miệng theo đó tạo nhân dữ. Cho nên, người
hiểu lẽ nhân quả đối với tác động của ý, phải dè dặt tối đa. Tác động của ý có nhân quả
cũng y hệt thân miệng.

Tuy nhiên, nhân quả, không phải đơn giản như nhiều người đã hiểu *“gây nhân
lành được quả lành, tạo nhân dữ bị quả dữ”*. Vẫn có những trường hợp dường như trái
lại. Bởi vì nhân quả là một dòng biến động theo thời gian. Thời gian có quá khứ, hiện
tại, vị lai thì nhân quả không thể chặn một quãng mà đoán định được. Chúng ta muốn
hiểu thấu đáo nhân quả phải căn cứ vào ba thời mà khảo sát. Nắm chắc lý nhân quả,
chúng ta sẽ có sức tự tín mãnh liệt, vì không còn lệ thuộc vào sức thiêng liêng bên
ngoài. Chúng ta tự nhận là chủ nhân ông toàn cả cuộc đời của mình.

Nhân quả là dòng biến động sanh diệt tiếp nối, nên nó là hiện thân của Vô
thường. Vì vô thường nên mãi lăn lộn trong vòng sanh diệt, cũng là thành quả của luân
hồi. Chủ thuyết nhân quả không phải cố định cứng khằng, mà linh động thăng giáng,
tùy theo sự đủ thiếu các nhân của nó. Người học Phật nhận chắc lý nhân quả, là đã có
căn bản vững vàng trên đường tiến tu. Đồng thời cũng gạt phắt những thuyết mê tín vu
vơ như: đồng bóng, bói xăm, tướng số, may rủi... Vì biết rõ mọi tác động đẹp xấu của
chúng ta, sẽ cải tạo xây dựng một cuộc đời vui khổ trong hiện tại và vị lai. Còn băn
khoăn trông đợi, thắc mắc điều gì mà phải đi coi bói tướng số? Thế là, chúng ta can
đảm nhận chịu mọi trách nhiệm hay dở do mình gây nên, không còn oán hờn kêu than
chi cả. Cũng phá tan những bệnh chấp: định mạng, nhất nhân, vô nhân. Vì biết rõ vạn
vật trên thế gian không có cái gì cố định, duy nhất, ngẫu nhiên, mà đều do nhân quả
hình thành.

### Duyên sanh {- #chan-ly-duyen-sanh}

Nhìn về mặt không gian, vạn vật đều do các duyên chung hợp thành hình. Cho
nên nói *“các pháp từ duyên sanh”*. Duyên là chỉ cho nhiều phần tử tổ hợp thành một
vật thể. Vật thể không tự có, phải do nhiều nguyên tố hay nhiều phần tử chung hợp.
Nói tới duyên sanh là không chấp nhận sự đơn thuần, mà khẳng định là hợp thể. Vạn
vật có hình tướng trên quả địa cầu và kể luôn quả địa cầu đều do các duyên chung hợp
thành hình. Cho đến những thứ không có hình tướng, chỉ có tác động, cũng thuộc
duyên sanh.

Trước khảo sát những vật có hình tướng gần chúng ta nhất. Như cái bàn viết
hiện đây của ta, trước nó không tự có, phải có gỗ, có đinh, có bào, có đục, có cưa... và
có ông thợ mộc, do sự cưa xẻ bào đục kết ráp của ông, sau mới thành cái bàn. Những
nguyên liệu dụng cụ và ông thợ mộc, đều là duyên chung hợp thành cái bàn. Nếu có
người hỏi: cái bàn này do vật gì làm ra, chúng ta đáp: do ông thợ mộc, hoặc do gỗ...
Đó là lối đáp đơn thuần, không đúng toàn thể của cái bàn. Nếu chấp lối đáp ấy đúng,
thì mắc phải bệnh thiên kiến.

Đến như cái nhà chúng ta hiện ở hoặc nhà lá hay nhà gạch, trước nó cũng không
tự có. Nếu là nhà lá, phải có cột kèo đòn tay cây lá rồi, sau chúng ta mới ráp lại thành
cái nhà. Nếu là nhà gạch, phải có gạch xi măng cát vôi ngói gỗ và thợ hồ, mới xây
thành cái nhà. Khi thành hình cái nhà, gọi là duyên hợp; khi cái nhà hư hoại đi, gọi là
duyên tan. Chỉ do duyên hợp duyên tan, thật thể cái nhà vốn không thật có.

Khảo sát như thế qua mọi sự vật, chúng ta không thấy có một sự vật nào không
phải duyên hợp mà thành. Dù vật nhỏ bé như cây kim ngọn cỏ, vật to lớn như núi biển
quả địa cầu, đều nằm chung trong một thông lệ ấy.

Cho đến những thứ không có hình tướng, chỉ thấy tác động, cũng do duyên hợp
mà có. Như điện, gió, chúng ta không thấy hình tướng nó, chỉ biết khi tác động dấy
khởi. Về điện thì có điện âm điện dương, phối hợp mới phát khởi hiện tượng. Về gió
phải có khí nặng khí nhẹ... mới có hoạt động.

Nơi con người, tư tưởng dấy khởi cũng phải có sáu cơ quan làm chỗ tựa và đối
diện với trần cảnh bên ngoài. Nếu ba phần - tư tưởng, cơ quan, trần cảnh mà thiếu một
thì, không sao dấy khởi được. Thế nên mọi tác động có ra, đều do duyên hợp mà có.

Nói duyên sanh là nhằm vào hợp thể, choán một khoảng không gian. Đã là hợp
thể thì không có tự thể và thật thể. Tự thể đã không thì, tên đặt cho sự vật cũng rỗng.
Ví như tên *“cái nhà”*, chúng ta phân tích từng viên gạch, từng miếng ngói v.v... ra, tìm
xem cái gì là *“cái nhà”*? Chỉ khi hợp thể thành hình, tạm đặt cho nó một cái tên. Cái
tên ấy chỉ có giá trị tạm thời, từ khi hợp thể thành hình, bởi trước và sau nó vốn không
có. Chính ngay khi thành hình, chúng ta phân tích từng đơn vị một, tìm tự thể cái tên
chung ấy, vẫn không có. Nên nói: *“các pháp duyên sanh tự thể là không”*. Trước
không, sau không, giữa cũng chẳng thật, nên sự có mặt của các hợp thể là hư giả huyễn
hoá. Do đó, nói đến lý duyên sanh thì, xem vạn vật đều như huyễn như hoá.

Thông suốt lý duyên sanh, chúng ta thoát khỏi hai chứng bệnh: thiên kiến và mê
lầm. Nhất là bệnh mê lầm, quả là bệnh trầm kha khó chữa trị. Vạn vật do hợp thể mà
có, hư giả không thật, lại mê lầm chấp là thật. Vì chấp thật nên theo đó có yêu ghét và
sanh tham sân. Đó là nguyên nhân mãi lăn trong vòng luân hồi sanh diệt. Biết rõ duyên
sanh hợp thể hư giả là, dứt mê lầm chuyển thành trí tuệ. Đây là cửa ngõ của lâu đài
giác ngộ.

Trong phần *“Chân lý phổ biến”*, lý nhân quả và duyên sanh là hai sự thật, tràn
đầy trên vạn vật và mọi tác động của chúng sanh. Sự thật ấy, quá khứ hiện tại vị lai
đều không thay đổi. Song nó tinh vi khó hiểu, người chịu khó nghiền ngẫm phân tích
kỹ càng mới nhận ra được. Hai sự thật này nhằm vào hai chiều của vũ trụ, nhân quả
chạy suốt chiều dọc thời gian, nhân duyên xuyên tột chiều ngang không gian. Do đó,
gọi là *“Chân lý phổ biến”*.

## Chân lý tương đối {- #chan-ly-tuong-doi}

Chân lý tương đối là những sự thật còn nằm trong đối đãi đối trị nhau. Những
sự đối đãi ấy là: sáng đối tối, lạnh đối nóng, xấu đối tốt, thiện đối ác, khổ đối vui, động
đối tịnh, sanh diệt đối vô sanh...Còn sanh hoạt trong tương đối thì, có xấu phải có tốt,
có thiện phải có ác, có khổ phải có vui..., chúng ta không thể chối cãi sự thật ấy được.
Chỗ khôn ngoan của chúng ta là, khéo lợi dụng cái này đối trị cái khác, để tiến lên
đúng nguyện vọng của mình. Như lương y biết bệnh biết thuốc, khéo dùng thuốc trị
lành bệnh cho người. Phật pháp là những phương thuốc trị lành bệnh cho chúng sanh,
nên gọi Phật là Ông vua thầy thuốc *(Vô thượng y vương)*. Ở đây, chúng ta chỉ đơn cử
vài lối đối trị để làm sáng tỏ lẽ này.

Sáng đối tối. Chúng ta biết tối không phải tự nó tối, mà do nhân duyên thiếu
ánh sáng. Nếu ta khéo tạo điều kiện - đèn dầu, đuốc, đèn điện...- cho nó ánh sáng thì
bóng tối tự mất. Ngược lại, muốn có bóng tối cũng như thế. Đây là cái tối, sáng của
hiện tượng bên ngoài. Đến cái tối, sáng tinh thần bên trong của chúng ta cũng có nhân
duyên. Nhân thiếu học, thiếu đọc sách khiến ta tối dốt. Dùng ánh sáng học tập đọc
sách... thì cái tối dốt dần dần tiêu diệt.

Nóng đối lạnh. Chúng ta nhân chạm khí lạnh, gió lạnh, nước lạnh... nên phát
lạnh run. Biết thế, chúng ta phải tạo điều kiện cho có hơi nóng để đối trị, như đốt lửa
hơ, lò sưởi ấm, mền bông trùm... Ngược lại, gặp khí nóng chúng ta phải dùng các thứ
lạnh trị, như nước, gió, máy điều hòa... Nếu lạnh trong thân thì dùng thuốc nóng trị.

Khổ đối vui. Khổ có nhiều loại: khổ do đói rét, khổ do bệnh tật, khổ do vô minh
phiền não... Nếu khổ do đói rét, chúng ta phải nỗ lực tạo điều kiện cho có ăn có mặc,
tức là lấy cái vui no ấm trị cái khổ đói rét. Nếu khổ vì bệnh tật, chúng ta phải dùng
thuốc thang điều trị, lấy cái vui khỏe mạnh trị cái khổ bệnh tật. Nếu khổ do vô minh
phiền não, chúng ta phải lấy chánh pháp của Phật trị nó. Vô minh phiền não tức là si
tham sân. Si mê là vô minh, tham sân là phiền não.

Bệnh si mê, chúng ta dùng trí tuệ điều trị. Tức là dùng pháp *“quán giới phân
biệt”* hay *“quán nhân duyên”*. Bởi chúng ta lười biếng không chịu phân tích quán sát
nên tâm trí mờ tối. Phân tích nội tâm tự thân và ngoại cảnh có chia từng phần từng giới
hạn, gọi là quán giới phân biệt. Chính sự chia chẻ quán sát ấy, khiến chúng ta thấy rõ
thân tâm này không thật, trí tuệ do đó dần dần phát sanh. Hoặc dùng quán nhân duyên,
khéo khảo sát như phần *“duyên sanh”* trong mục Chân lý phổ biến ở trước.

Bệnh tham lam, cần phải tra xét coi tham thuộc loại nào trong năm thứ tham:
tham tiền của, tham sắc đẹp, tham danh vọng, tham ăn uống, tham ngủ nghỉ.

Tham tiền của thì dùng bố thí trị. Bởi vì tham thì muốn gom góp gìn giữ, mà bố
thí thì ban cho, cứu giúp chia sớt. Chính của mình còn mang ra cứu giúp chia sớt kẻ
khác, huống là của họ mà mình muốn gom góp về, thật vô lý. Do thật tâm bố thí thì
bệnh tham tiền của từ từ lành hẳn.

Tham sắc đẹp và ăn uống phải dùng pháp *“quán bất tịnh”* điều trị. Bất tịnh là
bẩn thỉu nhơ nhớp. Xét nơi thân mình từ trong đến ngoài toàn trữ những đồ nhơ nhớp,
như cái bô đậy kín, nếu nó hở rỉ ở đâu sẽ nghe mùi hôi thối tràn ra đấy. Những thứ
nước hoa, mùi son phấn, đều là loại sơn vẽ khéo của cái bô. Nếu thật con người là sạch
sẽ, cần gì phải tô điểm. Các loại tô điểm ấy chẳng qua là, lối đánh lừa mắt mũi kẻ khác
mà thôi. Những thức ăn uống lúc còn bên ngoài dường như thơm ngon, song khi qua
khỏi cổ, sẽ biến thành những đồ bất tịnh. Thường dùng lối quán sát thân nhơ nhớp như
thế, sẽ trị lành bệnh tham sắc đẹp và ăn uống.

Tham danh vọng và ngủ nghỉ, nên dùng pháp *“quán vô thường”* điều trị. Vô
thường là chỉ cho sự đời chợt còn chợt mất không bền bỉ lâu dài. Danh vọng được đó
rồi mất đó, như sương đầu ngọn cỏ, như lằn điện chớp. Thường nghĩ xét như thế thì
còn lòng nào đeo đuổi danh vọng. Đời người mỏng manh sớm còn tối mất, lúc còn
khoẻ mạnh còn hoạt động, chúng ta phải quí tiếc thời gian, nỗ lực làm lợi ích cho mình
cho người, đừng để một đời trôi qua vô ích. Thấy rõ như vậy thì, đâu cam giết chết thì
giờ trong cái ngủ nghỉ.

Sân hận dùng pháp *“quán từ bi”* hạnh *“nhẫn nhục”* và *“hỉ xả”*, trị nó. Sân là
nóng giận, hận là hờn phiền. Nóng giận muốn la rầy đánh đập cho đã cơn giận, khiến
người phải đau khổ. Bởi vì khi giận thì không thương, lúc thương thì không giận. Từ
bi là hằng đem lòng thương chan rải khắp mọi người, xem sự vui khổ của người như
sự vui khổ của chính bản thân mình. Thương người như mình, còn lòng nào hại người
đau khổ. Tay trái lỡ đập tay phải đau điếng, tay phải cam nhận chịu không đập lại, vì
biết cùng một thân mình. Lòng thương xem người như mình, dù bị người làm đau khổ
mấy cũng nhịn chịu, không nóng giận hại lại. Nhẫn nhục là nhịn chịu. Khi cơn nóng
nổi lên cố gắng dằn ép xuống, để giữ bình tĩnh và nhịn chịu cho qua. Bởi đè ép nên chỉ
là phương tiện tạm thời không thể hết gốc nóng giận. Chỉ có quán từ bi thành công thì
gốc nóng giận mới tiêu. Hờn phiền là lòng còn ôm ấp những mối bất bình. Hỉ xả là vui
vẻ buông bỏ hết, khiến lòng nhẹ nhàng thơ thới. Ôm lòng hờn phiền là gốc bệnh hoạn
khổ đau, vui vẻ buông bỏ hết thì lòng vui tươi an ổn, bệnh hoạn khổ đau không có lý
do gì tồn tại.

Khổ từ ngoại cảnh, khổ nơi bản thân, khổ của nội tâm, chúng ta khéo lấy sự an
vui đối trị. Vui no ấm, vui khoẻ mạnh, vui sáng suốt, vui hết tham lam, vui không nóng
giận... trị lành các bệnh khổ ở trên.

Khổ là thành quả xấu do nhân duyên xấu tạo nên. Khổ về vật chất và thể xác, do
nhân duyên thiếu thốn hoặc phản nghịch của vật chất gây nên. Khổ về tinh thần, do
nhân duyên si, tham, sân... chủ động. Si là không biết đúng lẽ thật nên sanh tham, tham
không được như ý nên nổi sân. Ba thứ này là nhân chánh tạo nên quả khổ. Quả khổ là
Khổ đế, nhân duyên tạo nên nó là Tập đế. Biết rõ nguyên nhân và các duyên rồi, dùng
Phật pháp đối trị là Đạo đế. Khi mọi nhân duyên gây đau khổ dứt sạch, gọi là Diệt đế.
Đây là Bốn lẽ thật *(Tứ đế)* nằm trong pháp đối đãi và đối trị.

Động đối tịnh. Động là xao xuyến rối loạn, tịnh là yên ổn lặng lẽ. Ở đây riêng
giải thích về cách đối trị của tâm thức. Tâm thức chúng ta xao xuyến rối loạn khiến suy
yếu mờ tối. Muốn dừng sự xao xuyến rối loạn này, chúng ta phải dùng sự yên ổn lặng
lẽ đối trị. Song chúng ta phải biết rõ do nhân duyên gì khiến tâm thức xao xuyến rối
loạn. Bởi tâm thức chạy theo sự được mất tiền của, được mất sắc đẹp, được mất danh
vọng, được mất ăn uống, được mất ngủ nghỉ, mà thành xao xuyến rối loạn. Muốn dừng
sự chạy theo ấy, Phật pháp dạy chúng ta trước tiên phải giữ giới. Giới là hàng rào ngăn
chận tâm thức chạy theo ngũ dục. Kế dùng phương pháp thiền quán làm sợi dây cột nó
lại. Ngoài có hàng rào giới luật, trong có sợi dây thiền quán, con khỉ tâm thức sẽ thúc
thủ ngồi yên, dần dần ngủ lịm. Giới có năm giới, mười giới v.v... nhằm ngăn chận mọi
sự đuổi theo ngoại cảnh của tâm thức. Thiền quán có sổ tức quán, từ bi quán, bất tịnh
quán, nhân duyên quán..., cốt cột chặt tâm thức lại một chỗ, bắt buộc nó phải yên lặng.
Đây là phương pháp lấy tịnh trị động.

Sanh diệt đối vô sanh. Cặp đối này cũng gọi là sanh tử đối Niết-bàn. Sanh diệt
là nói chung cho muôn loài, sanh tử chỉ nói riêng cho loài động vật. Sanh tử đối Niết-
bàn, lại khu biệt hoàn toàn vào người Phật tử. Muôn loài hằng chịu sanh diệt, mà
không biết lẽ vô sanh, để dùng đối trị. Đức Phật sau khi giác ngộ đã thấy rõ lẽ ấy, nên
dạy đệ tử lấy vô sanh đối trị sanh diệt hay sanh tử. Vô sanh là nghĩa chánh của Niết-
bàn. Dòng tâm thức biến động là nguồn gốc sanh tử. Tâm thức biến động bởi do luyến
ái bản thân và ngoại cảnh. Nếu biết rõ cảnh vật vô thường, thân người vô ngã thì dòng
luyến ái sẽ khô kiệt, tâm thức sẽ dừng lặng. Tâm thức dừng lặng thì nhân duyên sanh
tử dứt bặt, đó là nghĩa vô sanh. Ví như gió dừng thì sóng lặng, mặt biển sẽ bằng phẳng
an lành. Luyến ái là động cơ thúc đẩy tâm thức sanh diệt, còn luyến ái thì sanh tử
không bao giờ dứt. Chúng ta yêu mến một người, người ấy vắng đi thì tìm cách gặp
lại, hoặc nơi này hay nơi khác. Lòng yêu mến thúc giục chúng ta tìm gặp nhau mãi
mãi. Chỉ khi lòng yêu mến cạn thì, sự tìm kiếm mới dừng. Trong pháp Mười hai nhân
duyên, Ái là động cơ thúc đẩy có Thủ, Hữu rồi Sanh Lão Tử ở đời sau. Ái dứt thì Thủ
Hữu không còn, làm gì có Sanh Lão Tử tiếp nối. Ái là luồng gió mạnh thổi cuốn sóng
tâm thức nổi dậy. Gió Ái dừng thì sóng tâm thức cũng theo đó mà lặng. Bức tường
chặn gió Ái không gì hơn quán các pháp vô thường, quán thân tâm vô ngã.

Bờ sông bên này là sanh tử, bờ sông bên kia là Niết-bàn. Thấy rõ như thế, hành
giả cấp bách kết bè vượt dòng sông qua bờ bên kia, qua rồi từ biệt vĩnh viễn bờ sông
bên này. Đó là quan niệm chán sanh tử cầu Niết-bàn của hàng Nhị thừa, vì còn thấy sự
đối đãi là chân thật. Cũng dùng phương pháp đối trị này, song Bồ-tát chỉ thấy là
phương tiện tạm thời, nên không mắc kẹt ưa chán.

Chân lý tương đối bàng bạc khắp thế gian. Bất luận nhân loại vật loại ngôn ngữ
tư tưởng... phát xuất đều nằm gọn trong phạm vi của nó. Chúng ta khôn khéo ứng dụng
tài tình những phản đề, để tiêu diệt chúng theo đúng đường lối vươn lên của chúng ta.
Không biết dùng, hoặc dùng sai phương pháp đối trị, mà muốn tiêu diệt chúng, không
bao giờ thành công. Thầy thuốc hay, là người khéo biết bệnh biết thuốc và dùng thuốc
trị liệu đúng phương pháp. Vì thế, Phật pháp gọi là *“phương pháp trị liệu”*.


## Chân lý tuyệt đối {- #chan-ly-tuyet-doi}

Một thực thể không lệ thuộc nhân quả, duyên sanh, thoát ngoài đối đãi là chân
lý tuyệt đối. Không thuộc nhân quả nên không sanh diệt vô thường. Không thuộc
duyên sanh nên không phải hợp tướng giả dối. Thoát ngoài vòng đối đãi nên không trị
liệu, không so sánh, không luận bàn, không suy nghĩ đến được. Thực thể này không lệ
thuộc thời gian, không bị chi phối của không gian, vượt ngoài mọi đối tượng trong vũ
trụ. Chính nó là sanh mạng là mạch sống của chúng sanh, mà chúng sanh không nhận
ra nó. Nó hiển nhiên hằng có mặt nơi chúng ta, mà chúng ta lãng quên nó một cách
đáng thương. Nó là thể chẳng sanh chẳng diệt vĩnh cửu trường tồn của chúng ta, chúng
ta không biết đến nó, đi nhận cái sanh diệt tạm bợ làm mình. Bỏ quên thực thể này là
vô minh là si mê, nhận được nó là giác ngộ là trí tuệ. Bỏ quên nó, đi theo sanh diệt là
luân hồi, nhận sống với nó là vô sanh giải thoát. Bởi thực thể này hệ trọng dường ấy,
nên chúng ta phải biết: Nó tên gì? Làm sao nhận ra nó? Nhận được nó có lợi ích gì?
Chúng tôi sẽ theo thứ tự giải quyết những thắc mắc này.

Thực thể này nguyên không có tên, trong Phật pháp tùy công dụng gắng gượng
đặt rất nhiều tên: Kinh Kim Cang gọi là Kim Cang Bát-nhã Ba-la-mật tức là trí tuệ cứu
kính như kim cang. Bởi vì trí tuệ này không có cái gì phá hoại được nó, mà nó hay phá
hoại tất cả, như chất kim cang. Kinh Viên Giác gọi nó là Viên giác tánh, là tánh giác
tròn đầy. Vì đối với các thứ chân lý, chúng ta nhận được từng phần chân lý nào thì,
giác ngộ phần chân lý ấy, nên gọi là phần giác. Chỉ nhận được Chân lý tuyệt đối này,
mới gọi là giác ngộ viên mãn. Kinh Pháp Hoa gọi là Tri kiến Phật hay Phật thừa. Bởi
vì nó là cái thấy biết Phật, là cỗ xe đưa người đến Phật quả. Kinh Hoa Nghiêm gọi là
Trí tuệ Phật. Vì nhận được thực thể này là trí tuệ giác ngộ của chư Phật. Kinh Lăng
Nghiêm gọi là Chân tâm hay Như lai tàng. Nó là tâm thể chân thật hay kho tàng Như
Lai của chúng sanh. Kinh Duy-ma-cật gọi là Pháp môn bất nhị, vì nó vượt ra ngoài
vòng đối đãi hai bên. Thiền tông gọi là Chân tánh. Nó là tánh chân thật của tất cả
chúng sanh. Lại còn những tên thông dụng là: Chân như, Phật tánh, Pháp thân, Đạo,
Bản lai diện mục..., không thể kể xiết.

Tạm biết tên thể này một cách khái quát rồi, chúng ta cần phải nhận ra mặt mày
nó mới là điều thiết yếu. Song phàm có nói năng có trình bày đều thuộc về tương đối,
làm sao diễn đạt khiến người chưa hiểu nhận được. Đây quả là điều thiên nan vạn nan.
Tuy nhiên, chúng tôi cũng gắng gượng trước tạm đặt những nguyên tắc, kế dẫn lời
Phật dạy trong kinh, sau cùng nhắc lại những phương tiện của Thiền sư, họa chăng quí
độc giả có nhận được phần nào chăng?

Chúng ta tạm đặt những nguyên tắc để khả dĩ nhận ra mặt mày của nó. Phàm
cái gì *“có hình tướng đều do duyên hợp là hư giả”*, cái gì *“có tác động là sanh diệt”*,
cái gì *“đối đãi là không thật”*. Ngược lại, cái gì *“không hình tướng, không tác động,
không đối đãi là chân thật thường còn vô sanh”*. Cái không hình tướng thì không giới
hạn chỗ nơi trong ngoài. Vừa đặt câu hỏi tìm chỗ nơi nó là sai. Cái không tác động thì
không sanh diệt, không bị vô thường theo thời gian. Đặt vấn đề thời gian với nó là sai.
Cái không đối đãi thì không còn so sánh không phân biệt. Đặt vấn đề so sánh phân biệt
với nó là sai. Thực thể này tràn đầy hiện hữu nơi chúng ta. Vừa dấy tâm tìm kiếm nó là
sai. Nó là thực thể của giác tri, không phải cái đối tượng giác tri. Nếu khởi nghĩ cầu
biết nó là sai. Nó không hình tướng, không tác động, không đối đãi, mà có mặt khắp ba
nơi ấy. Cho nên nghĩ ly khai hình tướng tác động đối đãi để tìm nó là sai. Yếu chỉ nhận
ra nó là tự ta *“trực nhận, thầm nhận”*. Lời Phật dạy, phương tiện Tổ chỉ đều là lối *“đập
cỏ rắn sợ”* hay *“vỗ nước cá đau đầu”* mà thôi. Chúng ta muốn nhận ra nó phải khéo
nhìn theo tinh thần *“ngón tay chỉ mặt trăng”*. Mặt trăng không nằm tại đầu ngón tay,
khéo nương theo ngón tay thấy mặt trăng ở tận trong hư không. Hoặc nhìn theo tinh
thần soi gương. Nhân thấy bóng trong gương, biết được mặt thật của mình, đừng chấp
bóng là thật, đợi khi xoay gương mất bóng la hoảng lên *“mất mình”*.

Đây là phương tiện tạm đặt những nguyên tắc, nương nó khả dĩ chúng ta thấy
được thực thể chính mình.

Thực thể này biểu lộ thường xuyên nơi sáu cơ quan *(mắt, tai, mũi, lưỡi, thân, ý)*
của chúng ta, mà không lệ thuộc hoàn toàn sáu cơ quan ấy. Dễ nhận dễ thấy nhất là, ở
mắt và tai. Vì thế, đức Phật khi muốn chỉ thực thể chẳng sanh chẳng diệt ấy, thường
dùng phương tiện chỉ ngay nơi mắt và tai của chúng ta.

Kinh Lăng Nghiêm có đoạn:

...Phật ở trong đại chúng đưa tay lên rồi nắm lại xòe ra, nắm lại xòe ra, hỏi ngài A-nan: Nay ông thấy cái gì?  

A-nan thưa: Con thấy bàn tay trăm báu của Như Lai ở trong chúng xòe nắm.  

Phật bảo A-nan: Ông thấy tay ta ở trong chúng xòe nắm, là tay ta có xòe có nắm hay cái thấy của ông có xòe có nắm?  

A-nan thưa: Tay trăm báu của Thế Tôn ở trong chúng xòe nắm. Con thấy tay Như Lai tự xòe nắm, chẳng phải tánh
thấy của con có xòe nắm.  

Phật hỏi: Cái nào động cái nào tịnh?  

A-nan thưa: Tay Phật động, tánh thấy của con còn không có tịnh, huống nữa là động.  

Phật khen: Đúng thế! 

Lúc đó, trong lòng bàn tay Phật phóng một làn hào quang báu soi bên phải ngài
A-nan, A-nan liền xoay đầu nhìn bên phải; lại phóng quang soi bên trái ngài A-nan, A-
nan xoay đầu nhìn bên trái.

Phật hỏi A-nan: Hôm nay tại sao đầu ông dao động?  

A-nan thưa: Con thấy hào quang báu của Như Lai phóng đến bên trái bên phải của con, con nhìn theo hai bên nên đầu tự dao động.  

Phật hỏi: Ông nhìn hào quang Phật soi bên trái bên phải nên đầu dao động, thế là đầu ông động hay cái thấy động?  

A-nan thưa: Bạch Thế Tôn! Đầu con tự động, tánh thấy của con còn chẳng dừng, huống là dao động.  

Phật khen: Đúng thế!  

Khi ấy, Như Lai bảo khắp đại chúng rằng: Nếu như chúng sanh nhận lấy cái dao
động gọi là trần, nhận lấy cái dao động gọi là khách. Các ông xem A-nan, đầu tự dao
động cái thấy không động. Lại xem ta, tay tự xòe nắm cái thấy không xòe nắm. Tại sao
hôm nay các ông lấy động làm thân, lấy động làm cảnh, từ thủy đến chung niệm niệm
sanh diệt, quên mất chân tánh làm việc điên đảo, tâm tánh đã mất chân, nên nhận vật
làm mình, ở trong luân hồi tự chịu lưu chuyển.

<div style="text-align: right">
*(Kinh Lăng Nghiêm cuối quyển 1 Hán tự)*
</div>

Qua đoạn kinh này, chúng ta nhận thấy thâm ý Phật muốn chỉ cho ngài A-nan
và đại chúng biết: Ngoại cảnh biến động sanh diệt như bàn tay Phật xòe nắm, thân này
dao động vô thường như đầu ngài A-nan xoay qua lại. Chỉ có cái thấy, xem thấy cảnh
biến động mà không bị biến động, tựa nơi đầu dao động mà không bị dao động. Cái
biến động và dao động là vô thường hư giả, tại sao chúng ta nhận nó làm thật thân
mình, làm thật cảnh của mình? Trái lại, cái thấy biết chưa từng dao động là chân thật
vô sanh, mà chúng ta lại bỏ quên nó, để cam chịu lưu chuyển luân hồi.

Lại cũng một đoạn trong kinh Lăng Nghiêm:

Vua Ba-tư-nặc đứng dậy bạch Phật: Con xưa chưa từng nghe sự chỉ dạy của
Phật, gặp Ca-chiên-diên, Tỳ-la-chi-tử đều nói: *“Thân này sau khi chết không còn gì
nữa, gọi là Niết-bàn”*. Nay con tuy gặp Phật vẫn còn hồ nghi *“làm sao phát huy chứng
biết chỗ tâm này chẳng sanh chẳng diệt?”*. Đại chúng ở đây, những người còn trong
hàng hữu lậu, thảy đều thích được nghe.  

Phật hỏi: Đại vương! Nhục thân hiện tại của ông là đồng kim cang thường trụ chẳng hoại hay là biến hoại?  

Vua thưa: Bạch Thế Tôn! Thân con hiện nay trọn theo biến diệt. Phật bảo: Đại vương! Ông chưa từng diệt làm sao biết nó diệt?  

Vua thưa: Bạch Thế Tôn! Thân biến hoại vô thường của con tuy
chưa từng diệt, song con xem hiện tiền niệm niệm đổi dời luôn luôn chẳng dừng, như
lửa tàn thành tro dần dần tiêu mất, mất hết không dừng, nên biết thân này sẽ theo tiêu
diệt.  

Phật bảo: Đại vương! Đúng thế. Nay ông đã già, đi theo suy yếu, nhan mạo đâu
giống lúc còn trẻ?  

Vua thưa : Bạch Thế Tôn! Thuở xưa con còn trẻ da dẻ tươi nhuận,
đến lúc trưởng thành khí huyết sung mãn, nay con già cả suy yếu hình sắc khô khan,
tinh thần mờ tối, tóc bạc mặt nhăn không còn bao lâu sẽ chết, làm sao sánh được với
lúc sung thạnh?  

Phật bảo: Đại vương! Hình dung của ông đâu lẽ già liền?  

Vua thưa: Bạch Thế Tôn! Nó thầm biến hóa đổi dời thật con chẳng biết, nóng lạnh đổi thay dần
dần đến như thế. Vì sao? Khi con hai mươi tuổi tuy nói niên thiếu, nhan mạo đã già
hơn lúc mười tuổi, đến ba mươi tuổi lại suy hơn hai mươi tuổi, nay đã sáu mươi hai
tuổi xem lại thuở năm mươi tuổi rõ ràng cường tráng. Bạch Thế Tôn! Sự thầm đổi dời
tuy đặt thời hạn mười năm, song con suy xét kỹ nó biến đổi đâu những mười năm hai
mươi năm, mà thật dời đổi từng năm; đâu chỉ từng năm, mà dời đổi từng tháng, đâu
những từng tháng mà dời đổi từng ngày. Suy xét chín chắn tế nhị hơn thì khoảng mỗi
sát-na, mỗi niệm đổi dời. Vì thế, biết thân con trọn theo biến diệt.  

Phật bảo: Đại vương! Ông thấy sự biến hóa đổi dời chẳng dừng, ngộ biết thân ông tiêu diệt; cũng
chính khi diệt đó, ông biết trong thân có cái chẳng diệt chăng?  

Vua chấp tay bạch Phật: Thật con chẳng biết.  

Phật bảo: Nay tôi chỉ cho ông biết cái tánh chẳng sanh diệt. Đại
vương! Ông khi mấy tuổi được thấy sông Hằng?  

Vua thưa: Khi con được ba tuổi mẹ bồng đi yết kiến Kỳ-bà Thiên sang ngang sông này, khi ấy là biết sông Hằng.  

Phật bảo: Đại vương! Như ông đã nói, khi hai mươi tuổi già hơn mười tuổi, cho đến sáu mươi
tuổi, năm tháng ngày giờ niệm niệm đổi dời, ắt khi ông ba tuổi thấy sông Hằng đến
năm mười ba tuổi thấy sông Hằng, cái thấy ấy thế nào?  

Vua thưa: Như lúc ba tuổi rõ ràng không đổi, cho đến hiện nay sáu mươi hai tuổi vẫn không có khác.  

Phật bảo: Nay ông tự lo tóc bạc mặt nhăn, quyết định mặt nhăn hơn lúc còn trẻ, song hiện nay ông thấy sông Hằng cùng với cái thấy sông Hằng thuở xưa có trẻ có già chăng?  

Vua thưa: Bạch Thế Tôn! Không.  

Phật bảo: Đại vương! Mặt ông tuy nhăn, song tánh thấy của
ông chưa từng nhăn; nhăn thì biến đổi, chẳng nhăn thì không biến đổi; biến đổi thì bị
sanh diệt, cái không biến đổi vốn không sanh diệt, tại sao ở trong ấy chịu sanh tử với
ông, mà ông dẫn lời Mạc-dà-lê... đều nói thân này sau khi chết là diệt hết? ...

<div style="text-align: right">
*(Kinh Lăng Nghiêm đầu quyển 2 Hán tự)*
</div>

Đọc đoạn kinh này, chúng ta thấy Phật chỉ rõ ràng ngay nơi thân này cái nào
sanh diệt, cái nào chẳng sanh diệt. Thân là dòng biến động thay đổi từng phút giây, tức
là vô thường hoại diệt. Tánh thấy xưa nay chưa từng thay đổi thì làm gì có hoại diệt.
Nói tánh thấy là chỉ cái thấy biết thường xuyên nơi mắt chúng ta, khi chưa hợp tác với
niệm thứ hai để so sánh đẹp xấu hơn kém. Cho đến mắt chúng ta mở hay nhắm, nó
cũng luôn luôn hiển lộ. Nó không lệ thuộc hoàn toàn vào mắt, cơ quan mắt tốt thì nó
hiện sáng tỏ, cơ quan mắt xấu thì nó hiện lu mờ, cho đến cơ quan mắt hoại nó cũng
không bị hoại theo. Đó là đặc tính chẳng sanh chẳng diệt của nó vậy.

Chẳng những thực thể chẳng sanh chẳng diệt hằng biểu lộ ở mắt, mà ở tai nó
cũng có mặt luôn luôn. Cũng kinh Lăng Nghiêm có đoạn:


... Phật bảo La-hầu-la đánh một tiếng chuông, hỏi A-nan: Hiện giờ ông nghe
chăng?  
A-nan và đại chúng đồng thưa: Chúng con nghe.  

Tiếng chuông bặt dứt, Phật lại hỏi: Hiện giờ các ông nghe chăng?  

A-nan và đại chúng đồng thưa: Chẳng nghe.  

La-hầu-la lại đánh một tiếng chuông, Phật hỏi: Hiện giờ các ông nghe chăng?  

A-nan và đại chúng đồng đáp: Nghe.  

Phật hỏi A-nan: Ông tại sao nghe, tại sao chẳng nghe?  

A-nan và đại chúng đồng bạch Phật: Nếu đánh tiếng chuông thì chúng con được nghe,
đánh lâu tiếng bặt âm vang dứt hết thì gọi là không nghe.

Phật lại bảo La-hầu-la đánh chuông, hỏi A-nan: Hiện giờ có tiếng chăng?  

A-nan và đại chúng đồng thưa: Có tiếng.  

Đợi giây lâu tiếng bặt, Phật lại hỏi: Hiện giờ có tiếng chăng?  

A-nan và đại chúng đáp: Không tiếng.  

Giây lát La-hầu-la lại đánh chuông, Phật hỏi: Hiện giờ có tiếng chăng?  

A-nan và đại chúng đồng đáp: Có tiếng.  

Phật hỏi A-nan: Ông nói thế nào là có tiếng, thế nào là không tiếng?  

A-nan và đại chúng đồng bạch: Nếu đánh chuông thì gọi có tiếng, đánh lâu tiếng bặt âm vang dứt
hết thì gọi không tiếng.  

Phật quở A-nan và đại chúng: Hôm nay tại sao các ông tự nói rối loạn?  

Đại chúng và A-nan đồng thời hỏi Phật: Thế nào hôm nay chúng con nói rối loạn?  

Phật bảo: Tôi hỏi các ông nghe thì các ông đáp nghe, tôi hỏi các ông tiếng thì các
ông đáp tiếng. Chỉ nghe với tiếng mà đáp không nhất định. Tại sao như thế chẳng gọi
là rối loạn?

Này A-nan! Tiếng bặt không còn âm vang ông nói không nghe, nếu thật không
nghe thì tánh nghe đã diệt, giống như cây khô, lại đánh tiếng chuông thì ông làm sao
mà biết? Biết có biết không chính là thanh trần *(tiếng)* hoặc có hoặc không, đâu phải
tánh nghe kia là có là không. Nếu tánh nghe thật không thì ai biết nó không? Thế nên,
A-nan! Tiếng ở trong tánh nghe tự có sanh diệt, chẳng phải tánh nghe của ông do có
tiếng, không tiếng mà nó thành có thành không. Ông còn điên đảo nhận lầm tiếng làm
cái nghe, đâu còn lạ gì chẳng mê lầm cho cái thường làm đoạn. Trọn không nên nói lìa
các thứ động tịnh, thông bít mà bảo không có tánh nghe...

<div style="text-align: right">
*(Kinh Lăng Nghiêm cuối quyển 4 Hán tự)*  
</div>

Đây là cái mê lầm chung của toàn thể chúng ta, nhận tiếng làm cái nghe, nhận
hình tướng làm cái thấy. Có tiếng gọi là có nghe, không tiếng gọi là không nghe. Có
hình tướng gọi là có thấy, không hình tướng gọi là không thấy. Nghe thấy là cái giác
tri của chính mình, hình tướng và âm thanh là trần cảnh bên ngoài. Nhận lầm trần cảnh
là mình, trách gì không mất mình và trôi lăn theo cái sanh diệt mãi mãi. Đó là bằng
chứng hiển nhiên để thấy chúng ta đang bị vô minh điên đảo. Nếu ngay nơi đây mà
chúng ta không chịu thức tỉnh, phát minh tánh chân thường chẳng hoại, không biết bao
giờ ra khỏi vòng sanh tử luân hồi.

Đánh thức mọi người giác ngộ thể tánh Chân thường của chính mình, âu cũng
là mục đích chung của chư Phật. Kinh Pháp Hoa có đoạn:

...Này Xá-lợi-phất! Chư Phật tùy nghi nói pháp ý thú khó hiểu. Vì cớ sao? Vì ta
dùng vô số phương tiện các thứ nhân duyên lời lẽ thí dụ diễn nói các pháp. Pháp ấy
không phải do SUY NGHĨ PHÂN BIỆT hay hiểu, chỉ có chư Phật mới hay biết đó. Vì
cớ sao? Vì chư Phật Thế Tôn chỉ do một ĐẠI SỰ NHÂN DUYÊN mà hiện ra đời.

Xá-lợi-phất! Thế nào nói chư Phật Thế Tôn chỉ do một ĐẠI SỰ NHÂN
DUYÊN mà hiện ra đời? Vì chư Phật Thế Tôn muốn chúng sanh MỞ TRI KIẾN PHẬT khiến được thanh tịnh mà hiện ra đời, muốn chúng sanh NGỘ TRI KIẾN
PHẬT mà hiện ra đời, muốn chúng sanh NHẬP TRI KIẾN PHẬT mà hiện ra đời.

Xá-lợi-phất! Đó là chư Phật chỉ do một ĐẠI SỰ NHÂN DUYÊN mà hiện ra
đời...

<div style="text-align: right">
*(Kinh Pháp Hoa phẩm Phương Tiện)*
</div>

Yếu chỉ chư Phật không có hai, duy dẫn đường chúng sanh vào TRI KIẾN
PHẬT. Tri kiến Phật tức là cái thấy biết Phật, sẵn có nơi chúng ta. Chúng ta thấy nhân
nơi sắc tướng, sắc tướng mất, nói không thấy. Biết nhân trần cảnh, trần cảnh không,
nói không biết. Ai thấy sắc tướng mất mà nói không thấy? Ai biết trần cảnh không mà
nói không biết? Quả tang chúng ta quên mất chúng ta một cách đáng thương. Mỗi
hôm, sáng ra vừa mở mắt, chúng ta đã đặt sẵn bao nhiêu vấn đề phải giải quyết trong
ngày nay. Đến tối ăn cơm xong, lên gường nằm kiểm điểm lại đã giải quyết được mấy
vấn đề, còn cặn lại và thêm những vấn đề mới ngày mai phải giải quyết. Cứ thế mãi,
ngày nay ngày mai... cho đến ngày tắt thở mà những vấn đề vẫn chưa giải quyết xong.
Những vấn đề là việc bên ngoài mà thiết tha giải quyết, còn chính ông chủ đặt vấn đề
và giải quyết vấn đề lại quên bẵng. Song ông chủ ấy lại là người không có vấn đề.
Quên mình chạy theo cảnh là cái thấy biết của chúng sanh. Nhân cảnh nhận được tánh
chân thường của chính mình là cái thấy biết Phật *(Tri kiến Phật)*. Quên mình là mê,
nhận được mặt thật của mình là giác. Chuyển mê khai ngộ cho chúng sanh đó là bản
hoài của chư Phật.

Chính vì đánh thức chúng sanh sống trở lại cái thấy biết Phật của mình, đừng
chạy theo trần cảnh mà quên mất mình, kinh Kim Cang có đoạn:

... Thế nên, Tu-bồ-đề! Bồ-tát nên lìa tất cả tướng phát tâm Vô thượng Chánh
đẳng Chánh giác *(Phật)*, không nên trụ nơi sắc, không nên trụ thanh, hương, vị, xúc,
pháp, nên phát tâm không có chỗ trụ. Nếu tâm có trụ tức là chẳng trụ.

<div style="text-align: right">
*(Kinh Kim Cang)*
</div>

Tâm Vô thượng Chánh đẳng Chánh giác là tâm Phật. Tâm Phật không dính mắc
sáu trần, vì sáu trần là pháp sanh diệt, dính mắc pháp sanh diệt là tâm hư vọng của
chúng sanh. Cho nên Bồ-tát muốn an trụ nơi tâm Phật thì không nên dính mắc sáu trần.
Còn chạy theo sáu trần là còn thấy trong có tâm ngoài có cảnh, nằm trong pháp đối đãi
giả dối. Biết trần cảnh duyên hợp giả dối, dừng tâm không chạy theo nó là, sống trở về
tánh chân thật tuyệt đối của mình. Đó là Pháp môn bất nhị trong kinh Duy-ma-cật.

Kinh Duy-ma-cật có đoạn:

Ông Duy-ma-cật nói với các vị Bồ-tát: Các nhân giả! Thế nào là Bồ-tát vào
*“pháp môn không hai”*? Cứ theo chỗ hiểu của mình mà nói.

Bồ-tát Pháp Tự Tại nói: Các nhân giả! Sanh diệt là hai. Pháp vốn không sanh
cũng không diệt, được vô sanh pháp nhẫn, đó là vào *“pháp môn không hai”*.

Bồ-tát Đức Thủ nói: Ngã, ngã sở là hai. Nhân có ngã mới có ngã sở, nếu không
có ngã thì không có ngã sở, đó là vào *“pháp môn không hai”*.

...

Bồ-tát Văn-thù nói: Như ý tôi, đối với tất cả Pháp không nói không bàn, không
chỉ không biết, xa lìa các vấn đáp, đó là vào *“pháp môn không hai”*.


Ngài Văn-thù hỏi ông Duy-ma-cật: Chúng tôi ai cũng nói rồi, đến lượt nhân giả
nói thế nào là *“pháp môn không hai”*?

Ông Duy-ma-cật ngồi im lặng.

Ngài Văn-thù khen: Hay thay! Hay thay! Cho đến không có văn tự ngữ ngôn,
đó mới thật vào *“pháp môn không hai”*.

<div style="text-align: right">
  *(Kinh Duy-ma-cật phẩm Pháp Môn Bất Nhị)*
</div>

Người đọc kinh Phật rất khó hiểu vì cách lập ngôn trong kinh. Thế thường nói
hai hoặc nói một, nếu không phải một, là hai, không phải hai là một. Tại sao trong kinh
nói *“không hai”* mà chẳng nói một? Bởi một đối hai, hai đối một, ở đây chỉ pháp thoát
ngoài đối đãi nên nói *“không hai”*. Nếu có dùng ngôn ngữ cũng vì để dẹp ngôn ngữ,
như đoạn ngài Văn-thù nói. Đến chỗ cứu kính ấy không còn lời để diễn bày, vừa có
diễn bày đều rơi vào đối đãi, chỉ ngay đó nhận được mới là người đạt đạo. Chính đó là
chỗ im lặng của ông Duy-ma-cật. Nói mà không nói là mượn ngôn ngữ để dẹp ngôn
ngữ, không nói mà nói là im lặng để thầm chỉ Chân Lý Tuyệt Đối bặt hết ngữ ngôn.
Đó là thái độ hai vị Bồ-tát ở cuối phẩm này.

Trong các kinh còn đầy dẫy những đoạn chỉ dạy Chân Lý Tuyệt Đối này, chỉ e
dẫn lắm thêm rườm, chúng ta hãy bước sang lãnh vực Thiền sư.

Trước tiên là bài thuyết pháp kỳ diệu của Tổ Huệ Năng:

Sau khi khai ngộ, được Ngũ Tổ truyền y bát bảo trở về phương Nam, Tổ đi đến
ngọn Đại Dữu bị Huệ Minh đuổi theo kịp. Tổ để y bát trên tảng đá vào rừng ẩn. Huệ
Minh đến gặp y bát, song giở lên không nổi, gọi:

\- Hành giả! Tôi đến đây vì pháp, không phải vì y bát.

Tổ nghe gọi, bước ra ngồi trên tảng đá bảo:

\- Nếu ông vì pháp, hãy bình tâm nghe tôi nói.

Huệ Minh đứng yên lặng giây lâu.

Tổ bảo:

\- KHÔNG NGHĨ THIỆN, KHÔNG NGHĨ ÁC, CÁI GÌ LÀ BẢN LAI DIỆN
MỤC CỦA THƯỢNG TỌA MINH?

Nghe câu này, Huệ Minh liền đại ngộ.

Bài thuyết pháp ngắn, gọn này phản ảnh trung thực một sự nghiệp to tát Tổ vừa
lãnh hội nơi Ngũ Tổ và đang mang nó về phương Nam. Chính đó cũng là bản hoài của
chư Phật.

Bản lai diện mục là *“bộ mặt thật xưa nay”* của chúng ta, nó là tên khác của Đạo,
của Pháp thân, của Phật tánh, của Chân tâm... Chúng ta có bộ mặt thật muôn đời không
đổi, mà tự bỏ quên nó, bám vào thân hình tạm bợ cho là thật mình. Cái thân hình đang
chấp giữ là thật mình, nó thay đổi từng phút giây, hợp tan không nhất định. Thế thì lấy
gì bảo chứng cho nó là thật? Quả thật một hình tướng biến thiên, một hợp thể tạm bợ.
Nó có, mà không thật có vì luôn luôn đổi thay, còn mà không thật còn vì hợp tan
chẳng định. Nếu chấp chặt nó là ta, thật là cái ta tạm bợ làm sao! Hoặc có người biết
thân này giả dối, chính cái tâm biết thiện, biết ác, biết phải, biết quấy, tốt xấu... mới
thật là ta. Song cái tâm phân biệt hai bên, cũng là đổi thay tạm bợ. Vì vừa dấy nghĩ về
lành về dữ thì nó đã sanh diệt rồi. Nếu buông hết mọi vấn đề đối đãi, tìm lại nó thì tung
tích vắng tanh. Thế là, ta ở đâu? Mất rồi sao? Thật bối rối vô cùng, nếu chấp cái suy
nghĩ làm ta. Chỉ vì chấp thân tạm bợ, tâm giả dối làm ta nên muôn kiếp trôi lăn trong
sanh diệt, gọi là luân hồi.

Ngay nơi thân tạm bợ, tâm giả dối, chúng ta nhận ra *“bộ mặt thật xưa nay”* của
mình và sống hẳn với nó, dòng sanh diệt ngang đấy liền dừng, kiếp luân hồi đến đây
giải thoát. *“Bộ mặt thật xưa nay”* chưa từng bị sanh diệt, một thực thể không do duyên
hợp, làm gì bị đổi thay, tan hợp? Nó vẫn có và thường còn mà chúng ta quên đi, gọi là
vô minh, nhận ra nó không còn lầm quên nữa, gọi là giác ngộ.

Muốn chỉ *“Bộ mặt thật xưa nay”* cho người, không có cách kỳ diệu nào bằng
câu *“không nghĩ thiện, không nghĩ ác, cái gì là bản lai diện mục của Thượng tọa
Minh”* của Lục Tổ. Người ta cứ thắc mắc *“cái gì là bản lai diện mục của Thượng tọa
Minh”* mà chẳng nhớ *“không nghĩ thiện, không nghĩ ác”*, là tối quan trọng. Chính khi
*“không nghĩ thiện, không nghĩ ác”* là bản lai diện mục của Thượng tọa Minh chớ gì.
Bởi khi tâm bình thường tỉnh táo, không dấy nghĩ thiện ác, phải quấy..., quả là *“bộ mặt
thật xưa nay”* xuất hiện. Vừa dấy nghĩ thiện ác...là động, là chạy theo sanh diệt, “*bộ
mặt thật xưa nay”* bị khuất lấp mất rồi. Cho nên qua câu nói này, Thượng tọa Minh
khéo thấy được *“bộ mặt thật xưa nay”* của mình, gọi là ngộ đạo.

Dưới đây thêm những bài thuyết pháp đơn giản bình dị mà hay tuyệt của các
Thiền sư.

“Thiền sư Tùng Thẩm *(Triệu Châu)* đến tham vấn Nam Tuyền *(Phổ Nguyện)*,
hỏi:

\- Thế nào là đạo?

Nam Tuyền đáp:

\- Tâm bình thường là đạo.

\- Lại có thể nhằm tiến đến chăng?

\- Nghĩ nhằm tiến đến là trái.

\- Khi chẳng nghĩ làm sao biết là đạo?

\- Đạo chẳng thuộc biết chẳng biết, biết là vọng giác, không biết là vô ký. Nếu
thật đạt đạo thì chẳng nghi, ví như hư không thênh thang rỗng rang đâu thể gắng nói
phải quấy.

Ngay câu nói này, Sư ngộ đạo.”

Đạo là tên khác của Bản lai diện mục hay Pháp thân... Nó là thực thể tuyệt đối
nằm sẵn nơi tâm tánh chúng ta. Chúng ta vừa dấy niệm tìm nó, tiến đến nó là trái mất
rồi. Khởi nghĩ biết nó đã rơi vào vọng giác, không nghĩ biết nó để tâm mờ mờ mịt mịt
lại thuộc bệnh vô ký. Dấy tâm phán đoán phải quấy càng xa với đạo.

Câu TÂM BÌNH THƯỜNG LÀ ĐẠO, quả thật đã vén bức màn vô minh cho
mọi người thấy được *“Bộ mặt thật xưa nay”* của mình rồi. Bởi khởi tâm tìm kiếm là
mất bình thường, xét đoán phải quấy là mất bình thường ... Chỉ tâm tỉnh táo sáng suốt
mà không dấy động, mới thật TÂM BÌNH THƯỜNG. Tâm bình thường không tướng
mạo, không hình dáng, thể nó thênh thang rỗng rang đồng với hư không. Thấy được
tâm thể này là người đạt đạo.

<div style="text-align: center">
***
</div>

“Thiền sư Đạo Ngộ bảo đệ tử là Sùng Tín rằng:

\- Ngươi làm thị giả ta, ta sẽ chỉ tâm yếu cho ngươi.

Sùng Tín nhận làm thị giả, trải qua mấy năm mà không được chỉ dạy điều gì.
Sùng Tín thưa:

\- Từ ngày con vào đây đến giờ, chưa được Hòa thượng chỉ dạy tâm yếu.

Đạo Ngộ bảo:

\- Từ ngày ngươi vào đây đến nay, ta chưa từng chẳng chỉ dạy tâm yếu.

\- Chỉ dạy ở chỗ nào?

\- Ngươi dâng trà lên, ta vì ngươi tiếp. Ngươi bưng cơm đến, ta vì ngươi nhận.
Ngươi xá lui ra thì ta gật đầu. Chỗ nào chẳng chỉ dạy tâm yếu?

Sùng Tín cúi đầu suy nghĩ giây lâu.

Đạo Ngộ bảo:

\- Thấy thì thẳng đó liền thấy, suy nghĩ liền sai.

Ngay câu này, Sùng Tín khai ngộ.”

Đạo Ngộ nói Tâm yếu tức là Nam Tuyền nói Tâm bình thường. Trong mọi hành
động ăn cơm, mặc áo, tới lui qua lại của chúng ta đều biểu lộ tâm yếu đầy đủ. Chỉ đáng
tiếc, khi ăn chúng ta chẳng chịu ăn, lại nghĩ đến các việc này, khi mặc chẳng chịu mặc
lại suy các việc nọ. Chúng ta không thể sống được với tâm bình thường trong mọi hoạt
động của mình. Hằng bị vọng tưởng cuốn hút qua mọi lãnh vực hoạt động của nó. Do
đó cả ngày chúng ta mãi đuổi theo vọng tưởng, hết thứ này đến loại khác, không bao
giờ được dừng nghỉ.

Ở đây, Thiền sư Đạo Ngộ chỉ tâm yếu phát hiện nơi dâng trà, nhận cơm, gật
đầu..., thật là bình thường đơn giản. Tâm yếu hằng hiện hữu nơi mọi hoạt động của
chúng ta, mà chúng ta thông qua không chịu nhận. Bởi trong đầu óc chúng ta chứa dẫy
đầy các thứ quái tượng, hiếu kỳ thì làm sao nhận được cái bình thường đơn giản này.
Nói đến Tâm yếu, Đạo, Pháp thân..., chúng ta tưởng tượng phải là cái gì phi thường kỳ
đặc mới được. Đâu ngờ, nó lại là cái rất giản đơn bình dị. Ném phắt mọi vọng tưởng
cuồng loạn, chỉ sống với tâm thể an nhiên trong mọi hoạt động bình thường là, chúng
ta đạt đạo, ngộ tâm yếu. Các lượn sóng lặn hụp trên mặt biển là hiện tượng sanh diệt.
Khi mọi lượn sóng đều lặng yên, chỉ còn một mặt biển phẳng lì, thử hỏi cái gì là sanh
diệt? Có sóng nổi lên là có hình tướng sai biệt, khi sóng lặng hết tìm xem còn hình
tướng gì? Song đến đó không thể nói không có mặt biển. Tâm thể chúng ta cũng thế,
chỉ cần lặng hết mọi vọng tưởng thì thể tánh hiển bày. Thế nên vừa suy nghĩ là lấp mất
thể tánh rồi.

<div style="text-align: center">
***
</div>

“Thiền sư Hoài Hải *(Bá Trượng)* theo hầu Mã Tổ đi dạo vườn, bỗng có bầy
chim bay qua. Mã Tổ hỏi:

\- Bay đó là gì?

Hoài Hải thưa:

\- Bầy vịt trời.

\- Bay đi đâu?

\- Bay qua mất.

Mã Tổ nắm lỗ mũi của Sư vặn mạnh một cái, đau quá Sư la thất thanh.

Mã Tổ bảo:

\- Sao không nói bay qua mất?

Nhân đây Sư tỉnh ngộ.”

Tâm yếu luôn luôn hiển lộ đầy đủ nơi sáu căn, mà chúng ta không nhận thấy.
Chúng ta một bề buông thả sáu căn chạy theo sáu trần. Mắt đối sắc cho là có thấy, sắc
trần qua mất nói là không thấy, lệ thuộc hẳn ngoại cảnh. Sắc trần là tướng sanh diệt
chợt có chợt không, cái thấy biết sắc trần có khi nào sanh diệt, mà chúng ta chỉ nhận
sắc trần không nhận cái thấy. Cái thấy là hiện thân của tâm yếu, là mạng sống ngàn đời
của chúng ta. Thế mà, chúng ta quên đi mạng sống của chính mình, phóng tâm đuổi
theo dòng sanh diệt của ngoại giới. Trường hợp Thiền sư Hoài Hải cũng thế, chỉ nhớ
bầy chim bay qua mất, không nhớ tánh thấy thường còn của mình. Mã Tổ nắm lỗ mũi
vặn mạnh, bảo *“sao không nói bay qua mất”*. Sư chợt tỉnh ngộ cái không mất của
mình, hay thức được giấc mê *“quên mình theo vật”*.

Chúng ta sống nhờ lỗ mũi hít vô thở ra, nó là sanh mạng của mình, lỗ mũi hằng
có mặt thường trực ở trước chúng ta, mà chúng ta khó thấy và ít nhớ. Hằng ngày chúng
ta chỉ nhớ những vấn đề: ăn, mặc, đẹp, xấu... còn hơi thở là điều tối thiết yếu lại quên
đi. Quên hơi thở tức là đã quên mạng sống của mình. Mạng sống đã quên đi thì sự
sống không còn ý nghĩa của sự sống. Sống của cái chết, của cái cuồng loạn. Phật, Tổ
cố đánh thức chúng ta nhớ lại mạng sống của chính mình. Hằng sống với mạng sống
của chính mình, làm gì có nghĩa chết. Như mãi còn thở ra vào, sao nói chết được. Bởi
vì chết là mất đi cái sống, là dừng hơi thở. Tánh thấy hằng hiện hữu nơi chúng ta mà
chúng ta không thấy, ví như lỗ mũi thường có mặt ở trước mắt mà chúng ta dễ quên.
Cái nắm mũi vặn mạnh của Mã Tổ, khiến Thiền sư Hoài Hải đau la thất thanh, liền đó
tỉnh ngộ, quả là diệu thuật trong nhà Thiền, cũng là một bài thuyết pháp không lời kỳ
diệu.

<div style="text-align: center">
***
</div>

“Tướng quốc Bùi Hưu vào viếng chùa Khai Nguyên, thấy trên vách chùa có vẽ
hình Cao tăng, Bùi Hưu hỏi Thiền sư Hy Vận *(Hoàng Bá)*:

\- Hình thấy tại đây, Cao tăng ở đâu?

Sư cất giọng trong thanh gọi:

\- Bùi Hưu!

Bùi Hưu:

\- Dạ!

Sư hỏi:

\- Ở đâu?

Bùi Hưu liền ngộ được hạt châu trên búi tóc.”

Chúng ta đến thăm nhà người bạn, vừa ấn nút chuông điện ngoài cổng, liền có
người mở cửa, bao nhiêu lần cũng thế. Chúng ta biết chắc chắn rằng nhà này có người
gác cửa thường trực. Cũng vậy, nơi tai chúng ta nếu không có cái linh tri thường trực,
khi động làm sao có phản ứng kịp thời. Ở đây vừa gọi liền đáp, không có phút giây
chờ đợi nghĩ suy gì cả. Cho đến đang lúc ngủ say, bỗng có tiếng gọi to cũng giật mình
thức giấc. Càng thấy rõ cái linh tri nơi tai chúng ta không khi nào vắng mặt. Chỉ khi
thức các cơ quan hoạt động thì nó sáng, lúc ngủ các cơ quan đóng bít thì nó mờ. Cái
linh tri này mới thật là Chủ nhân ông hay *“Bộ mặt thật xưa nay”* của chúng ta. Chúng
ta quên lửng ông chủ, cứ chạy theo khách trần bên ngoài. Một bề quên mình theo vật,
nên mãi trầm luân sanh tử. Đang lúc hoạt động lăng xăng, có người hỏi: cái gì là ông
chủ, chúng ta bàng hoàng sửng sốt không biết đáp thế nào. Thế là, hằng ngày chúng ta
nói sống vì mình, lo cho mình, mà quả thật chúng ta đã mất mình. Nếu biết rõ ông chủ
của mình, chúng ta mới dám nói thật sống, bằng không biết ông chủ thế nào, làm sao
nói rằng mình đang sống được. Có hoạt động có sống cũng chỉ là cuộc sống vay mượn
mà thôi.

Ông Bùi Hưu thấy hình Cao tăng mà không biết Cao tăng ở đâu. Đó là tâm
trạng quên mất ông chủ, đang thao thức dò tầm. Một tiếng gọi của Thiền sư Hy Vận,
dường như một tiếng sét ngang tai, khiến ông bất chợt ứng thanh *“dạ”*, chồng thêm
một câu hỏi *“ở đâu”,* hốt nhiên ông sáng mắt. Ông chủ đã lâu ông băn khoăn thắc mắc
kiếm tìm, bất chợt hiện lồ lộ trước mắt. Hạt châu quí trong búi tóc của nhà vua, trong
kinh Pháp Hoa, chỉ dành tặng riêng cho vị tướng quân có công to nhất, hôm nay ông
nhận được. Cái cao cả quí báu nhất trong đời sống con người là ông chủ. Nhà không
có chủ là nhà hoang, xác thân không nhận ra ông chủ là xác thân rỗng. Vì thế, mục
đích duy nhất của Phật, Tổ là chỉ cho chúng ta nhận ra ông chủ. Ông chủ ấy hằng có
mặt nơi tai, mắt... chúng ta, chỉ khéo nhận liền thấy.

<div style="text-align: center">
***
</div>

“Thiền sư Sư Bị *(Huyền Sa)* ngồi trong thất, có vị Tăng đứng hầu, nhìn xuống
nền thất có một điểm trắng, Sư hỏi Tăng:

\- Ông thấy chăng?

Tăng thưa:

\- Thấy.

Sư bảo:

\- Ta thấy ông cũng thấy, tại sao có người ngộ người không ngộ?”

Hai thầy trò đồng thấy một điểm trắng trên nền thất, tại sao thầy ngộ mà trò lại
mê? Bởi vì trò thấy chỉ thấy cái bị thấy, cho nên quên mất ông chủ tức là mê. Thầy
thấy mà không chạy theo cái bị thấy, nhân cái bị thấy nhận ra ông chủ hay thấy của
chính mình, tức là ngộ. Đồng một cảnh mà mê ngộ khác nhau, gốc tại quên mình theo
vật hay nhân vật nhận được mình. Ở hội Linh Sơn đức Phật đưa cành hoa sen lên, Tôn
giả Ca-diếp miệng cười chúm chím, đồng ý nghĩa này. Chư Tổ Thiền tông tận dụng
mọi phương tiện, nào đưa tay, dựng phất tử... khiến người nhận được ông chủ qua cái
thấy của mình.

Ngay khi thấy sự vật, tâm không bị dấy một niệm nào, chính khi ấy “*bộ mặt
thật xưa nay”* bày hiện. Vì có thấy là có biết, cái biết không do suy nghĩ, không do
phân biệt, mới là cái biết chân thật, thoát ngoài đối đãi sanh diệt. Cái biết do suy nghĩ,
do phân biệt đều là động, tạm có rồi không, làm sao nói chân thật được. Cái suy nghĩ
phân biệt lặng xuống, tánh giác tri hiện bày rỡ rỡ, nó mới thật là ông chủ muôn đời của
ta. Giác tri mà lặng lẽ thì làm gì có sanh diệt. Chỗ này còn nghi ngờ gì, không nói nó
chân thật vĩnh cửu. Thế nên, mắt thấy sắc tướng mà nhận được tánh thấy của mình, là
ngộ đạo, trái lại là mê.

<div style="text-align: center">
***
</div>

“Thiền sư Cảnh Thanh ngồi trong thất, có vị Tăng đứng bên cạnh, Sư hỏi:

\- Bên ngoài có tiếng gì?

Tăng thưa:

\- Tiếng con nhái bị con rắn bắt kêu.

Sư nói:

\- Sẽ bảo chúng sanh khổ, lại có khổ chúng sanh.

Hôm khác, Sư hỏi vị Tăng bên cạnh:

\- Bên ngoài có tiếng gì?

Tăng thưa:

\- Tiếng mưa rơi.

Sư bảo:

\- Chúng sanh điên đảo quên mình theo vật.

\- Hòa thượng thì sao?

\- Vẫn chẳng quên mình.

\- Vẫn chẳng quên mình, ý nghĩa thế nào?

\- Xuất thân còn là dễ, thoát thể nói rất khó.”

Rắn bắt nhái đó là chúng sanh khổ, vì con lớn hiếp con bé. Song lại có khổ
chúng sanh, chính là người quên mất mình chạy theo ngoại cảnh. Hằng ngày tai chúng
ta chỉ lắng nghe tiếng động tịnh bên ngoài, có khi nào nhận biết mình có tánh nghe
thường trực. Vừa nghe tiếng động liền phân biệt thuộc loại nào, hay dở, lợi hại , phải
quấy... rồi sanh tâm yêu ghét. Cứ thế mãi không dừng, làm sao chẳng bảo là *“chúng
sanh điên đảo quên mình theo vật”*? Chỉ có người tỉnh giác mới biết phản quan lại
mình, mọi động tịnh bên ngoài đều là pháp sanh diệt, ông chủ biết được mọi động tịnh
ấy mới là người chẳng sanh diệt. Vì khi động vẫn biết động, lúc tịnh vẫn biết tịnh, hai
tướng động tịnh đuổi nhau, ông chủ vẫn ngồi yên xem sự đổi thay của chúng. Người
biết sống trở về ông chủ của mình, mặc sự sanh diệt đổi thay của trần cảnh, là *“vẫn
không quên mình”*. Chỗ không quên mình ấy, làm sao diễn tả được, nên nói *“xuất thân
còn là dễ, thoát thể nói rất khó”*.

Tai nghe tiếng mà không chạy theo phân biệt tiếng, lại nhận nơi mình hằng có
tánh nghe, là pháp tu *“Phản văn văn tự tánh”* của Bồ-tát Quán Thế Âm. Âm thanh nhỏ
lớn xa gần lúc nào cũng có, tánh nghe thường hằng nên mới thường nghe. Nếu tánh
nghe có gián đoạn, ắt chúng ta có khi nghe khi không. Song không khi nào chúng ta
chẳng nghe, dù khi không có tiếng động vẫn nghe không tiếng. Đây là chứng cứ cụ
thể, tánh nghe thường trực nơi mọi người chúng ta. Trong các phương pháp tu *“trở về
tự tánh”*, biết phản chiếu lại tánh nghe của mình là ưu việt hơn cả. Cho nên trong kinh
Lăng Nghiêm đức Phật bảo Bồ-tát Văn-thù chọn phương pháp nào viên thông, Ngài
chọn ngay pháp *“nhĩ căn viên thông”* của Bồ-tát Quán Thế Âm.

Thiền sư có đến ngàn vạn phương tiện, lãnh hội một thì tất cả đều thông. Sau
khi thông lý tuyệt đối, có giá trị thế nào?

Bởi vì tất cả chúng ta đều trông thấy mọi lẽ tạm bợ của cuộc đời, khiến khát
khao tìm kiếm hướng về chỗ trường cửu miên viễn. Song nói đến chỗ này, dường như
mọi người đều thở dài tự nhận là vô phần. Hầu hết đều bó tay cúi đầu trước thực thể
bất sanh bất diệt ấy. Khao khát ước mơ mà không thể tìm được, không dám mò tới,
thật là đau đớn vô cùng. Một khi bất ngờ bắt gặp được nó thì còn gì sung sướng cho
bằng. Chính tâm trạng Tôn giả Xá-lợi-phất v.v... ở trong kinh Pháp Hoa cũng thế. Từ
khi tu hành cho đến nay, các ngài chỉ mong được quả Nhị thừa, không khi nào dám
ước mơ đến Phật quả. Bất ngờ được đức Phật thọ ký cho sẽ thành Phật, thật là một
điều quá sức ước mong. Nói thí dụ chàng cùng tử được ông trưởng giả trao sự nghiệp
để bày tỏ tâm trạng của các Ngài. Thiền sư Thủy Lạo nói với đồ đệ: *“Từ khi ăn cái đạp
của Mã Tổ đến giờ, cười mãi không thôi”*. Thiền sư Huệ Hải cũng nói: *“Từ khi nhận
được kho báu nhà mình đến nay, dùng mãi không thiếu”*. Cười mãi không thôi, vì hạt
châu vô giá bị đánh mất, bất chợt tìm thấy nắm được trong tay, kể từ đây hết rồi một
kiếp lang thang nghèo đói. Dùng mãi không thiếu, vì nó là kho báu vô tận, ứng dụng
tùy tâm, nên gọi là *“bảo châu như ý”*. Có được hạt bảo châu như ý trong tay, tự thân
mọi nhu cầu đều toại nguyện, còn thêm tùy ý cứu giúp tha nhân. Thật là tự lợi, lợi tha
viên mãn.

Hạt *“Minh châu vô giá”* hay *“Bảo châu như ý”*, đều do đức Phật lấy làm thí dụ
để chỉ thể tánh tuyệt đối này. Bởi vì mạng sống là cứu kính của chúng sanh, mạng
sống càng dài thì giá trị càng cao. Cho nên ở thế gian không ơn gì to bằng ơn cứu
mạng. Chỉ cần được cứu sống thêm một vài mươi năm, người ta cho đó là ơn sâu trời
bể. Đạt được thể tánh này, là nhận lấy sanh mạng trường tồn miên viễn, vượt ngoài
vòng thời gian, không còn dùng con số nào tính kể được. Đức Phật dùng thí dụ *“điểm
mực”* nơi phẩm Như Lai Thọ Lượng trong kinh Pháp Hoa là nói rõ ý này. Đem thế
giới tam thiên nghiền thành bụi nhỏ, lấy bụi ấy làm mực, đi sang phương đông trải qua
trăm ngàn muôn ức thế giới mới điểm một điểm mực..., gom hết những thế giới có
điểm mực không điểm mực đã đi qua, nghiền nát thành bụi, mỗi hạt bụi tính là một
kiếp, thử tính tuổi thọ Phật là bao nhiêu? Dù có nhà toán học tài tình mấy cũng không
sao tính nổi tuổi thọ của Phật. Phật ở đây là chỉ Phật pháp thân, tức là thực thể tuyệt
đối sẵn có nơi mọi chúng sanh vậy.

Thực thể này không những vượt ngoài thời gian, mà cũng bao trùm khắp không
gian. Kinh Hoa Nghiêm đức Phật dùng thí dụ *“phá vi trần xuất kinh quyển”*, để nói lên
thể rộng lớn của nó. Nói rằng *“Có một quyển kinh lượng bằng thế giới tam thiên đại
thiên, vò tròn nhét trong hạt bụi nhỏ, có người trí tuệ xem biết, dùng phương tiện đập
vỡ hạt bụi lấy quyển kinh. Trong quyển kinh ghi chép đầy đủ mọi sự thật của thế giới
tam thiên đại thiên...”*.  

Quyển kinh dụ thể tánh tuyệt đối hay Phật tánh, hạt bụi dụ thân
tứ đại của chúng sanh. Muốn biết mọi sự vật trong vũ trụ, không gì hơn ngay nơi thân
này nhận ra thể tánh tuyệt đối, mọi sự thật hiện bày đầy đủ trong ấy. Có ai ngờ trong
hạt bụi nhỏ lại chứa quyển kinh to như thế, chỉ người trí tuệ *(Phật)* mới nhận thấy được
nó. Chúng ta không khi nào dám thừa nhận mình có thể tánh rộng lớn trùm khắp vũ
trụ, mà hằng tự nhận mình như cây lau, cây sậy trên địa cầu, như hạt cát trong bãi sa
mạc.  

Vì thế, đọc kinh Duy-ma-cật thấy nói *“ông Duy-ma-cật đưa tay nắm thế giới dời
đi nơi khác...”*, làm sao chúng ta dám tin. Tôn giả A-nan sau khi ngộ được chân tâm,
bạch Phật rằng: *“con xem thân cha mẹ sanh (so với chân tâm) như hạt bụi trong hư
không, như hòn bọt ngoài bể cả...” (Kinh Lăng Nghiêm)*.  

Tuệ Trung Thượng Sĩ, một Thiền sư Việt Nam, có vị tăng hỏi: *“Sanh tử là việc lớn làm sao giải quyết?"*  

Thượng sĩ đáp: *“Trong hư không dài có chướng gì hai vành xe, ngoài bể cả có ngại gì hòn bọt nổi.”*  

Ý nói rằng, sự sanh tử của thân này đối với pháp
thân như hai vành xe ném trong hư không, như hòn bọt nổi trong bể cả, có nghĩa lý gì
mà quan trọng. Hạt bụi sánh với hư không, hòn bọt so với bể cả, giá trị quá rõ ràng,
nên nói *“viên ngọc vô giá”*.

Sống được với thể tánh này thì diệu dụng vô cùng, lợi mình lợi người viên mãn.
Hằng ngày chúng ta chỉ sống với vọng tưởng, mà còn có trăm ngàn tác dụng, tạo ra
trăm điều ngàn việc. Phương chi sống với thể tánh linh minh thì diệu dụng làm sao
lường được. Căn cứ hiện tượng thế gian phán xét, để thấy rõ điều này. Trên thế gian
cái gì càng thô thì dụng càng yếu, cái gì càng tế thì dụng càng mạnh. Như đất thể thô
hơn nước, nên bị nước cuốn; nước thể thô hơn gió, nên bị gió đùa. Sức mạnh của gió
làm tan cả đất, cuộn phăng cả nước mà không thấy hình dáng tướng mạo gì. Sức mạnh
của nguyên tử, của khinh khí cũng tương tợ như thế. Vọng tưởng là tướng tâm duyên
theo pháp trần... nên có tướng mạo. Khi tâm ta tưởng quả núi, liền có quả núi hiện nơi
tâm, tâm nhớ người liền có người hiện... Dấy tâm thì có cảnh, tâm cảnh dính liền nhau.
Tâm không rời cảnh, đó là tâm hư vọng cũng gọi là vọng tưởng. Cảnh có đến ngàn vạn
nên tâm duyên cảnh cũng cả trăm thứ. Có tướng mạo là tâm thô, chia nhiều thứ là bị
phân tán. Tâm thô và phân tán nên công dụng của nó yếu ớt tầm thường. Khi vọng
tưởng đã lặng sạch, chỉ còn một tâm thể linh minh, không hình dáng tướng mạo, nên
ứng dụng vô cùng. Đến chỗ này gọi là *“diệu dụng không thể nghĩ bàn”*. Bởi diệu dụng
không thể nghĩ bàn, nên dụ là Bảo Châu Như Ý. Nắm hạt châu này trong tay thì mọi
việc đều như ý, tức là mãn nguyện tự tại. Một bên công dụng tầm thường cuộc hạn,
một bên diệu dụng không thể nghĩ bàn tự do tự tại, đối chiếu nhau chúng ta thấy rõ giá
trị sai biệt của đôi bên rồi.

Chân lý tuyệt đối không có ở bên ngoài, mà nằm sẵn ngay nơi chúng ta. Chúng
ta muốn tìm nó, phải biết quay lại mình, đừng chạy ra ngoài tìm kiếm vô ích. Chân lý
tuyệt đối nơi mình, chính là ông chủ của mình, nhận ra ông chủ thì mọi chân lý trong
vũ trụ đều thấy rõ. Nhận ra và sống được với ông chủ của mình thì, vòng luân hồi
chấm dứt, mọi khổ đau hết sạch, được giác ngộ giải thoát hoàn toàn.
