
# Học Phật bằng cách nào? {- #hoc-phat-bang-cach-nao}

Hỏi học Phật bằng cách nào, tức là hỏi đến phương pháp học Phật. Ở thế gian
môn học nào cũng có phương pháp riêng của nó. Ví như môn toán học, người học trò
trước phải biết số, kế học thuộc cửu chương, học cách cộng trừ nhân chia, lên nữa phải
học công thức, phương trình v.v... Môn văn chương, trước phải biết chữ cái, học ráp
vần, viết chánh tả, học văn phạm, tập cách làm văn v.v... Phương chi Phật pháp là môn
học giác ngộ, mà không có phương pháp riêng của nó hay sao?

Phương pháp học Phật tức là ba môn Tuệ học: Văn tuệ, Tư tuệ, và Tu tuệ. Bởi
vì muốn vào cửa giác ngộ không phải anh tướng trí tuệ thì không sao vào được. Phật
pháp là chân lý là những sự thật, nếu không có ngọn đuốc trí tuệ soi sáng, làm sao
chúng ta thấy mọi sự thật ở chung quanh, không cần trí tuệ, chỉ dùng lòng tin đến với
đạo Phật, để học Phật pháp, thật là sai lầm lớn lao. Đây là chứng bệnh trầm trọng của
Phật tử hiện thời. Cần chữa lành bệnh này, chúng ta phải ứng dụng triệt để ba môn Tuệ
học vào công trình tu học Phật pháp.

## Thế nào là Văn tuệ? {- #van-tue}

Văn là nghe, do nghe giáo lý Phật pháp trí tuệ mở sáng, gọi là Văn tuệ. Chúng
ta nghe Phật pháp qua lời giảng dạy của chư Tăng, của thiện hữu tri thức đã tu học
trước ta. Những lời giảng dạy ấy xuất phát từ kinh điển của Phật, trong đó chứa toàn
lời lẽ chân chánh, chỉ bày mọi sự thật cho chúng sanh. Càng nghe trí tuệ chúng ta càng
sáng. Hoặc chúng ta trực tiếp đọc kinh sách Phật, khiến mở mang trí tuệ cũng thuộc
Văn tuệ. Chịu khó nghe giảng dạy, chịu khó nghiên cứu kinh sách Phật, đó là người
biết từ cửa Văn tuệ tiến thẳng vào ngôi nhà Phật pháp.

## Thế nào là Tư tuệ? {- #the-nao-la-tu-tue}

Tư là suy xét phán đoán, do suy xét phán đoán những lời dạy trong Phật pháp,
trí tuệ càng tăng trưởng. Chúng ta được nghe lời chỉ dạy của thầy bạn, dẫn từ trong
kinh Phật ra, song nghe rồi tin liền là chưa đủ tư cách học Phật. Buộc chúng ta phải
dùng trí phán đoán xem đúng hay sai, nếu quả thật đúng, từ đó chúng ta mới tin. Có
thế mới thực hành đúng câu *“các người phải tự thắp đuốc lên mà đi, thắp đuốc lên với
chánh pháp”*, trong kinh Pháp Cú. Chúng ta muốn mở mang trí tuệ, song tự mình làm
sao mở được, phải mồi ngọn đuốc trí tuệ của mình với ngọn đuốc chánh pháp của Phật,
trí tuệ mới phát sáng.

Mồi bằng cách nào?

Ví như chúng ta nghe vị Sư giảng rằng: *“Tất cả thế gian đều là vô thường”*. Sau
đó phải dùng trí tuệ của mình phán đoán xem đúng hay không. Chúng ta tự đặt câu
hỏi: Tất cả thế gian đều là vô thường, có sự vật nào thoát ngoài luật lệ ấy chăng? Nếu
có, câu nói này chưa phải chân lý. Bằng không, mới thật đúng chân lý, chúng ta sẽ
hoàn toàn tin. Thế rồi, ta tự khảo sát :

Con người có phải vô thường không? Từ ông bà đến cha mẹ chúng ta đều có
sanh ra, lớn lên, bệnh hoạn, già yếu rồi chết. Kể luôn cả ta, khi nào còn nhỏ bé, lớn lên,
bệnh hoạn, già yếu, rồi cũng sẽ chết. Trong gia đình thân tộc chúng ta đã thế, ngoài xã
hội cũng thế, cả nhân loại trên thế giới cũng thế; ngàn xưa là thế, mãi sau này cũng thế.
Quả là con người vô thường.

Đến những sự vật, nào nhà cửa, bàn ghế, xe cộ... có bị vô thường không? Chính
cái nhà của mình, khi mới cất thì tốt đẹp lành lặn, qua vài ba năm thấy cũ dần, đến năm
mười năm thì hư sập. Cái bàn viết cũng thế, khi mới đóng xem bóng loáng tốt đẹp,
dùng mấy năm thấy đã cũ, tróc sơn khờn mặt, rồi đây sẽ mục nát hư hoại. Chiếc xe đạp
khi mới mua đem về mới toanh, chạy được một năm vỏ đã rách, cổ lỏng, các con ốc
lờn... vài năm nữa sẽ hư. Thế là, nhà cửa, bàn ghế, xe cộ... những vật cần dùng bên
cạnh chúng ta thảy bị vô thường chi phối. Cho đến trăm ngàn vật khác, nếu khảo sát
đều thấy đồng một số phận như nhau.

Chúng ta có thể kết luận rằng: *“tất cả thế gian là vô thường”*, quả thật là chân
lý. Ta tin chắc lẽ này, dù có ai nói khác đi, cũng không làm lay động được lòng tin của
ta. Bởi lòng tin này đã được gạn lọc qua sàng lý trí, nên nó vững chắc không dễ gì làm
lung lay.

Lại một thí dụ, chúng ta nghe vị Sư giảng lý luân hồi, bảo rằng: *“Muôn vật ở
thế gian đều xoay quanh vòng luân hồi”*. Ta tự đặt câu hỏi: Tại sao muôn vật đều luân
hồi? Có vật nào không luân hồi chăng? Chúng ta bắt đầu xét từ thực vật:

Cây cối thành hình bắt nguồn từ hạt, hạt nẩy mầm tăng trưởng thành cây, nở
hoa, kết trái; trái sanh hạt, hạt lại nẩy mầm... lộn đi đảo lại không cùng. Song đó là sự
lộn đi đảo lại từ cây này sang cây khác, ngay bản thân cây ấy có đảo lộn vậy không?
Cũng lộn đi đảo lại như thế. Thân cây hiện sống đây, do châm rễ hút đất nước... nuôi
dưỡng mới được sanh trưởng, dần dần thành đại thọ. Rễ hút đất nước nuôi dưỡng thân
cành lá, lá rụng biến thành phân đất, cành gãy mục cũng thành phân đất, thân cây ngã
mục cũng trở về đất nước. Thân cây nhờ đất nước sanh trưởng, khi ngã mục lại trở về
đất nước.

Nước do ánh nắng bốc thành hơi, hơi lên cao gặp khí lạnh đọng lại, rơi xuống
thành nước; nước lại bốc hơi... mãi mãi không cùng.

To như quả địa cầu vẫn quay tròn quanh cái trục, sáng rồi tối, tối lại sáng. Căn
cứ vào sự quay tròn của nó, người ta chia ra ngày giờ tháng năm, thời tiết xuân hạ thu
đông, xoay vần thế mãi không cùng.

Do sự khảo sát trên, chúng ta khẳng định rằng *“muôn vật ở thế gian đều xoay
quanh vòng luân hồi”*, là sự thật không còn gì phải nghi ngờ.

Trên đây tạm cử vài thí dụ làm căn bản cho công cuộc suy xét phán đoán Phật
pháp. Căn cứ vào đây, chúng ta phán xét những lời Phật dạy, hoặc chư tăng dạy trong những trường hợp khác. Có thế, mới phân biệt được chánh tà và  mới đúng tinh thần người học Phật.

## Thế nào là Tu Tuệ? {- #tu-tue}

Sau khi phán xét lời Phật dạy là đúng, chúng ta đem áp dụng trong cuộc sống
hằng ngày của mình, khiến chánh lý càng bày hiện sáng tỏ, là tu tuệ. Ví như, đã biết rõ
*“tất cả thế gian là vô thường”*, chúng ta ứng dụng sự vô thường vào đời sống của mình,
trong những trường hợp như sau:

Đã biết rõ thế gian là vô thường, khi gặp vô thường đến với bản thân, với gia
đình ta, ta vẫn giữ bình tĩnh không hốt hoảng hãi sợ. Vì biết chắc điều đó ở thế gian
không ai tránh khỏi, sợ hãi kinh hoàng chỉ làm rối thêm vô ích. Bởi không sợ nên tâm
ta bình tĩnh sáng suốt, giải quyết mọi việc một cách tốt đẹp. Chúng ta vẫn đủ sáng suốt
để khuyên giải cho những người đồng cảnh ngộ bớt đau khổ.

Biết rõ thế gian là vô thường, mọi sự tranh giành danh lợi, tài sắc... lòng ta
nguội lạnh. Tranh giành những thứ tạm bợ ấy làm gì, để rồi chuốc khổ về mình, gây
đau khổ cho người, rốt cuộc chỉ thành việc mò trăng bắt bóng. Lòng tham lam giành
giật dục lạc thế gian, do đây dứt sạch.

Do thấy rõ lẽ vô thường, chúng ta không thể ngồi yên chờ chết. Phải cố gắng
làm mọi việc lành, nếu cơn vô thường đến, chúng ta có muốn làm cũng không sao làm
được. Lại biết quí tiếc thời giờ, một ngày qua rồi không tìm lại được, phải cấp bách nỗ
lực làm lợi mình lợi người, không thể chần chờ.

Đó là ba trường hợp do biết *“thế gian vô thường”*, chúng ta khéo ứng dụng tu
hành trong cuộc sống hiện tại của mình. Bao nhiêu sự lợi ích tốt đẹp sẽ theo đó mà
tăng trưởng. Sự tu hành ấy, đi đôi với tâm trí tỉnh táo sáng suốt, nên gọi là *“Tu tuệ”*.

Ví dụ khác, chúng ta nhận rõ *“muôn vật luân hồi”*, liền ứng dụng lý luân hồi
vào cuộc sống của mình. Nếu phải luân hồi, chúng ta chọn cái luân hồi nào tốt đẹp an
ổn hơn. Ví như, biết các loài thảo mộc từ hạt nẩy mầm, sanh trưởng thành cây, đơm
hoa, kết quả; hạt lại nẩy mầm... Chúng ta nên chọn lựa hạt tốt giống ngon đem ương,
để sau này kết quả ngon, cho ta và mọi người được thưởng thức vị ngon. Cũng thế,
trong vòng luân hồi bản thân ta cũng không thoát khỏi, ta cần tạo những nhân tốt, nhân
an vui, để mai kia có lăn lộn cũng lăn lộn trong chỗ tốt, chỗ an vui.

Đã biết muôn vật luân hồi, chúng ta phải tìm xem nguyên nhân nào lôi cuốn vào
trong ấy. Biết rõ nguyên nhân rồi, phải tìm cách thoát ra ngoài vòng luân hồi. Không
đầu hàng khuất phục, để chịu lăn mãi trong luân hồi. Như các nhà khoa học nghiên cứu
biết sức hút của quả đất, sau đó tìm cách chế phi thuyền đủ sức mạnh vượt ra ngoài
vòng hút của quả đất, đi thẳng vào quĩ đạo v.v... Biết luân hồi để tìm cách thoát ra,
chính là tinh thần *“Tu tuệ”*.

Văn tuệ, Tư tuệ rất cần thiết, song Tu tuệ lại càng quan trọng hơn. Nếu có văn
tuệ, tư tuệ mà thiếu tu tuệ thì chỉ là tuệ rỗng, không lợi ích thiết thực cho đời sống con
người. Nhờ tu tuệ mới thẩm định được giá trị văn, tư ở trên và giúp cho văn, tư được
kết quả viên mãn.

Vì thế, đức Phật dạy hàng Phật tử đi chùa là cốt gặp Sư tăng, Sư ni, gặp Tăng
ni rồi cần phải thưa hỏi Phật pháp, thưa hỏi xong phải ghi nhớ, ghi nhớ rồi cần phán xét, phán xét rồi phải tiến tu. Được vậy mới đúng tinh thần Phật tử
*(Phỏng theo bài kinh Ma-ha-nam trong Tạp A-hàm)*.  

Bồ-tát Quán Thế Âm cũng trình với Phật, thuở quá khứ lâu xa Ngài gặp Phật dạy tu phương pháp văn, tư, tu được vào
chánh định và cho hiệu là Quán Thế Âm *(Kinh Lăng Nghiêm)*. Chính trong giới Bồ-
tát, Phật cũng dạy *“dù ở xa trăm ngàn dặm, nghe có người nói kinh luật, người mới thọ
giới Bồ-tát cũng phải mang kinh luật đến đó học” (Kinh Phạm Võng)*. Quả nhiên đức
Phật không chấp nhận đệ tử tu hành tối dốt, phải đầy đủ ba môn Tuệ học, mới xứng là
đệ tử của Ngài.

Ba môn Tuệ học này hoàn toàn thích hợp với tinh thần khoa học hiện nay. Bất
luận môn học nào, trước tiên học lý thuyết, kế phê bình lý thuyết, sau thí nghiệm hay
thực hành lý thuyết. Lý thuyết tức là văn tuệ, phê bình tức là tư tuệ, thí nghiệm, thực
hành là tu tuệ.
