
# Kết luận {- #ket-luan}

Những vấn đề đã trình bày qua, chúng tôi cố gắng cô đọng trong một khuôn khổ
rất nhỏ hẹp, giống như việc *“lấy thúng úp voi”*, khó tránh khỏi lỗi khó hiểu và thiếu
sót. Chúng tôi chỉ mong độc giả nhận được then chốt của mỗi vấn đề, cần đi sâu vào
chi tiết, sẽ nhờ những quyển kinh sách khác, hoặc nhờ sự dắt dẫn của Tăng, Ni hay
Thiện hữu. Ôn lại then chốt thiết yếu, có thể nói:  

Phật là người đã giác ngộ và giải thoát sanh tử, đó là vị trí căn bản của Ngài.
Chúng ta đừng xê dịch, đừng tô điểm, dừng ép buộc Ngài phải rời chỗ căn bản ấy.
Phật pháp là những lời giảng dạy chỉ ra lẽ thật: Lẽ thật trên hình tướng sự vật là
nhân quả, lẽ thật trong sự cấu tạo kết hợp là duyên sanh, lẽ thật thầm lặng trong bản
thể là chân không hay Phật tánh.  

Học Phật là tiến bước trên con đường giác ngộ, là nhận hiểu phán xét những lẽ
thật của Phật dạy, đem chỗ nhận hiểu ứng dụng vào cuộc sống con người. Thực hiện
được những điều này, cần nhờ cặp mắt trí tuệ sáng suốt mới thành công.
Tu Phật là ứng dụng những lẽ thật đã nhận xét được vào cuộc sống hằng ngày
của mình. Gỡ sạch mọi phiền não kiến chấp đang trói buộc khắn chặt trong tâm tư
chúng ta, đem lại sự an lạc ngay trong hiện tại và miên viễn ở vị lai. Chẳng những thế,
tu Phật còn có nghĩa vượt ra ngoài vòng đối đãi sanh diệt, thoát khỏi mọi khuôn khổ
hạn cuộc, làm người tự do tự tại.  

Với những điểm chủ yếu trên, chúng ta nhận thức chắc chắn sâu xa, là trong tay
đã có sẵn ngọn đuốc sáng, trên con đường về quê ắt không đến nỗi lạc lầm. Giá trị của
Phật pháp là biết để hành, không phải biết để nói. Thực hành sâu chừng nào, càng thấy
giá trị Phật pháp cao chừng ấy. Biết để nói, là người trình bày đủ mọi thức ăn, mà bụng
vẫn đói; là nhân viên phát ngân trong ngân hàng cả ngày đếm tiền, khi ra về chỉ hai tay
không. Chúng tôi ước mong độc giả của quyển sách này không đến nỗi như thế.
